	#base	"../../../#users/custom/resource/ui/huditemeffectmeter_sapper.res"
	#base	"../../../#users/ly_dee/resource/ui/huditemeffectmeter_sapper.res"
	#base	"../../../#users/jayhyunpae/resource/ui/huditemeffectmeter_sapper.res"
	#base	"../../../_stream/resource/ui/huditemeffectmeter_sapper.res"
	#base	"../../../_budhud/resource/ui/huditemeffectmeter_sapper.res"
	#base	"../../../_tf2hud/resource/ui/huditemeffectmeter_sapper.res"