	#base	"../../../#users/custom/resource/ui/targetid.res"
	#base	"../../../#users/jayhyunpae/resource/ui/targetid.res"
	#base	"../../../#customization/_enabled/bh_targetid_healthcross2.res"
	#base	"../../../_stream/resource/ui/targetid.res"
	#base	"../../../_budhud/resource/ui/targetid.res"
	#base	"../../../_tf2hud/resource/ui/targetid.res"