	#base	"..\..\#customization\_enabled\bh_chat_lowerleft.res"
	#base	"..\..\#customization\_enabled\bh_chat_upperleft.res"
	#base	"..\..\_stream\resource\ui\basechat.res"
	#base	"..\..\_budhud\resource\ui\basechat.res"
	#base	"..\..\_tf2hud\resource\ui\basechat.res"