	#base	"..\..\#customization\_enabled\bh_biggeruber.res"
	#base	"..\..\#customization\_enabled\bh_ubernearcrosshair.res"
	#base	"..\..\_stream\resource\ui\hudmediccharge.res"
	#base	"..\..\_budhud\resource\ui\hudmediccharge.res"
	#base	"..\..\_tf2hud\resource\ui\hudmediccharge.res"