"Resource/UI/HudObjectiveTimePanel.res"
{	
	"TimePanelBG"
	{
		"ControlName"			"ScalableImagePanel"
		"fieldName"				"TimePanelBG"
		"xpos"					"25"
		"ypos"					"0"
		"zpos"					"2"
		"wide"					"56"
		"tall"					"20"
		"visible"				"1"
		"enabled"				"1"
		"image"					"../hud/objectives_timepanel_blue_bg"
		"scaleImage"			"1"
		"src_corner_height" 	"3"
		"src_corner_width" 		"3"
		"draw_corner_width" 	"0"
		"draw_corner_height" 	"0"
	}
	"TimePanelProgressBar"
	{
		"ControlName"			"CTFProgressBar"
		"fieldName"				"TimePanelProgressBar"
		"xpos"					"6969"
		"ypos"					"6969"
		"zpos"					"4"	
		"wide"					"20"
		"tall"					"20"
		"visible"				"1"
		"enabled"				"0"
		"scaleImage"			"0"
		"image"					"../hud/objectives_timepanel_progressbar"
		"color_active"			"bh_white"
		"color_inactive"		"bh_gray"
		"color_warning"			"bh_red"
		"percent_warning"		"0.75"
	}
	"WaitingForPlayersLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"			"WaitingForPlayersLabel"
		"xpos"				"15"
		"ypos"				"18"
		"zpos"				"5"
		"wide"				"78"
		"tall"				"19"
		"visible"			"0"
		"enabled"			"1"
		"labelText"			"#game_WaitingForPlayers"
		"textAlignment"		"center"
		"dulltext"			"0"
		"brighttext"		"0"
		"wrap"				"0"
		"font"				"bh_Lato10"
		"fgcolor_override"	"bh_white"
	}			
	"WaitingForPlayersBG"
	{
		"ControlName"	"CTFImagePanel"
		"fieldName"		"WaitingForPlayersBG"
		"xpos"			"6969"
		"ypos"			"6969"
		"zpos"			"1"
		"wide"			"78"
		"tall"			"20"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../hud/objectives_timepanel_suddendeath"	
		"scaleImage"	"1"	
	}
	"OvertimeLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"			"OvertimeLabel"
		"xpos"				"15"
		"ypos"				"29"
		"zpos"				"5"
		"wide"				"78"
		"tall"				"19"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"Overtime"
		"textAlignment"		"center"
		"dulltext"			"0"
		"brighttext"		"0"
		"wrap"				"0"
		"font"				"bh_Lato10"
		"fgcolor_override"	"bh_lorange"
	}			
	"OvertimeBG"
	{
		"ControlName"		"CTFImagePanel"
		"fieldName"			"OvertimeBG"
		"xpos"				"6969"
		"ypos"				"6969"
		"zpos"				"1"
		"wide"				"78"
		"tall"				"20"
		"visible"			"0"
		"enabled"			"0"
		"image"				"../hud/objectives_timepanel_suddendeath"	
		"scaleImage"		"1"	
	}
	"SuddenDeathLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"			"SuddenDeathLabel"
		"xpos"				"15"
		"ypos"				"18"
		"zpos"				"5"
		"wide"				"78"
		"tall"				"19"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"#game_SuddenDeath"
		"textAlignment"		"center"
		"dulltext"			"0"
		"brighttext"		"0"
		"wrap"				"0"
		"font"				"bh_Lato10"
		"fgcolor_override"	"bh_white"
	}			
	"SuddenDeathBG"
	{
		"ControlName"		"CTFImagePanel"
		"fieldName"			"SuddenDeathBG"
		"xpos"				"6969"
		"ypos"				"6969"
		"zpos"				"1"
		"wide"				"78"
		"tall"				"20"
		"visible"			"0"
		"enabled"			"1"
		"image"				"../hud/objectives_timepanel_suddendeath"	
		"scaleImage"		"1"	
	}	
	"SetupLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"			"SetupLabel"
		"xpos"				"15"
		"ypos"				"18"
		"zpos"				"5"
		"wide"				"78"
		"tall"				"19"
		"visible"			"1"
		"enabled"			"1"
		"labelText"			"#game_Setup"
		"textAlignment"		"center"
		"dulltext"			"0"
		"brighttext"		"0"
		"wrap"				"0"
		"font"				"bh_Lato10"
		"fgcolor_override"	"bh_white"
	}	
	"SetupBG"
	{
		"ControlName"		"CTFImagePanel"
		"fieldName"			"SetupBG"
		"xpos"				"6969"
		"ypos"				"6969"
		"zpos"				"1"
		"wide"				"78"
		"tall"				"20"
		"tall_minmode"		"0"
		"visible"			"0"
		"enabled"			"0"
		"image"				"../hud/objectives_timepanel_suddendeath"	
		"scaleImage"		"1"	
	}
	"ServerTimeLimitLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"			"ServerTimeLimitLabel"
		"xpos"				"27"
		"ypos"				"18"
		"zpos"				"5"
		"wide"				"54"
		"tall"				"19"
		"visible"			"0"
		"enabled"			"1"
		"labelText"			"%servertimeleft%"
		"textAlignment"		"center"
		"dulltext"			"0"
		"brighttext"		"0"
		"wrap"				"0"
		"font"				"bh_Lato14"
	}	
	"ServerTimeLimitLabelBG"
	{
		"ControlName"		"CTFImagePanel"
		"fieldName"			"ServerTimeLimitLabelBG"
		"xpos"				"6969"
		"ypos"				"6969"
		"zpos"				"1"
		"wide"				"78"
		"tall"				"20"
		"visible"			"0"
		"enabled"			"1"
		"image"				"../hud/objectives_timepanel_suddendeath"	
		"scaleImage"		"1"	
	}	
}
