	#base	"..\..\#customization\_enabled\bh_biggerhealth.res"
	#base	"..\..\#customization\_enabled\bh_healthcross.res"
	#base	"..\..\_stream\resource\ui\hudplayerhealth.res"
	#base	"..\..\_budhud\resource\ui\hudplayerhealth.res"
	#base	"..\..\_tf2hud\resource\ui\hudplayerhealth.res"