"Resource/UI/MainMenuOverride.res"
{	
	MainMenuOverride
	{
		"fieldName"		"MainMenuOverride"
		"visible"		"1"
		"enabled"		"1"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"0"
		"wide"			"f0"
		"tall"			"480"
		
	//	"bgcolor_override"	"0 0 0 240"
		
		"update_url"	"http://store.steampowered.com/news/?filter=updates&appids=440"
		"blog_url"		"http://www.teamfortress.com/"
		
		"button_x_offset"	"-285"
		"button_y"			"120"
		"button_y_delta"	"5"
		"button_kv"
		{
			"xpos"			"0"
			"ypos"			"150"
			"wide"			"250"
			"tall"			"26"
			"visible"		"1"

			"SubButton"
			{
				"ControlName"	"CExImageButton"
				"fieldName"		"SubButton"
				"xpos"			"0"
				"ypos"			"0"
				"wide"			"250"
				"tall"			"26"
				"autoResize"	"0"
				"pinCorner"		"3"
				"visible"		"1"
				"enabled"		"1"
				"tabPosition"	"0"
				"textinsetx"	"25"
				"use_proportional_insets" "1"
				"font"			"HudFontSmallBold"
				"textAlignment"	"west"
				"dulltext"		"0"
				"brighttext"	"0"
				"default"		"1"
				"sound_depressed"	"UI/buttonclick.wav"
				"sound_released"	"UI/buttonclickrelease.wav"
				
				"border_default"	"MainMenuButtonDefault"
				"border_armed"		"MainMenuButtonArmed"
				"paintbackground"	"0"
				
				"defaultFgColor_override" "46 43 42 255"
				"armedFgColor_override" "bh_white"
				"depressedFgColor_override" "46 43 42 255"
				
				"image_drawcolor"	"117 107 94 255"
				"image_armedcolor"	"bh_white"
				"SubImage"
				{
					"ControlName"	"ImagePanel"
					"fieldName"		"SubImage"
					"xpos"			"6"
					"ypos"			"6"
					"zpos"			"1"
					"wide"			"14"
					"tall"			"14"
					"visible"		"1"
					"enabled"		"1"
					"scaleImage"	"1"
				}				
			}		
		}
		
		"SaxxySettings"
		{
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"-101"		
			"wide"			"f0"
			"tall"			"480"
			
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			
			"flashbounds_x"	"50"
			"flashbounds_y"	"65"
			"flashbounds_w"	"250"
			"flashbounds_h"	"120"
			
			"flashstartsize_min"	"8"
			"flashstartsize_max"	"12"
			
			"flash_maxscale"		"4"
			
			"flash_lifelength_min"	".1"
			"flash_lifelength_max"	".2"
			
			"curtain_anim_duration"		"4.0"
			"curtain_open_time"		"2.8"
			"flash_start_time"		"4.0"
			
			"initial_freakout_duration"		"15.0"
			"clap_sound_duration"	"10.0"
			
			"CameraFlashSettings"
			{
				"visible"		"1"
				"enabled"		"1"
				"tileImage"		"0"
				"scaleImage"	"1"
				"zpos"			"9"
			}
		}
	}	
	
	"mouseoveritempanel"
	{
		"ControlName"			"CItemModelPanel"
		"fieldName"				"mouseoveritempanel"
		"xpos"					"c-70"
		"ypos"					"270"
		"zpos"					"100"
		"wide"					"300"
		"tall"					"300"
		"visible"				"0"
		"bgcolor_override"		"0 0 0 0"
		"noitem_textcolor"		"117 107 94 255"
		"PaintBackgroundType"	"2"
		"paintborder"			"1"
		"border"				"MainMenuBGBorder"
		
		"text_ypos"				"20"
		"text_center"			"1"
		"model_hide"			"1"
		"resize_to_text"		"1"
		"padding_height"		"15"
		
		"attriblabel"
		{
			"font"				"ItemFontAttribLarge"
			"xpos"				"0"
			"ypos"				"30"
			"zpos"				"2"
			"wide"				"140"
			"tall"				"60"
			"autoResize"		"0"
			"pinCorner"			"0"
			"visible"			"1"
			"enabled"			"1"
			"labelText"			"%attriblist%"
			"textAlignment"		"center"
			"fgcolor"			"117 107 94 255"
			"centerwrap"		"1"
		}
	}	
	
	"Background"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"Background"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"-200"
		"wide"			"f0"
		"tall"			"480"
		"visible"		"0"
		"enabled"		"1"
		"image"			""
		"scaleImage"	"1"
		
		if_halloween_0
		{
			"image"		"../console/background_upward"
		}
		if_halloween_1
		{
			"image"		"../console/background_upward"
		}
		if_halloween_2
		{
			"image"		"../console/background_upward"
		}
		if_fullmoon
		{
			"image"		"../console/background_upward"
		}
		if_christmas
		{
			"image"		"../console/background_upward"
		}
		if_eotl_launch
		{
			"image"		"../console/background_upward"
		}
	}
					
	"TFLogoImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"TFLogoImage"
		"xpos"			"6969"
		"ypos"			"6969"
		"zpos"			"-99"
		"wide"			"256"
		"tall"			"64"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../logo/new_tf2_logo"
		"scaleImage"	"1"
	}	
	
	"TFCharacterImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"TFCharacterImage"
		"xpos"			"6969"
		"ypos"			"6969"
		"zpos"			"-99"
		"wide"			"600"
		"tall"			"600"
		"visible"		"0"
		"enabled"		"0"
		"scaleImage"	"1"
	}
	
	"MainMenuBGPanel"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"MainMenuBGPanel"
		"xpos"			"c-290"
		"ypos"			"92"
		"zpos"			"-1"
		"wide"			"260"
		"tall"			"120"
		"visible"		"0"
		"pinCorner"		"0"
		"autoResize"	"0"
		"PaintBackgroundType"	"2"
		"border"		"MainMenuBGBorder"
	}	
	"PlayLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"PlayLabel"
		"font"			"HudFontSmallBold"
		"labelText"		"#MMenu_Play"
		"textAlignment"	"west"
		"xpos"			"6969"
		"ypos"			"6969"
		"wide"			"140"
		"tall"			"30"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"fgcolor_override"	"235 227 203 255"
	}
	
	"TooltipPanel"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"TooltipPanel"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"1"
		"wide"			"150"
		"tall"			"50"
		"visible"		"0"
		"PaintBackgroundType"	"2"
		"border"		"MainMenuBGBorder"
		
		"TipSubLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"TipSubLabel"
			"font"			"HudFontSmall"
			"labelText"		"%tipsubtext%"
			"textAlignment"	"center"
			"xpos"			"20"
			"ypos"			"30"
			"zpos"			"2"
			"wide"			"250"
			"tall"			"50"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"fgcolor_override"	"117 107 94 255"
			"wrap"			"1"
		}
		
		"TipLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"TipLabel"
			"font"			"HudFontSmallBold"
			"labelText"		"%tiptext%"
			"textAlignment"	"center"
			"xpos"			"20"
			"ypos"			"5"
			"zpos"			"2"
			"wide"			"140"
			"tall"			"30"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"fgcolor_override"	"bh_white"
			"auto_wide_tocontents" "1"
		}
	}	
	
	"CreateServerButton"
	{
		"ControlName"						"EditablePanel"
		"fieldname"							"CreateServerButton"
		"xpos"								"150"
		"ypos"								"408"
		"zpos"								"12"
		"wide"								"25"
		"tall"								"25"
		"visible"							"1"

		"navUp"								"PlayPVEButton"
		"navDown"							"CharacterSetupButton"
		"navLeft"							"ServerBrowserButton"
		"navRight"							"TrainingButton"
		"navToRelay"						"SubButton"
		
		"SubButton"
		{
			"ControlName"					"CExImageButton"
			"fieldName"						"SubButton"
			"xpos"							"0"
			"ypos"							"0"
			"wide"							"20"
			"tall"							"20"
			"autoResize"					"0"
			"pinCorner"						"3"
			"visible"						"1"
			"enabled"						"1"
			"tabPosition"					"0"
			"textinsetx"					"100"
			"use_proportional_insets"		"1"
			"font"							"HudFontSmallBold"
			"textAlignment"					"west"
			"dulltext"						"0"
			"brighttext"					"0"
			"default"						"1"
			"sound_depressed"				"UI/buttonclick.wav"
			"sound_released"				"UI/buttonclickrelease.wav"
			
		//	"border_default"				"MainMenuMiniButtonDefault"
		//	"border_armed"					"MainMenuMiniButtonArmed"
			"paintbackground"				"0"
			
			"image_drawcolor"				"255 255 255 255"
			"image_armedcolor"				"240 134 49 255"
			
			"SubImage"
			{
				"ControlName"				"ImagePanel"
				"fieldName"					"SubImage"
				"xpos"						"5"
				"ypos"						"6"
				"zpos"						"1"
				"wide"						"12"
				"tall"						"12"
				"visible"					"1"
				"enabled"					"1"
				"image"						"replay\thumbnails\createserver"
				"scaleImage"				"1"
			}				
		}		
	}
	
	"TopRightContainer"
	{
			"ControlName"					"EditablePanel"
			"fieldName"						"TopRightContainer"
			"xpos"							"c95"
			"ypos"							"26"
			"zpos"							"0"
			"wide"							"212"
			"tall"							"36"
			"autoResize"					"3"
			"pinCorner"						"0"
			"visible"						"0"
			"enabled"						"1"
			"tabPosition"					"0"
			"border"						"MainMenuBGBorder"
			"PaintBackgroundType"			"2"
	}

	"Notifications_ShowButtonPanel"
	{
		"ControlName"						"EditablePanel"
		"fieldName"							"Notifications_ShowButtonPanel"
		"xpos"								"c188"
		"ypos"								"28"
		"zpos"								"10"
		"wide"								"32"
		"tall"								"32"
		"autoResize"						"0"
		"pinCorner"							"3"
		"visible"							"1"
		"enabled"							"1"

		"navUp"								"MOTD_ShowButtonPanel"
		"navDown"							"SettingsButton"
		"navLeft"							"QuickplayButton"
		"navRight"							"Notifications_Panel"
		"navToRelay"						"Notifications_ShowButtonPanel_SB"
		
		"SubImage"
		{
			"ControlName"					"ImagePanel"
			"fieldName"						"SubImage"
			"xpos"							"16"
			"ypos"							"0"
			"zpos"							"3"
			"wide"							"16"
			"tall"							"16"
			"visible"						"1"
			"enabled"						"1"
			"image"							"glyph_achievements"
			"scaleImage"					"1"
			"drawcolor" 					"210 125 33 255"
		}				
		
		"Notifications_CountLabel"
		{
			"ControlName"					"CExLabel"
			"fieldName"						"Notifications_CountLabel"
			"font"							"HudFontSmallestBold"
			"labelText"						"%noticount%"
			"textAlignment"					"center"
			"xpos"							"16"
			"ypos"							"0"
			"zpos"							"4"
			"wide"							"16"
			"tall"							"16"
			"autoResize"					"0"
			"pinCorner"						"0"
			"visible"						"1"
			"enabled"						"1"
			"fgcolor_override"				"255 255 255 255"
		}
	
		"Notifications_ShowButtonPanel_SB"
		{
			"ControlName"					"CExImageButton"
			"fieldName"						"Notifications_ShowButtonPanel_SB"
			"xpos"							"0"
			"ypos"							"0"
			"zpos"							"1"
			"wide"							"32"
			"tall"							"32"
			"autoResize"					"0"
			"pinCorner"						"3"
			"visible"						"1"
			"enabled"						"1"
			"tabPosition"					"0"
			"labelText"						""
			"font"							"HudFontSmallestBold"
			"textAlignment"					"center"
			"dulltext"						"0"
			"brighttext"					"0"
			"default"						"1"

			"Command"						"noti_show"
			"navActivate"					"<QuickplayButton"

			"sound_depressed"				"UI/buttonclick.wav"
			"sound_released"				"UI/buttonclickrelease.wav"
			"paintbackground" 				"0"
			"image_drawcolor"				"235 226 202 255"
			"image_armedcolor"				"255 255 255 255"
			
			"SubImage"
			{
				"ControlName"				"ImagePanel"
				"fieldName"					"SubImage"
				"xpos"						"0"
				"ypos"						"0"
				"zpos"						"1"
				"wide"						"32"
				"tall"						"32"
				"visible"					"1"
				"enabled"					"1"
				"image"						"button_Alert"
				"scaleImage"				"1"
			}
		}
	}

	"QuestLogButton"
	{
		"ControlName"						"EditablePanel"
		"fieldName"							"QuestLogButton"
		"xpos"								"c228"
		"ypos"								"28"
		"zpos"								"1"
		"wide"								"32"
		"tall"								"32"
		"autoResize"						"0"
		"pinCorner"							"3"
		"visible"							"1"
		"enabled"							"1"
		"tabPosition"						"0"
		
		"navUp"								"Notifications_Panel"
		"navLeft"							"SettingsButton"

		"SubButton"
		{
			"ControlName"					"CExImageButton"
			"fieldName"						"SubButton"
			"xpos"							"0"
			"ypos"							"0"
			"wide"							"f0"
			"tall"							"f0"
			"autoResize"					"0"
			"pinCorner"						"3"
			"visible"						"1"
			"enabled"						"1"
			"tabPosition"					"0"
			"textinsetx"					"25"
			"labelText"						""
			"use_proportional_insets" 		"1"
			"font"							"HudFontSmallBold"
			"command"						"questlog"
			"textAlignment"					"west"
			"dulltext"						"0"
			"brighttext"					"0"
			"default"						"1"
			"sound_depressed"				"UI/buttonclick.wav"
			"sound_released"				"UI/buttonclickrelease.wav"
			"actionsignallevel" 			"2"
			"proportionaltoparent"			"1"
				
			"sound_depressed"				"UI/buttonclick.wav"
			"sound_released"				"UI/buttonclickrelease.wav"
			"paintbackground"				"0"
			"paintborder"					"0"
			"image_drawcolor"				"235 226 202 255"
			"image_armedcolor"				"255 255 255 255"

			"SubImage"
			{
				"ControlName"				"ImagePanel"
				"fieldName"					"SubImage"
				"xpos"						"cs-0.5"
				"ypos"						"cs-0.5"
				"zpos"						"1"
				"wide"						"f0"
				"tall"						"f0"
				"visible"					"1"
				"enabled"					"1"
				"scaleImage"				"1"
				"image"						"replay\thumbnails\contracts"

				"proportionaltoparent"		"1"
				"mouseinputenabled"			"0"
				"keyboardinputenabled" 		"0"
			}		
		}
		
		"NotificationsContainer"
		{
			"ControlName"					"EditablePanel"
			"fieldName"						"NotificationsContainer"
			"xpos"							"rs1"
			"ypos"							"0"
			"zpos"							"10"
			"wide"							"16"
			"tall"							"16"
			"visible"						"0"
			"proportionaltoparent"			"1"
			"mouseinputenabled"				"0"
			"keyboardinputenabled" 			"0"

			"SubImage"
			{
				"ControlName"				"ImagePanel"
				"fieldName"					"SubImage"
				"xpos"						"cs-0.5"
				"ypos"						"cs-0.5"
				"zpos"						"3"
				"wide"						"16"
				"tall"						"16"
				"visible"					"1"
				"enabled"					"1"
				"image"						"glyph_achievements"
				"scaleImage"				"1"
				"drawcolor"					"210 125 33 255"
				"proportionaltoparent"		"1"
			}				
		
			"Notifications_CountLabel"
			{
				"ControlName"				"CExLabel"
				"fieldName"					"Notifications_CountLabel"
				"font"						"HudFontSmallestBold"
				"labelText"					"%noticount%"
				"textAlignment"				"center"
				"xpos"						"cs-0.5"
				"ypos"						"cs-0.5"
				"zpos"						"4"
				"wide"						"16"
				"tall"						"16"
				"autoResize"				"0"
				"pinCorner"					"0"
				"visible"					"1"
				"enabled"					"1"
				"fgcolor_override"			"255 255 255 255"
				"proportionaltoparent"		"1"
			}
		}
	}	
	
	"MOTD_ShowButtonPanel"
	{
		"ControlName"						"EditablePanel"
		"fieldName"							"MOTD_ShowButtonPanel"
		"xpos"								"c200"
		"ypos"								"35"
		"zpos"								"1"
		"wide"								"20"
		"tall"								"20"
		"autoResize"						"0"
		"pinCorner"							"3"
		"visible"							"1"
		"enabled"							"1"
		
		"MOTD_ShowButtonPanel_SB"
		{
			"ControlName"					"CExImageButton"
			"fieldName"						"MOTD_ShowButtonPanel_SB"
			"xpos"							"0"
			"ypos"							"0"
			"zpos"							"1"
			"wide"							"32"
			"tall"							"32"
			"autoResize"					"0"
			"pinCorner"						"3"
			"visible"						"1"
			"enabled"						"1"
			"tabPosition"					"0"
			"labelText"						""
			"font"							"HudFontSmallestBold"
			"textAlignment"					"center"
			"dulltext"						"0"
			"brighttext"					"0"
			"default"						"1"
			"Command"						"motd_show"
			"sound_depressed"				"UI/buttonclick.wav"
			"sound_released"				"UI/buttonclickrelease.wav"
			"paintbackground"				"0"
			
			"image_drawcolor"				"235 226 202 255"
			"image_armedcolor"				"255 255 255 255"

			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"1"
				"wide"			"20"
				"tall"			"20"
				"visible"		"1"
				"enabled"		"1"
				"image"			"replay\thumbnails\news"
				"scaleImage"	"1"
			}
		}
	}
	
	"MOTD_Panel"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"MOTD_Panel"
		"xpos"			"c0"
		"ypos"			"63"
		"zpos"			"1"
		"wide"			"300"
		"tall"			"360"
		"visible"		"0"
		"PaintBackgroundType"	"2"
		"paintbackground"		"1"
		"border"				"NoBorder"
		"bgcolor_override"		"25 25 25 200"
		
		"MOTD_HeaderContainer"
		{
			"ControlName"	"EditablePanel"
			"fieldName"		"MOTD_HeaderContainer"
			"xpos"			"0"
			"ypos"			"0"
			"wide"			"300"
			"tall"			"22"
			"visible"		"1"
			
			"MOTD_HeaderLabel"
			{
				"ControlName"	"CExLabel"
				"fieldName"		"MOTD_HeaderLabel"
				"font"			"LatoSemibold24"
				"textAlignment"	"center"
				"labelText"		"%motdheader%"
				"xpos"			"0"
				"ypos"			"0"
				"wide"			"300"
				"tall"			"24"
				"autoResize"	"0"
				"pinCorner"		"0"
				"visible"		"1"
				"enabled"		"1"
				"fgcolor_override"	"bh_white"
			}
		}
		
		"MOTD_CloseButton"
		{
			"ControlName"	"CExImageButton"
			"fieldName"		"MOTD_CloseButton"
			"xpos"			"282"
			"ypos"			"4"
			"zpos"			"10"
			"wide"			"14"
			"tall"			"14"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labeltext"		"X"
			"font"			"LatoSemibold16"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"default"		"0"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"Command"		"motd_hide"
			
			"paintbackground"	"0"
			
			//"defaultFgColor_override" "bh_white"
			//"armedFgColor_override" "46 43 42 255"
			"defaultFgColor_override" "bh_white"
			"armedFgColor_override" "bh_white"
			"depressedFgColor_override" "bh_white"
			
			"image_drawcolor"	"bh_white"
			"image_armedcolor"	"200 80 60 255"		
		}	

		"MOTD_HeaderIcon"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"MOTD_HeaderIcon"
			"xpos"			"6969"
			"ypos"			"6969"
			"zpos"			"100"
			"wide"			"25"
			"tall"			"25"
			"visible"		"0"
			"enabled"		"1"
			"image"			"class_icons/filter_all_motd"
			"scaleImage"	"1"
		}
			
		"MOTD_TitleLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"MOTD_TitleLabel"
			"font"			"HudFontSmallBold"
			"labelText"		"%motdtitle%"
			"textAlignment"	"west"
			"xpos"			"10"
			"ypos"			"25"
			"wide"			"250"
			"tall"			"15"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"fgcolor_override"	"bh_white"
			"wrap"			"1"
		}
		
		"MOTD_Label"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"MOTD_Label"
			"font"			"HudFontSmall"
			"labelText"		"%motddate%"
			"textAlignment"	"north-west"
			"xpos"			"10"
			"ypos"			"40"
			"wide"			"300"
			"tall"			"15"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"fgcolor_override"	"bh_white"
		}
		
		"MOTD_TitleImageBg"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"MOTD_TitleImageBg"
			"xpos"			"10"
			"ypos"			"55"
			"zpos"			"99"
			"wide"			"280"
			"tall"			"180"
			"visible"		"1"
			"enabled"		"1"
			"image"			"item_bg"
			"scaleImage"	"1"
		}
		
		"MOTD_TitleImageContainer"
		{
			"ControlName"	"EditablePanel"
			"fieldName"		"MOTD_TitleImageContainer"
			"xpos"			"10"
			"ypos"			"55"
			"zpos"			"100"
			"wide"			"280"
			"tall"			"180"
			"visible"		"1"
			"border" 		"NoBorder"
			
			"MOTD_TitleImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"MOTD_TitleImage"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"100"
				"wide"			"280"
				"tall"			"280"
				"visible"		"1"
				"enabled"		"1"
				"image"			"class_icons/filter_all"
				"scaleImage"	"0"
			}
		}
			
		"MOTD_TextScroller"
		{
			"ControlName"	"ScrollableEditablePanel"
			"fieldName"		"MOTD_TextScroller"
			"xpos"			"20"
			"ypos"			"240"
			"wide"			"280"
			"tall"			"95"
			"PaintBackgroundType"	"2"
			"fgcolor_override"	"bh_white"
			
			"MOTD_TextPanel"
			{
				"ControlName"	"EditablePanel"
				"fieldName"		"MOTD_TextPanel"
				"xpos"			"0"
				"ypos"			"0"
				"wide"			"250"
				"tall"			"300"
				"visible"		"1"
				"PaintBackgroundType"	"2"
			
				"MOTD_TextLabel"
				{
					"ControlName"	"CExLabel"
					"fieldName"		"MOTD_TextLabel"
					"font"			"HudFontSmall"
					"labelText"		"%motdtext%"
					"textAlignment"	"north-west"
					"xpos"			"0"
					"ypos"			"0"
					"wide"			"250"
					"tall"			"300"
					"autoResize"	"0"
					"pinCorner"		"0"
					"visible"		"1"
					"enabled"		"1"
					"fgcolor_override"	"bh_white"
					"wrap"			"1"
				}
			}
		}
		
		"MOTD_URLButton"
		{
			"ControlName"	"CExButton"
			"fieldName"		"MOTD_URLButton"
			"xpos"			"75"
			"ypos"			"339"
			"wide"			"150"
			"tall"			"15"
			"autoResize"	"0"
			"pinCorner"		"3"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labelText"		"#MMenu_MOTD_URL"
			"textinsetx"	"20"
			"use_proportional_insets" "1"
			"font"			"HudFontSmallestBold"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"default"		"1"
			"command"		"motd_viewurl"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		
		"defaultBgColor_override"	"25 25 25 255"
		"armedBgColor_override"		"35 35 35 255"
		"depressedBgColor_override"	"25 25 25 255"
		
		"defaultFgColor_override"	"bh_white"
		"armedFgColor_override" 	"bh_white"
		"depressedFgColor_override" "TanDark"
		
		"border_default"			"NoBorder"
		"border_armed"				"NoBorder"
		}	
		
		"MOTD_PrevButton"
		{
			"ControlName"	"CExImageButton"
			"fieldName"		"MOTD_PrevButton"
			"xpos"			"12"
			"ypos"			"336"
			"zpos"			"1"
			"wide"			"20"
			"tall"			"20"
			"autoResize"	"0"
			"pinCorner"		"3"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labelText"		""
			"font"			"HudFontSmallBold"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"default"		"1"
			"Command"		"motd_prev"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"paintbackground" "0"
			
			"image_drawcolor"				"255 255 255 255"
			"image_armedcolor"				"150 150 150 255"
			
			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"1"
				"wide"			"20"
				"tall"			"20"
				"visible"		"1"
				"enabled"		"1"
				"image"			"blog_back"
				"scaleImage"	"1"
			}
		}		
		
		"MOTD_NextButton"
		{
			"ControlName"		"CExImageButton"
			"fieldName"			"MOTD_NextButton"
			"xpos"				"267"
			"ypos"				"336"
			"zpos"				"1"
			"wide"				"20"
			"tall"				"20"
			"autoResize"		"0"
			"pinCorner"			"3"
			"visible"			"1"
			"enabled"			"1"
			"tabPosition"		"0"
			"labelText"			""
			"font"				"HudFontSmallBold"
			"textAlignment"		"center"
			"dulltext"			"0"
			"brighttext"		"0"
			"default"			"1"
			"Command"			"motd_next"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"paintbackground" 	"0"
			
			"image_drawcolor"	"bh_white"
			"image_armedcolor"	"255 255 255 255"
			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"1"
				"wide"			"20"
				"tall"			"20"
				"visible"		"1"
				"enabled"		"1"
				"image"			"blog_forward"
				"scaleImage"	"1"
			}
		}
	}	
	
	"Notifications_ShowButtonPanel"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"Notifications_ShowButtonPanel"
		"xpos"			"c172"
		"ypos"			"35"
		"zpos"			"1"
		"wide"			"36"
		"tall"			"36"
		"autoResize"	"0"
		"pinCorner"		"3"
		"visible"		"1"
		"enabled"		"1"
		
		"SubImage"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"SubImage"
			"xpos"			"6969"
			"ypos"			"6969"
			"zpos"			"3"
			"wide"			"12"
			"tall"			"12"
			"visible"		"1"
			"enabled"		"1"
			"image"			"glyph_achievements"
			"scaleImage"	"1"
			"drawcolor" 	"255 255 255 255"
		}				
		
		"Notifications_CountLabel"
		{
			"ControlName"					"CExLabel"
			"fieldName"						"Notifications_CountLabel"
			"font"							"LatoSemibold14"
			"labelText"						"%noticount%"
			"textAlignment"					"center"
			"xpos"							"6969"
			"ypos"							"6969"
			"zpos"							"4"
			"wide"							"16"
			"tall"							"16"
			"autoResize"					"0"
			"pinCorner"						"0"
			"visible"						"1"
			"enabled"						"1"
			"fgcolor_override"				"bh_white"
		}
	
		"Notifications_ShowButtonPanel_SB"
		{
			"ControlName"					"CExImageButton"
			"fieldName"						"Notifications_ShowButtonPanel_SB"
			"xpos"							"0"
			"ypos"							"0"
			"zpos"							"1"
			"wide"							"20"
			"tall"							"20"
			"autoResize"					"0"
			"pinCorner"						"3"
			"visible"						"1"
			"enabled"						"1"
			"tabPosition"					"0"
			"labelText"						""
			"font"							"LatoSemibold16eticaBold12"
			"textAlignment"					"center"
			"dulltext"						"0"
			"brighttext"					"0"
			"default"						"1"
			"Command"						"noti_show"
			"sound_depressed"				"UI/buttonclick.wav"
			"sound_released"				"UI/buttonclickrelease.wav"
			"paintbackground"				"0"
			
			"image_drawcolor"				"255 255 255 255"
			"image_armedcolor"				"150 150 150 255"
			
			"SubImage"
			{
				"ControlName"				"ImagePanel"
				"fieldName"					"SubImage"
				"xpos"						"0"
				"ypos"						"0"
				"zpos"						"1"
				"wide"						"20"
				"tall"						"20"
				"visible"					"1"
				"enabled"					"1"
				"image"						"replay\thumbnails\newnotification"
				"scaleImage"				"1"
			}
		}
	}
	
	"Notifications_Panel"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"Notifications_Panel"
		"xpos"			"c0"
		"ypos"			"102"
		"zpos"			"1"
		"wide"			"210"
		"tall"			"80"
		"visible"		"0"
		"PaintBackgroundType"	"2"
		"paintbackground"	"0"
		"border"		"MainMenuHighlightBorder"
		
		"Notifications_CloseButton"
		{
			"ControlName"	"CExImageButton"
			"fieldName"		"Notifications_CloseButton"
			"xpos"			"186"
			"ypos"			"8"
			"zpos"			"10"
			"wide"			"14"
			"tall"			"14"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labeltext"		""
			"font"			"HudFontSmallBold"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"default"		"0"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"Command"		"noti_hide"
			
			"paintbackground"	"0"
			
			"defaultFgColor_override" "bh_white"
			"armedFgColor_override" "Button Color"
			"depressedFgColor_override" "Button Color"
			
			"image_drawcolor"				"255 255 255 255"
			"image_armedcolor"				"150 150 150 255"
			
			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"1"
				"wide"			"14"
				"tall"			"14"
				"visible"		"1"
				"enabled"		"1"
				"image"			"close_button"
				"scaleImage"	"1"
			}				
		}		
	
		"Notifications_TitleLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"Notifications_TitleLabel"
			"font"			"HudFontSmallBold"
			"labelText"		"%notititle%"
			"textAlignment"	"north-west"
			"xpos"			"12"
			"ypos"			"8"
			"wide"			"250"
			"tall"			"20"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"fgcolor_override"	"46 43 42 255"
			"wrap"			"1"
		}
		
		"Notifications_Scroller"
		{
			"ControlName"	"ScrollableEditablePanel"
			"fieldName"		"Notifications_Scroller"
			"xpos"			"8"
			"ypos"			"25"
			"wide"			"210"
			"tall"			"135"
			"PaintBackgroundType"	"2"
			"fgcolor_override"	"117 107 94 255"
			
			"Notifications_Control"
			{
				"ControlName"	"CMainMenuNotificationsControl"
				"fieldName"		"Notifications_Control"
				"xpos"			"0"
				"ypos"			"0"
				"wide"			"220"
				"tall"			"135"
				"visible"		"1"
			}
		}
	}	
	
	"TrainingButton"
	{
		"ControlName"						"EditablePanel"
		"fieldname"							"TrainingButton"
		"xpos"								"169"
		"ypos"								"408"
		"zpos"								"12"
		"wide"								"25"
		"tall"								"25"
		"tall"								"40"
		"visible"							"0"
		"PaintBackgroundType"				"0"

		"navUp"								"PlayPVEButton"
		"navDown"							"GeneralStoreButton"
		"navLeft"							"CreateServerButton"
		"navRight"							"Notifications_ShowButtonPanel"
		"navToRelay"						"SubButton"

		"SubButton"
		{
			"ControlName"					"CExImageButton"
			"fieldName"						"SubButton"
			"xpos"							"0"
			"ypos"							"0"
			"wide"							"20"
			"tall"							"20"
			"autoResize"					"0"
			"pinCorner"						"3"
			"visible"						"1"
			"enabled"						"1"
			"tabPosition"					"0"
			"textinsetx"					"100"
			"use_proportional_insets" 		"1"
			"font"							"LatoSemibold24"
			"textAlignment"					"west"
			"dulltext"						"0"
			"brighttext"					"0"
			"default"						"1"
			"sound_depressed"				"UI/buttonclick.wav"
			"sound_released"				"UI/buttonclickrelease.wav"
			
			"paintbackground"				"0"
			
			"image_drawcolor"				"255 255 255 255"
			"image_armedcolor"				"240 134 49 255"
			
			"SubImage"
			{
				"ControlName"				"ImagePanel"
				"fieldName"					"SubImage"
				"xpos"						"5"
				"ypos"						"6"
				"zpos"						"1"
				"wide"						"12"
				"tall"						"12"
				"visible"					"1"
				"enabled"					"1"
				"image"						"replay\thumbnails\train"
				"scaleImage"				"1"
			}
		}
	}

	"SteamWorkshopButton"
	{
		"ControlName"						"EditablePanel"
		"fieldname"							"SteamWorkshopButton"
		"xpos"								"6969"
		"ypos"								"6969"
		"zpos"								"11"
		"wide"								"350"
		"tall"								"40"
		"visible"							"0"
		"PaintBackgroundType"				"2"

		"navUp"								"GeneralStoreButton"
		"navDown"							"VRModeButton"
		"navLeft"							"ReplayBrowserButton"
		"navRight"							"Notifications_ShowButtonPanel"
		"navToRelay"						"SubButton"

		"SubButton"
		{
			"ControlName"					"CExImageButton"
			"fieldName"						"SubButton"
			"xpos"							"0"
			"ypos"							"0"
			"wide"							"300"
			"tall"							"40"
			"autoResize"					"0"
			"pinCorner"						"3"
			"visible"						"1"
			"enabled"						"1"
			"tabPosition"					"0"
			"textinsetx"					"25"
			"use_proportional_insets" 		"1"
			"font"							"LatoSemibold24"
			"textAlignment"					"west"
			"dulltext"						"0"
			"brighttext"					"0"
			"default"						"1"
			"sound_depressed"				"UI/buttonclick.wav"
			"sound_released"				"UI/buttonclickrelease.wav"
			
		//	"border_default"				"MainMenuButtonDefault"
		//	"border_armed"					"MainMenuButtonArmed"
			"paintbackground"				"0"
			
			"defaultFgColor_override"	 	"bh_white"
			"armedFgColor_override" 		"bh_orange"
			"depressedFgColor_override" 	"bh_white"
			
		//	"image_drawcolor"				"117 107 94 255"
		//	"image_armedcolor"				"bh_white"
			"SubImage"
			{
				"ControlName"				"ImagePanel"
				"fieldName"					"SubImage"
				"xpos"						"6969"
				"ypos"						"6969"
				"zpos"						"1"
				"wide"						"14"
				"tall"						"14"
				"visible"					"0"
				"enabled"					"0"
				"scaleImage"				"1"
			}		
		}
	}

	"VRModeButton"
	{
		"ControlName"	"EditablePanel"
		"fieldname"		"VRModeButton"
		"xpos"			"c-285"
		"ypos"			"379"
		"zpos"			"11"
		"wide"			"270"
		"tall"			"36"
		"visible"		"1"
		"PaintBackgroundType"	"2"

		"navUp"			"ReplayBrowserButton"
		"navDown"		"QuitButton"
		"navRight"		"Notifications_ShowButtonPanel"
		"navToRelay"	"SubButton"

		"SubButton"
		{
			"ControlName"	"CExImageButton"
			"fieldName"		"SubButton"
			"xpos"			"0"
			"ypos"			"0"
			"wide"			"250"
			"tall"			"26"
			"autoResize"	"0"
			"pinCorner"		"3"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"textinsetx"	"25"
			"use_proportional_insets" "1"
			"font"			"HudFontSmallBold"
			"textAlignment"	"west"
			"dulltext"		"0"
			"brighttext"	"0"
			"default"		"1"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			
			"border_default"	"MainMenuButtonDefault"
			"border_armed"		"MainMenuButtonArmed"
			"paintbackground"	"0"
			
			"defaultFgColor_override" "46 43 42 255"
			"armedFgColor_override" "bh_white"
			"depressedFgColor_override" "46 43 42 255"
			
			"image_drawcolor"	"117 107 94 255"
			"image_armedcolor"	"bh_white"
			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"6"
				"ypos"			"6"
				"zpos"			"1"
				"wide"			"14"
				"tall"			"14"
				"visible"		"1"
				"enabled"		"1"
				"scaleImage"	"1"
			}		
		}
	}


	"ReplayBrowserButton"
	{
		"ControlName"						"EditablePanel"
		"fieldname"							"ReplayBrowserButton"
		"xpos"								"50"
		"ypos"								"240"
		"zpos"								"11"
		"wide"								"350"
		"tall"								"40"
		"visible"							"0"
		"PaintBackgroundType"				"0"

		"navUp"								"CharacterSetupButton"
		"navDown"							"VRModeButton"
		"navRight"							"SteamWorkshopButton"
		"navToRelay"						"SubButton"

		"SubButton"
		{
			"ControlName"					"CExImageButton"
			"fieldName"						"SubButton"
			"xpos"							"0"
			"ypos"							"0"
			"wide"							"300"
			"tall"							"40"
			"autoResize"					"0"
			"pinCorner"						"3"
			"visible"						"1"
			"enabled"						"1"
			"tabPosition"					"0"
			"textinsetx"					"25"
			"use_proportional_insets"		"1"
			"font"							"LatoSemibold36"
			"textAlignment"					"west"
			"dulltext"						"0"
			"brighttext"					"0"
			"default"						"1"
			"sound_depressed"				"UI/buttonclick.wav"
			"sound_released"				"UI/buttonclickrelease.wav"
			
		//	"border_default"				"MainMenuButtonDefault"
		//	"border_armed"					"MainMenuButtonArmed"
			"paintbackground"				"0"
			
			"defaultFgColor_override"	 	"bh_white"
			"armedFgColor_override" 		"bh_orange"
			"depressedFgColor_override" 	"bh_white"
			
		//	"image_drawcolor"				"117 107 94 255"
		//	"image_armedcolor"				"bh_white"
			"SubImage"
			{
				"ControlName"				"ImagePanel"
				"fieldName"					"SubImage"
				"xpos"						"6969"
				"ypos"						"6969"
				"zpos"						"1"
				"wide"						"14"
				"tall"						"14"
				"visible"					"0"
				"enabled"					"0"
				"scaleImage"				"1"
			}		
		}
	}

	"GeneralStoreButton"
	{
		"ControlName"						"EditablePanel"
		"fieldname"							"GeneralStoreButton"
		"xpos"								"50"
		"ypos"								"200"
		"zpos"								"11"
		"wide"								"350"
		"tall"								"40"
		"visible"							"0"
		"PaintBackgroundType"				"0"

		"navUp"								"ChangeServerButton"
		"navDown"							"SteamWorkshopButton"
		"navLeft"							"CharacterSetupButton"
		"navRight"							"Notifications_ShowButtonPanel"
		"navToRelay"						"SubButton"

		"SubButton"
		{
			"ControlName"					"CExImageButton"
			"fieldName"						"SubButton"
			"xpos"							"0"
			"ypos"							"0"
			"wide"							"300"
			"tall"							"40"
			"autoResize"					"0"
			"pinCorner"						"3"
			"visible"						"1"
			"enabled"						"1"
			"tabPosition"					"0"
			"textinsetx"					"25"
			"use_proportional_insets" 		"1"
			"font"							"LatoSemibold36"
			"textAlignment"					"west"
			"dulltext"						"0"
			"brighttext"					"0"
			"default"						"1"
			"sound_depressed"				"UI/buttonclick.wav"
			"sound_released"				"UI/buttonclickrelease.wav"
			
		//	"border_default"				"MainMenuButtonDefault"
		//	"border_armed"					"MainMenuButtonArmed"
			"paintbackground"				"0"
			
			"defaultFgColor_override"	 	"bh_white"
			"armedFgColor_override" 		"bh_orange"
			"depressedFgColor_override" 	"bh_white"
			
		//	"image_drawcolor"				"117 107 94 255"
		//	"image_armedcolor"				"bh_white"
			"SubImage"
			{
				"ControlName"				"ImagePanel"
				"fieldName"					"SubImage"
				"xpos"						"6969"
				"ypos"						"6969"
				"zpos"						"1"
				"wide"						"14"
				"tall"						"14"
				"visible"					"0"
				"enabled"					"0"
				"scaleImage"				"1"
			}		
		}
	}
	"StoreHasNewItemsImage"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"StoreHasNewItemsImage"
		"xpos"			"6969"
		"ypos"			"6969"
		"zpos"			"13"
		"wide"			"32"
		"tall"			"32"
		"visible"		"0"
		"enabled"		"0"
		"image"			"../vgui/new"
		"scaleImage"	"1"
	}
	
	"CharacterSetupButton"
	{
		"ControlName"						"EditablePanel"
		"fieldname"							"CharacterSetupButton"
		"xpos"								"50"
		"ypos"								"160"
		"zpos"								"11"
		"wide"								"350"
		"tall"								"40"
		"visible"							"0"
		"PaintBackgroundType"				"0"

		"navUp"								"ChangeServerButton"
		"navDown"							"ReplayBrowserButton"
		"navRight"							"GeneralStoreButton"
		"navToRelay"						"SubButton"

		"SubButton"
		{
			"ControlName"					"CExImageButton"
			"fieldName"						"SubButton"
			"xpos"							"0"
			"ypos"							"0"
			"wide"							"300"
			"tall"							"40"
			"autoResize"					"0"
			"pinCorner"						"3"
			"visible"						"1"
			"enabled"						"1"
			"tabPosition"					"0"
			"textinsetx"					"25"
			"use_proportional_insets" 		"1"
			"font"							"LatoSemibold36"
			"textAlignment"					"west"
			"dulltext"						"0"
			"brighttext"					"0"
			"default"						"1"
			"sound_depressed"				"UI/buttonclick.wav"
			"sound_released"				"UI/buttonclickrelease.wav"
			
		//	"border_default"				"MainMenuButtonDefault"
		//	"border_armed"					"MainMenuButtonArmed"
			"paintbackground"				"0"
			
			"defaultFgColor_override"	 	"bh_white"
			"armedFgColor_override" 		"bh_orange"
			"depressedFgColor_override" 	"bh_white"
			
		//	"image_drawcolor"				"117 107 94 255"
		//	"image_armedcolor"				"bh_white"
			"SubImage"
			{
				"ControlName"				"ImagePanel"
				"fieldName"					"SubImage"
				"xpos"						"6969"
				"ypos"						"6969"
				"zpos"						"1"
				"wide"						"14"
				"tall"						"14"
				"visible"					"0"
				"enabled"					"0"
				"scaleImage"				"1"
			}		
		}
	}

	"StoreBGPanel"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"StoreBGPanel"
		"xpos"			"c-290"
		"ypos"			"225"
		"zpos"			"-1"
		"wide"			"260"
		"tall"			"60"
		"visible"		"0"
		"PaintBackgroundType"	"2"
		"border"		"MainMenuBGBorder"
	}
	"CustomizeLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"CustomizeLabel"
		"font"			"HudFontSmallBold"
		"labelText"		"#MMenu_Customize"
		"textAlignment"	"west"
		"xpos"			"6969"
		"ypos"			"6969"
		"wide"			"140"
		"tall"			"30"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"fgcolor_override"	"235 227 203 255"
	}

	"CreateBGPanel"
	{
		"ControlName"			"EditablePanel"
		"fieldName"				"CreateBGPanel"
		"xpos"					"6969"
		"ypos"					"6969"
		"zpos"					"-1"
		"wide"					"260"
		"tall"					"60"
		"visible"				"0"
		"PaintBackgroundType"	"2"
		"border"				"MainMenuBGBorder"
	}
	"CreateLabel"
	{
		"ControlName"			"CExLabel"
		"fieldName"				"CreateLabel"
		"font"					"HudFontSmallBold"
		"labelText"				"#MMenu_Create"
		"textAlignment"			"west"
		"xpos"					"6969"
		"ypos"					"6969"
		"wide"					"140"
		"tall"					"30"
		"autoResize"			"0"
		"pinCorner"				"0"
		"visible"				"0"
		"enabled"				"0"
		"fgcolor_override"		"235 227 203 255"
	}
	
	"VRBGPanel"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"VRBGPanel"
		"xpos"			"c-290"
		"ypos"			"373"
		"zpos"			"-1"
		"wide"			"260"
		"tall"			"38"
		"visible"		"1"
		"PaintBackgroundType"	"2"
		"border"		"MainMenuBGBorder"
	}

	"ShowPromoCodesButton"
	{
		"ControlName"		"CExImageButton"
		"fieldName"			"ShowPromoCodesButton"
		"xpos"				"6969"
		"ypos"				"6969"
		"wide"				"250"
		"tall"				"20"
		"autoResize"		"0"
		"pinCorner"			"3"
		"visible"			"0"
		"enabled"			"0"
		"tabPosition"		"0"
		"font"				"HudFontSmallestBold"
		"labelText"			"#MMenu_ShowPromoCodes"
		"textAlignment"		"center"
		"dulltext"			"0"
		"brighttext"		"0"
		"default"			"1"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"command"			"showpromocodes"
		
		"border_default"	"MainMenuButtonDefault"
		"border_armed"		"MainMenuButtonArmed"
		"paintbackground"	"0"
		
		"defaultFgColor_override" "46 43 42 255"
		"armedFgColor_override" "bh_white"
		"depressedFgColor_override" "46 43 42 255"
	}
	"FreeTrialPanel"
	{
		"ControlName"	"EditablePanel"
		"fieldName"		"FreeTrialPanel"
		"xpos"			"c-300"
		"ypos"			"310"
		"zpos"			"0"
		"wide"			"250"
		"tall"			"130"
		"visible"		"0"

		"Image"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"Image"
			"xpos"			"0"
			"ypos"			"0"
			"zpos"			"0"
			"wide"			"80"
			"tall"			"80"
			"visible"		"1"
			"enabled"		"1"
			"image"			"tf_box"
			"scaleImage"	"1"
		}

		"UpgradeLabel1"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"UpgradeLabel"
			"font"			"HudFontSmallestBold"
			"labelText"		"#TF_Trial_MainMenu_Upgrade1"
			"textAlignment"	"north"
			"xpos"			"80"
			"ypos"			"5"
			"wide"			"165"
			"tall"			"80"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"wrap"			"1"
		}
		"UpgradeLabel2"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"UpgradeLabel2"
			"font"			"HudFontSmallBold"
			"labelText"		"#TF_Trial_MainMenu_Upgrade2"
			"textAlignment"	"north"
			"xpos"			"80"
			"ypos"			"18"
			"wide"			"165"
			"tall"			"80"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"wrap"			"1"
			"fgcolor"		"255 155 138 255"
		}
		"UpgradeLabel3"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"UpgradeLabel3"
			"font"			"HudFontSmallestBold"
			"labelText"		"#TF_Trial_MainMenu_Upgrade3"
			"textAlignment"	"north"
			"xpos"			"80"
			"ypos"			"48"
			"wide"			"165"
			"tall"			"80"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"wrap"			"1"
			"fgcolor"		"137 134 127 255"
		}
	}

///////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////
	
	"budhud"
	{
		"ControlName"			"EditablePanel"
		"fieldname"				"budhud"
		"xpos"					"r100"
		"ypos"					"422"
		"zpos"					"11"
		"wide"					"100"
		"tall"					"100"
		"visible"				"1"
		"PaintBackgroundType"	"0"
		
		"SubButton"
		{
			"ControlName"					"CExImageButton"
			"fieldName"						"SubButton"
			"xpos"							"0"
			"ypos"							"0"
			"wide"							"100"
			"tall"							"100"
			"autoResize"					"0"
			"pinCorner"						"3"
			"visible"						"1"
			"enabled"						"1"
			"tabPosition"					"0"
			"font"							"LatoSemibold16"
			"textAlignment"					"east"
			"labelText"						"budhud"
			"dulltext"						"0"
			"brighttext"					"0"
			"default"						"1"
	
			"sound_depressed"				"ui\quack.wav"
			"sound_released"				""
	
			"border_default"				""
			"border_armed"					""
			"paintbackground"				"0"

			"defaultFgColor_override" 		"bh_white"
			"armedFgColor_override" 		"bh_orange"
			"depressedFgColor_override" 	"bh_orange"
			
			"image_drawcolor"				"255 255 255 255"
			"image_armedcolor"				"150 150 150 255"

			"SubImage"
			{
				"ControlName"				"ImagePanel"
				"fieldName"					"SubImage"
				"xpos"						"6"
				"ypos"						"6"
				"zpos"						"1"
				"wide"						"14"
				"tall"						"14"
				"visible"					"1"
				"enabled"					"1"
				"scaleImage"				"1"
			}
		}
	}
	
///////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////

	"ToggleScoreboard"
	{
		"ControlName"					"EditablePanel"
		"fieldname"						"ToggleScoreboard"
		"xpos"							"0"
		"ypos"							"422"
		"zpos"							"11"
		"wide"							"70"
		"tall"							"80"
		"visible"						"1"
		"PaintBackgroundType"			"0"
		
		"SubButton"
		{
			"ControlName"				"CExImageButton"
			"fieldName"					"SubButton"
			"xpos"						"0"
			"ypos"						"11"
			"wide"						"80"
			"tall"						"80"
			"autoResize"				"0"
			"pinCorner"					"3"
			"visible"					"1"
			"enabled"					"1"
			"tabPosition"				"0"
			"font"						"LatoSemibold12"
			"textAlignment"				"west"
			"labelText"					"Scoreboard"
			"dulltext"					"0"
			"brighttext"				"0"
			"default"					"1"

			"sound_depressed"			"UI/buttonclick.wav"
			"sound_released"			"UI/buttonclickrelease.wav"

			"border_default"			""
			"border_armed"				""
			"paintbackground"			"0"
			
			"defaultFgColor_override" 	"bh_white"
			"armedFgColor_override" 	"bh_orange"
			"depressedFgColor_override" "bh_orange"
			
			"image_drawcolor"			"255 255 255 255"
			"image_armedcolor"			"150 150 150 255"

			"SubImage"
			{
				"ControlName"			"ImagePanel"
				"fieldName"				"SubImage"
				"xpos"					"6"
				"ypos"					"6"
				"zpos"					"1"
				"wide"					"14"
				"tall"					"14"
				"visible"				"1"
				"enabled"				"1"
				"scaleImage"			"1"
			}
		}
	}
	
///////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////////////////////////////
	
	"PlayComp"
	{
		"ControlName"						"EditablePanel"
		"fieldname"							"PlayComp"
		"xpos"								"125"
		"ypos"								"120"
		"zpos"								"11"
		"wide"								"225"
		"tall"								"40"
		"visible"							"1"
		"PaintBackgroundType"				"0"

		"navUp"							 	"QuickplayButton"
		"navDown"							"ServerBrowserButton"
		"navRight"							"Notifications_ShowButtonPanel"
		"navToRelay"						"SubButton"

		"SubButton"
		{
			"ControlName"					"CExImageButton"
			"fieldName"						"SubButton"
			"xpos"							"0"
			"ypos"							"0"
			"wide"							"350"
			"tall"							"40"
			"autoResize"					"0"
			"pinCorner"						"3"
			"visible"						"1"
			"enabled"						"1"
			"tabPosition"					"0"
			"textinsetx"					"25"
			"use_proportional_insets" 		"1"
			"font"							"LatoSemibold36"
			"textAlignment"					"west"
			"dulltext"						"0"
			"brighttext"					"0"
			"default"						"1"
			"sound_depressed"				"UI/buttonclick.wav"
			"sound_released"				"UI/buttonclickrelease.wav"
			
		//	"border_default"				"MainMenuButtonDefault"
		//	"border_armed"					"MainMenuButtonArmed"
			"paintbackground"				"0"
			
			"defaultFgColor_override"	 	"bh_white"
			"armedFgColor_override" 		"bh_orange"
			"depressedFgColor_override" 	"bh_white"
			
		//	"image_drawcolor"				"117 107 94 255"
		//	"image_armedcolor"				"bh_white"

			"SubImage"
			{
				"ControlName"			"ImagePanel"
				"fieldName"				"SubImage"
				"xpos"					"6969"
				"ypos"					"6969"
				"zpos"					"1"
				"wide"					"14"
				"tall"					"14"
				"visible"				"0"
				"enabled"				"0"
				"scaleImage"			"1"
			}
		}
	}	

	"QuickplayButton"
	{
		"ControlName"						"EditablePanel"
		"fieldname"							"QuickplayButton"
		"xpos"								"50"
		"ypos"								"80"
		"zpos"								"11"
		"wide"								"350"
		"tall"								"40"
		"visible"							"1"
		"PaintBackgroundType"				"0"

		"navDown"							"PlayPVEButton"
		"navRight"							"Notifications_ShowButtonPanel"
		"navToRelay"						"SubButton"

		"SubButton"
		{
			"ControlName"					"CExImageButton"
			"fieldName"						"SubButton"
			"xpos"							"0"
			"ypos"							"0"
			"wide"							"300"
			"tall"							"40"
			"autoResize"					"0"
			"pinCorner"						"3"
			"visible"						"1"
			"enabled"						"1"
			"tabPosition"					"0"
			"textinsetx"					"25"
			"use_proportional_insets" 		"1"
			"font"							"LatoSemibold36"
			"textAlignment"					"west"
			"dulltext"						"0"
			"brighttext"					"0"
			"default"						"1"
			"sound_depressed"				"UI/buttonclick.wav"
			"sound_released"				"UI/buttonclickrelease.wav"
			
			// "border_default"				"MainMenuButtonDefault"
			// "border_armed"				"MainMenuButtonArmed"
			"paintbackground"				"0"
			
			"defaultFgColor_override"	 	"bh_white"
			"armedFgColor_override" 		"bh_orange"
			"depressedFgColor_override" 	"bh_white"
			
			// "image_drawcolor"			"117 107 94 255"
			// "image_armedcolor"			"bh_white"

			"SubImage"
			{
				"ControlName"				"ImagePanel"
				"fieldName"					"SubImage"
				"xpos"						"6969"
				"ypos"						"6969"
				"zpos"						"1"
				"wide"						"14"
				"tall"						"14"
				"visible"					"0"
				"enabled"					"0"
				"scaleImage"				"1"
			}
		}
	}

	"ResumeGameButton"
	{
		"ControlName"						"EditablePanel"
		"fieldname"							"ResumeGameButton"
		"xpos"								"50"
		"ypos"								"40"
		"zpos"								"11"
		"wide"								"350"
		"tall"								"40"
		"visible"							"1"
		"PaintBackgroundType"				"0"

		"navUp"								"ServerBrowserButton"
		"navDown"							"QuickplayChangeButton"
		"navRight"							"CallVoteButton"
		"navToRelay"						"SubButton"

		"SubButton"
		{
			"ControlName"					"CExImageButton"
			"fieldName"						"SubButton"
			"xpos"							"0"
			"ypos"							"0"
			"wide"							"300"
			"tall"							"40"
			"autoResize"					"0"
			"pinCorner"						"3"
			"visible"						"1"
			"enabled"						"1"
			"tabPosition"					"0"
			"textinsetx"					"25"
			"use_proportional_insets" 		"1"
			"font"							"LatoSemibold36"
			"textAlignment"					"west"
			"dulltext"						"0"
			"brighttext"					"0"
			"default"						"1"
			"sound_depressed"				"UI/buttonclick.wav"
			"sound_released"				"UI/buttonclickrelease.wav"
			
		//	"border_default"				"MainMenuButtonDefault"
		//	"border_armed"					"MainMenuButtonArmed"
			"paintbackground"				"0"
			
			"defaultFgColor_override"	 	"bh_white"
			"armedFgColor_override" 		"bh_orange"
			"depressedFgColor_override" 	"bh_white"
			
		//	"image_drawcolor"				"117 107 94 255"
		//	"image_armedcolor"				"bh_white"

			"SubImage"
			{
				"ControlName"				"ImagePanel"
				"fieldName"					"SubImage"
				"xpos"						"6969"
				"ypos"						"6969"
				"zpos"						"1"
				"wide"						"14"
				"tall"						"14"
				"visible"					"1"
				"enabled"					"1"
				"scaleImage"				"1"
			}
		}
	}
		
	"QuickplayChangeButton"
	{
		"ControlName"						"EditablePanel"
		"fieldname"							"QuickplayChangeButton"
		"xpos"								"50"
		"ypos"								"80"
		"zpos"								"11"
		"wide"								"350"
		"tall"								"40"
		"visible"							"1"
		"PaintBackgroundType"				"0"

		"navUp"								"ResumeGameButton"
		"navDown"							"ChangeServerButton"
		"navRight"							"Notifications_ShowButtonPanel"
		"navToRelay"						"SubButton"

		"SubButton"
		{
			"ControlName"					"CExImageButton"
			"fieldName"						"SubButton"
			"xpos"							"0"
			"ypos"							"0"
			"wide"							"300"
			"tall"							"40"
			"autoResize"					"0"
			"pinCorner"						"3"
			"visible"						"1"
			"enabled"						"1"
			"tabPosition"					"0"
			"textinsetx"					"25"
			"use_proportional_insets" 		"1"
			"font"							"LatoSemibold36"
			"textAlignment"					"west"
			"dulltext"						"0"
			"brighttext"					"0"
			"default"						"1"
			"sound_depressed"				"UI/buttonclick.wav"
			"sound_released"				"UI/buttonclickrelease.wav"
			
		//	"border_default"				"MainMenuButtonDefault"
		//	"border_armed"					"MainMenuButtonArmed"
			"paintbackground"				"0"
			
			"defaultFgColor_override"	 	"bh_white"
			"armedFgColor_override" 		"bh_orange"
			"depressedFgColor_override" 	"bh_white"
			
		//	"image_drawcolor"				"117 107 94 255"
		//	"image_armedcolor"				"bh_white"

			"SubImage"
			{
				"ControlName"				"ImagePanel"
				"fieldName"					"SubImage"
				"xpos"						"6969"
				"ypos"						"6969"
				"zpos"						"1"
				"wide"						"14"
				"tall"						"14"
				"visible"					"0"
				"enabled"					"0"
				"scaleImage"				"1"
			}
		}
	}

	"PlayPVEButton"
	{
		"ControlName"						"EditablePanel"
		"fieldname"							"PlayPVEButton"
		"xpos"								"50"
		"ypos"								"120"
		"zpos"								"11"
		"wide"								"225"
		"tall"								"40"
		"visible"							"1"
		"PaintBackgroundType"				"0"

		"navUp"							 	"QuickplayButton"
		"navDown"							"ServerBrowserButton"
		"navRight"							"Notifications_ShowButtonPanel"
		"navToRelay"						"SubButton"

		"SubButton"
		{
			"ControlName"					"CExImageButton"
			"fieldName"						"SubButton"
			"xpos"							"0"
			"ypos"							"0"
			"wide"							"350"
			"tall"							"40"
			"autoResize"					"0"
			"pinCorner"						"3"
			"visible"						"1"
			"enabled"						"1"
			"tabPosition"					"0"
			"textinsetx"					"25"
			"use_proportional_insets" 		"1"
			"font"							"LatoSemibold36"
			"textAlignment"					"west"
			"dulltext"						"0"
			"brighttext"					"0"
			"default"						"1"
			"sound_depressed"				"UI/buttonclick.wav"
			"sound_released"				"UI/buttonclickrelease.wav"
			
		//	"border_default"				"MainMenuButtonDefault"
		//	"border_armed"					"MainMenuButtonArmed"
			"paintbackground"				"0"
			
			"defaultFgColor_override"	 	"bh_white"
			"armedFgColor_override" 		"bh_orange"
			"depressedFgColor_override" 	"bh_white"
			
		//	"image_drawcolor"				"117 107 94 255"
		//	"image_armedcolor"				"bh_white"

			"SubImage"
			{
				"ControlName"			"ImagePanel"
				"fieldName"				"SubImage"
				"xpos"					"6969"
				"ypos"					"6969"
				"zpos"					"1"
				"wide"					"14"
				"tall"					"14"
				"visible"				"0"
				"enabled"				"0"
				"scaleImage"			"1"
			}
		}
	}
		
	"ServerBrowserButton"
	{
		"ControlName"						"EditablePanel"
		"fieldname"							"ServerBrowserButton"
		"xpos"								"50"
		"ypos"								"40"
		"zpos"								"11"
		"wide"								"350"
		"tall"								"40"
		"visible"							"0"
		"PaintBackgroundType"				"0"

		"navUp"								"PlayPVEButton"
		"navDown"							"ResumeGameButton"
		"navRight"							"CreateServerButton"
		"navToRelay"						"SubButton"

		"SubButton"
		{
			"ControlName"					"CExImageButton"
			"fieldName"						"SubButton"
			"xpos"							"0"
			"ypos"							"0"
			"wide"							"300"
			"tall"							"40"
			"autoResize"					"0"
			"pinCorner"						"3"
			"visible"						"1"
			"enabled"						"1"
			"tabPosition"					"0"
			"textinsetx"					"25"
			"use_proportional_insets" 		"1"
			"font"							"LatoSemibold36"
			"textAlignment"					"west"
			"dulltext"						"0"
			"brighttext"					"0"
			"default"						"1"
			"sound_depressed"				"UI/buttonclick.wav"
			"sound_released"				"UI/buttonclickrelease.wav"
			
		//	"border_default"				"MainMenuButtonDefault"
		//	"border_armed"					"MainMenuButtonArmed"
			"paintbackground"				"0"
			
			"defaultFgColor_override"	 	"bh_white"
			"armedFgColor_override" 		"bh_orange"
			"depressedFgColor_override" 	"bh_white"
			
		//	"image_drawcolor"				"117 107 94 255"
		//	"image_armedcolor"				"bh_white"

			"SubImage"
			{
				"ControlName"				"ImagePanel"
				"fieldName"					"SubImage"
				"xpos"						"6969"
				"ypos"						"6969"
				"zpos"						"1"
				"wide"						"14"
				"tall"						"14"
				"visible"					"0"
				"enabled"					"0"
				"scaleImage"				"1"
			}
		}
	}
	
	"ChangeServerButton"
	{
		"ControlName"						"EditablePanel"
		"fieldname"							"ChangeServerButton"
		"xpos"								"50"
		"ypos"								"120"
		"zpos"								"11"
		"wide"								"350"
		"tall"								"40"
		"visible"							"1"
		"PaintBackgroundType"				"0"

		"navUp"								"QuickplayChangeButton"
		"navDown"							"CharacterSetupButton"
		"navRight"							"Notifications_ShowButtonPanel"
		"navToRelay"						"SubButton"

		"SubButton"
		{
			"ControlName"					"CExImageButton"
			"fieldName"						"SubButton"
			"xpos"							"0"
			"ypos"							"0"
			"wide"							"300"
			"tall"							"40"
			"autoResize"					"0"
			"pinCorner"						"3"
			"visible"						"1"
			"enabled"						"1"
			"tabPosition"					"0"
			"textinsetx"					"25"
			"use_proportional_insets" 		"1"
			"font"							"LatoSemibold36"
			"textAlignment"					"west"
			"dulltext"						"0"
			"brighttext"					"0"
			"default"						"1"
			"sound_depressed"				"UI/buttonclick.wav"
			"sound_released"				"UI/buttonclickrelease.wav"
			
		//	"border_default"				"MainMenuButtonDefault"
		//	"border_armed"					"MainMenuButtonArmed"
			"paintbackground"				"0"
			
			"defaultFgColor_override"	 	"bh_white"
			"armedFgColor_override" 		"bh_orange"
			"depressedFgColor_override" 	"bh_white"
			
		//	"image_drawcolor"				"117 107 94 255"
		//	"image_armedcolor"				"bh_white"

			"SubImage"
			{
				"ControlName"				"ImagePanel"
				"fieldName"					"SubImage"
				"xpos"						"6969"
				"ypos"						"6969"
				"zpos"						"1"
				"wide"						"14"
				"tall"						"14"
				"visible"					"1"
				"enabled"					"1"
				"scaleImage"				"1"
			}
		}
	}

	"CallVoteButton"
	{
		"ControlName"						"EditablePanel"
		"fieldname"							"CallVoteButton"
		"xpos"								"150"
		"ypos"								"409"
		"zpos"								"12"
		"wide"								"25"
		"tall"								"25"
		"visible"							"1"

		"navLeft"							"ResumeGameButton"
		"navDown"							"QuickplayChangeButton"
		"navRight"							"MutePlayersButton"
		"navToRelay"						"SubButton"

		"SubButton"
		{
			"ControlName"					"CExImageButton"
			"fieldName"						"SubButton"
			"xpos"							"0"
			"ypos"							"0"
			"zpos"							"1"
			"wide"							"25"
			"tall"							"25"
			"autoResize"					"0"
			"pinCorner"						"3"
			"visible"						"1"
			"enabled"						"1"
			"tabPosition"					"0"
			"font"							"HudFontSmallBold"
			"textAlignment"					"center"
			"dulltext"						"0"
			"brighttext"					"0"
			"default"						"1"
			"sound_depressed"				"UI/buttonclick.wav"
			"sound_released"				"UI/buttonclickrelease.wav"
			
		//	"border_default"				"MainMenuMiniButtonDefault"
		//	"border_armed"					"MainMenuMiniButtonArmed"
			"paintbackground"				"0"
			
			"image_drawcolor"				"255 255 255 255"
			"image_armedcolor"				"240 134 49 255"
			
			"SubImage"
			{
				"ControlName"				"ImagePanel"
				"fieldName"					"SubImage"
				"xpos"						"4"
				"ypos"						"4"
				"zpos"						"1"
				"wide"						"12"
				"tall"						"12"
				"visible"					"1"
				"enabled"					"1"
				"image"						"replay\thumbnails\callvote"
				"scaleImage"				"1"
			}				
		}
	}
	"MutePlayersButton"
	{
		"ControlName"						"EditablePanel"
		"fieldname"							"MutePlayersButton"
		"xpos"								"170"
		"ypos"								"409"
		"zpos"								"12"
		"wide"								"25"
		"tall"								"25"
		"visible"							"1"

		"navLeft"							"CallVoteButton"
		"navDown"							"QuickplayChangeButton"
		"navRight"							"RequestCoachButton"
		"navToRelay"						"SubButton"

		"SubButton"
		{
			"ControlName"					"CExImageButton"
			"fieldName"						"SubButton"
			"xpos"							"0"
			"ypos"							"0"
			"zpos"							"1"
			"wide"							"25"
			"tall"							"25"
			"autoResize"					"0"
			"pinCorner"						"3"
			"visible"						"1"
			"enabled"						"1"
			"tabPosition"					"0"
			"font"							"HudFontSmallBold"
			"textAlignment"					"center"
			"dulltext"						"0"
			"brighttext"					"0"
			"default"						"1"
			"sound_depressed"				"UI/buttonclick.wav"
			"sound_released"				"UI/buttonclickrelease.wav"
			
		//	"border_default"				"MainMenuMiniButtonDefault"
		//	"border_armed"					"MainMenuMiniButtonArmed"
			"paintbackground"				"0"
			
			"image_drawcolor"				"255 255 255 255"
			"image_armedcolor"				"240 134 49 255"
			
			"SubImage"
			{
				"ControlName"				"ImagePanel"
				"fieldName"					"SubImage"
				"xpos"						"4"
				"ypos"						"4"
				"zpos"						"1"
				"wide"						"12"
				"tall"						"12"
				"visible"					"1"
				"enabled"					"1"
				"image"						"replay\thumbnails\muteplayers"
				"scaleImage"				"1"
			}				
		}
	}

	"RequestCoachButton"
	{
		"ControlName"						"EditablePanel"
		"fieldname"							"RequestCoachButton"
		"xpos"								"190"
		"ypos"								"409"
		"zpos"								"12"
		"wide"								"25"
		"tall"								"25"
		"visible"							"1"

		"navLeft"							"MutePlayersButton"
		"navRight"							"Notifications_ShowButtonPanel"
		"navDown"							"QuickplayChangeButton"
		"navToRelay"						"SubButton"

		"SubButton"
		{
			"ControlName"					"CExImageButton"
			"fieldName"						"SubButton"
			"xpos"							"0"
			"ypos"							"0"
			"zpos"							"1"
			"wide"							"25"
			"tall"							"25"
			"autoResize"					"0"
			"pinCorner"						"3"
			"visible"						"1"
			"enabled"						"1"
			"tabPosition"					"0"
			"font"							"HudFontSmallBold"
			"textAlignment"					"center"
			"dulltext"						"0"
			"brighttext"					"0"
			"default"						"1"
			"sound_depressed"				"UI/buttonclick.wav"
			"sound_released"				"UI/buttonclickrelease.wav"
			
		//	"border_default"				"MainMenuMiniButtonDefault"
		//	"border_armed"					"MainMenuMiniButtonArmed"
			"paintbackground"				"0"
			
			"image_drawcolor"				"255 255 255 255"
			"image_armedcolor"				"240 134 49 255"
			
			"SubImage"
			{
				"ControlName"				"ImagePanel"
				"fieldName"					"SubImage"
				"xpos"						"4"
				"ypos"						"4"
				"zpos"						"1"
				"wide"						"12"
				"tall"						"12"
				"visible"					"1"
				"enabled"					"1"
				"image"						"replay\thumbnails\callcoach"
				"scaleImage"				"1"
			}				
		}
	}
	
	"BackgroundFooter"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"BackgroundFooter"
		"xpos"			"6969"
		"ypos"			"6969"
		"zpos"			"-50"
		"wide"			"f0"
		"tall"			"60"
		"visible"		"0"
		"enabled"		"0"
		"image"			"loadout_bottom_gradient"
		"tileImage"		"1"
	}				
	"FooterLine"
	{
		"ControlName"	"ImagePanel"
		"fieldName"		"FooterLine"
		"xpos"			"6969"
		"ypos"			"6969"
		"zpos"			""
		"wide"			"f0"
		"tall"			"10"
		"visible"		"0"
		"enabled"		"0"
		"image"			"loadout_solid_line"
		"scaleImage"	"1"
	}	
	
	"NewUserForumsButton"
	{
		"ControlName"	"CExImageButton"
		"fieldName"		"NewUserForumsButton"
		"xpos"			"6969"
		"ypos"			"6969"
		"zpos"			"2"
		"wide"			"30"
		"tall"			"25"
		"autoResize"	"0"
		"pinCorner"		"3"
		"visible"		"0"
		"enabled"		"0"
		"tabPosition"	"0"
		"labelText"		""
		"font"			"HudFontSmallBold"
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"default"		"1"
		"Command"		"view_newuser_forums"

		"navUp"			"VRModeButton"
		"navLeft"		"QuitButton"
		"navRight"		"AchievementsButton"

		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"PaintBackgroundType" "0"
		
		"image_drawcolor"	"bh_white"
		"SubImage"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"SubImage"
			"xpos"			"6969"
			"ypos"			"6969"
			"zpos"			"1"
			"wide"			"18"
			"tall"			"18"
			"visible"		"0"
			"enabled"		"0"
			"image"			"glyph_tutorial"
			"scaleImage"	"1"
		}				
	}		
	
	"AchievementsButton"
	{
		"ControlName"						"CExImageButton"
		"fieldName"							"AchievementsButton"
		"xpos"								"70"
		"ypos"								"407"
		"zpos"								"3"
		"wide"								"25"
		"tall"								"25"
		"autoResize"						"0"
		"pinCorner"							"3"
		"visible"							"1"
		"enabled"							"1"
		"tabPosition"						"0"
		"labelText"							""
		"font"								"HudFontSmallBold"
		"textAlignment"						"center"
		"dulltext"							"0"
		"brighttext"						"0"
		"default"							"1"
		"Command"							"OpenAchievementsDialog"

		"navUp"								"VRModeButton"
		"navLeft"							"NewUserForumsButton"
		"navRight"							"CommentaryButton"
		
	//	"border_default"					"MainMenuMiniButtonDefault"
	//	"border_armed"						"MainMenuMiniButtonArmed"
		"paintbackground"					"0"
	
		"sound_depressed"					"UI/buttonclick.wav"
		"sound_released"					"UI/buttonclickrelease.wav"
	//	"border_default"					"MainMenuSubButtonBorder"
		
		"image_drawcolor"				"255 255 255 255"
		"image_armedcolor"				"240 134 49 255"
		
		"SubImage"
		{
			"ControlName"					"ImagePanel"
			"fieldName"						"SubImage"
			"xpos"							"5"
			"ypos"							"6"
			"zpos"							"1"
			"wide"							"15"
			"tall"							"15"
			"visible"						"1"
			"enabled"						"1"
			"image"							"replay\thumbnails\achievements"
			"scaleImage"					"1"
		}				
	}		
	
	"CommentaryButton"
	{
		"ControlName"						"CExImageButton"
		"fieldName"							"CommentaryButton"
		"xpos"								"90"
		"ypos"								"407"
		"zpos"								"4"
		"wide"								"25"
		"tall"								"25"
		"autoResize"						"0"
		"pinCorner"							"3"
		"visible"							"1"
		"enabled"							"1"
		"tabPosition"						"0"
		"labelText"							""
		"font"								"HudFontSmallBold"
		"textAlignment"						"center"
		"dulltext"							"0"
		"brighttext"						"0"
		"default"							"1"
		"Command"							"OpenLoadSingleplayerCommentaryDialog"

		"navUp"								"VRModeButton"
		"navLeft"							"AchievementsButton"
		"navRight"							"CoachPlayersButton"
		
		"paintbackground"					"0"

		"sound_depressed"					"UI/buttonclick.wav"
		"sound_released"					"UI/buttonclickrelease.wav"
	//	"border_default"					"MainMenuSubButtonBorder"
		
		"image_drawcolor"				"255 255 255 255"
		"image_armedcolor"				"240 134 49 255"

		"SubImage"
		{
			"ControlName"					"ImagePanel"
			"fieldName"						"SubImage"
			"xpos"							"5"
			"ypos"							"6"
			"zpos"							"1"
			"wide"							"15"
			"tall"							"15"
			"visible"						"1"
			"enabled"						"1"
			"image"							"replay/thumbnails/developercommentary"
			"scaleImage"					"1"
		}				
	}		
	
	"CoachPlayersButton"
	{
		"ControlName"						"CExImageButton"
		"fieldName"							"CoachPlayersButton"
		"xpos"								"110"
		"ypos"								"407"
		"zpos"								"5"
		"wide"								"25"
		"tall"								"25"
		"autoResize"						"0"
		"pinCorner"							"3"
		"visible"							"1"
		"enabled"							"1"
		"tabPosition"						"0"
		"labelText"							""
		"font"								"HudFontSmallBold"
		"textAlignment"						"center"
		"dulltext"							"0"
		"brighttext"						"0"
		"default"							"1"
		"Command"							"engine cl_coach_toggle"

		"navUp"								"VRModeButton"
		"navLeft"							"CommentaryButton"
		"navRight"							"ReportBugButton"
		
		"paintbackground"					"0"

		"sound_depressed"					"UI/buttonclick.wav"
		"sound_released"					"UI/buttonclickrelease.wav"
	//	"border_default"					"MainMenuSubButtonBorder"
		
		"image_drawcolor"				"255 255 255 255"
		"image_armedcolor"				"240 134 49 255"
		
		"SubImage"
		{
			"ControlName"					"ImagePanel"
			"fieldName"						"SubImage"
			"xpos"							"5"
			"ypos"							"5"
			"zpos"							"1"
			"wide"							"15"
			"tall"							"15"
			"visible"						"1"
			"enabled"						"1"
			"image"							"replay/thumbnails/beacoach"
			"scaleImage"					"1"
		}				
	}		
	
	"ReportBugButton"
	{
		"ControlName"						"CExImageButton"
		"fieldName"							"ReportBugButton"
		"xpos"								"130"
		"ypos"								"406"
		"zpos"								"1"
		"wide"								"25"
		"tall"								"25"
		"autoResize"						"0"
		"pinCorner"							"3"
		"visible"							"1"
		"enabled"							"1"
		"tabPosition"						"0"
		"labelText"							""
		"font"								"HudFontSmallBold"
		"textAlignment"						"center"
		"dulltext"							"0"
		"brighttext"						"0"
		"default"							"1"
		"Command"							"engine bug"

		"navUp"								"VRModeButton"
		"navLeft"							"CoachPlayersButton"
		"navRight"							"SettingsButton"
		
		"paintbackground"					"0"

		"sound_depressed"					"UI/buttonclick.wav"
		"sound_released"					"UI/buttonclickrelease.wav"
	//	"border_default"					"MainMenuSubButtonBorder"
		
		"image_drawcolor"					"255 255 255 255"
		"image_armedcolor"					"240 134 49 255"
		"SubImage"
		{
			"ControlName"					"ImagePanel"
			"fieldName"						"SubImage"
			"xpos"							"5"
			"ypos"							"6"
			"zpos"							"1"
			"wide"							"15"
			"tall"							"15"
			"visible"						"1"
			"enabled"						"1"
			"image"							"replay/thumbnails/reportbug"
			"scaleImage"					"1"
		}				
	}		
	
	"TF2SettingsButton"
	{
		"ControlName"						"CExImageButton"
		"fieldName"							"TF2SettingsButton"
		"xpos"								"50"
		"ypos"								"320"
		"zpos"								"1"
		"wide"								"350"
		"tall"								"40"
		"autoResize"						"0"
		"pinCorner"							"3"
		"visible"							"1"
		"enabled"							"1"
		"tabPosition"						"0"
		"textinsetx"						"25"
		"use_proportional_insets"			"1"
		"labelText"							"ADVANCED OPTIONS"
		"font"								"LatoSemibold36"
		"textAlignment"						"west"
		"textinsetx"						"25"
		"dulltext"							"0"
		"brighttext"						"0"
		"default"							"1"
		"Command"							"opentf2options"

		"navUp"								"Notifications_Panel"
		"navLeft"							"SettingsButton"

		"sound_depressed"					"UI/buttonclick.wav"
		"sound_released"					"UI/buttonclickrelease.wav"
		
		"paintbackground"					"0"
		"defaultFgColor_override"	 		"bh_white"
		"armedFgColor_override" 			"bh_orange"
		"depressedFgColor_override" 		"bh_white"			
		
	//	"image_drawcolor"					"bh_white"
		"SubImage"
		{
			"ControlName"					"ImagePanel"
			"fieldName"						"SubImage"
			"xpos"							"6969"
			"ypos"							"6969"
			"zpos"							"1"
			"wide"							"14"
			"tall"							"14"
			"visible"						"0"
			"enabled"						"0"
			"scaleImage"					"1"
			"image"							"glyph_options"
			"scaleImage"					"1"
		}				
	}		
	
	"SettingsButton"
	{
		"ControlName"						"CExImageButton"
		"fieldName"							"SettingsButton"
		"xpos"								"50"
		"ypos"								"280"
		"zpos"								"1"
		"wide"								"350"
		"tall"								"40"
		"autoResize"						"0"
		"pinCorner"							"3"
		"visible"							"1"
		"enabled"							"1"
		"tabPosition"						"0"
		"textinsetx"						"25"
		"use_proportional_insets"			"1"
		"labelText"							"#GameUI_GameMenu_Options"
		"font"								"LatoSemibold36"
		"textAlignment"						"west"
		"textinsetx"						"25"
		"use_proportional_insets" 			"1"
		"dulltext"							"0"
		"brighttext"						"0"
		"default"							"1"
		"Command"							"OpenOptionsDialog"

		"navUp"								"Notifications_Panel"
		"navLeft"							"ReportBugButton"
		"navRight"							"TF2SettingsButton"

		"sound_depressed"					"UI/buttonclick.wav"
		"sound_released"					"UI/buttonclickrelease.wav"
		
		"paintbackground"					"0"
		"defaultFgColor_override"	 		"bh_white"
		"armedFgColor_override" 			"bh_orange"
		"depressedFgColor_override" 		"bh_white"		
		
	//	"image_drawcolor"					"bh_white"
		"SubImage"
		{
			"ControlName"					"ImagePanel"
			"fieldName"						"SubImage"
			"xpos"							"6969"
			"ypos"							"6969"
			"zpos"							"1"
			"wide"							"14"
			"tall"							"14"
			"visible"						"0"
			"enabled"						"0"
			"scaleImage"					"1"
			"image"							"glyph_options"
		}			
	}
	
	"QuitButton"
	{
		"ControlName"						"CExImageButton"
		"fieldName"							"QuitButton"
		"xpos"								"50"
		"ypos"								"360"
		"zpos"								"1"
		"wide"								"350"
		"tall"								"40"
		"autoResize"						"0"
		"pinCorner"							"3"
		"visible"							"1"
		"enabled"							"1"
		"tabPosition"						"0"
		"labelText"							"QUIT"
		"font"								"LatoSemibold36"
		"textAlignment"						"west"
		"textinsetx"						"25"
		"use_proportional_insets"			"1"
		"dulltext"							"0"
		"brighttext"						"0"
		"default"							"1"
		"Command"							"engine replay_confirmquit"

		"navUp"								"VRModeButton"
		"navDown"							"DisconnectButton"
		"navLeft"							"DisconnectButton"
		"navRight"							"NewUserForumsButton"

		"sound_depressed"					"UI/buttonclick.wav"
		"sound_released"					"UI/buttonclickrelease.wav"
		
		"paintbackground"					"0"
		"defaultFgColor_override"	 		"bh_white"
		"armedFgColor_override" 			"bh_orange"
		"depressedFgColor_override" 		"bh_white"
		
	//	"image_drawcolor"					"bh_white"
		"SubImage"
		{
			"ControlName"					"ImagePanel"
			"fieldName"						"SubImage"
			"xpos"							"6969"
			"ypos"							"6969"
			"zpos"							"1"
			"wide"							"14"
			"tall"							"14"
			"visible"						"0"
			"enabled"						"0"
			"scaleImage"					"1"
			"image"							"glyph_quit"
		}				
	}			

	"DemoUIButton"
	{
		"ControlName"				"CExImageButton"
		"fieldName"					"DemoUIButton"
		"xpos"						"40"
		"ypos"						"430"
		"zpos"						"1"
		"wide"						"70"
		"tall"						"16"
		"autoResize"				"0"
		"pinCorner"					"3"
		"visible"					"1"
		"enabled"					"1"
		"tabPosition"				"0"
		"labelText"					"DemoUI"
		"font"						"LatoSemibold18"
		"textAlignment"				"west"
		"textinsetx"				"35"
		"use_proportional_insets" 	"1"
		"dulltext"					"0"
		"brighttext"				"0"
		"default"					"1"
		"paintbackground"			"0"
		"Command"					"engine demoui"
		
		"defaultFgColor_override" 	"bh_white"
		"armedFgColor_override" 	"bh_orange"
		"depressedFgColor_override" "bh_orange"		
		
		"sound_depressed"			"ui/buttonclick.wav"
		"sound_released"			"ui/buttonclickrelease.wav"
		
		"image_drawcolor"			"bh_white"
		"image_armedcolor"			"bh_orange"
		"SubImage"
		{
			"ControlName"			"ImagePanel"
			"fieldName"				"SubImage"
			"xpos"					"16"
			"ypos"					"6"
			"zpos"					"1"
			"wide"					"0"
			"tall"					"0"
			"visible"				"1"
			"enabled"				"1"
			"scaleImage"			"1"
			"image"					"glyph_quit"
		}				
	}

	"ConsoleButton"
	{
		"ControlName"				"CExImageButton"
		"fieldName"					"ConsoleButton"
		"xpos"						"75"
		"ypos"						"430"
		"zpos"						"1"
		"wide"						"70"
		"tall"						"16"
		"autoResize"				"0"
		"pinCorner"					"3"
		"visible"					"1"
		"enabled"					"1"
		"tabPosition"				"0"
		"labelText"					"Console"
		"font"						"LatoSemibold18"
		"textAlignment"				"west"
		"textinsetx"				"35"
		"use_proportional_insets" 	"1"
		"dulltext"					"0"
		"brighttext"				"0"
		"default"					"1"
		"paintbackground"			"0"
		"Command"					"engine toggleconsole"
		
		"defaultFgColor_override" 	"bh_white"
		"armedFgColor_override" 	"bh_orange"
		"depressedFgColor_override" "bh_orange"		
		
		"sound_depressed"			"UI/buttonclick.wav"
		"sound_released"			"UI/buttonclickrelease.wav"
		
		"image_drawcolor"			"bh_white"
		"image_armedcolor"			"bh_orange"
		"SubImage"
		{
			"ControlName"			"ImagePanel"
			"fieldName"				"SubImage"
			"xpos"					"16"
			"ypos"					"6"
			"zpos"					"1"
			"wide"					"0"
			"tall"					"0"
			"visible"				"1"
			"enabled"				"1"
			"scaleImage"			"1"
			"image"					"glyph_quit"
		}				
	}
	
	
	"DisconnectButton"
	{
		"ControlName"						"CExImageButton"
		"fieldName"							"DisconnectButton"
		"xpos"								"50"
		"ypos"								"360"
		"zpos"								"1"
		"wide"								"350"
		"tall"								"40"
		"autoResize"						"0"
		"pinCorner"							"3"
		"visible"							"1"
		"enabled"							"1"
		"tabPosition"						"0"
		"textinsetx"						"25"
		"use_proportional_insets" 			"1"
		"labelText"							"DISCONNECT"
		"font"								"LatoSemibold36"
		"textAlignment"						"west"
		"dulltext"							"0"
		"brighttext"						"0"
		"default"							"1"
		"Command"							"engine disconnect"
		"sound_depressed"					"UI/buttonclick.wav"
		"sound_released"					"UI/buttonclickrelease.wav"
		
		"PaintBackgroundType"				"0"
		"paintbackground"					"0"
		"defaultFgColor_override"	 		"bh_white"
		"armedFgColor_override" 			"bh_orange"
		"depressedFgColor_override" 		"bh_white"

		"navUp"								"QuitButton"
		"navRight"							"NewUserForumsButton"
		
	//	"image_drawcolor"				"bh_white"
		"SubImage"
		{
			"ControlName"				"ImagePanel"
			"fieldName"					"SubImage"
			"xpos"						"6969"
			"ypos"						"6969"
			"zpos"						"1"
			"wide"						"14"
			"tall"						"14"
			"visible"					"0"
			"enabled"					"0"
			"scaleImage"				"1"
			"image"						"glyph_quit"
		}				
	}			
	
	"BackToReplaysButton"
	{
		"ControlName"	"CExImageButton"
		"fieldName"		"BackToReplaysButton"
		"xpos"			"c-300"
		"ypos"			"250"
		"zpos"			"1"
		"wide"			"170"
		"tall"			"25"
		"autoResize"	"0"
		"pinCorner"		"3"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"#GameUI_GameMenu_ExitReplay"
		"font"			"HudFontSmallBold"
		"textAlignment"	"west"
		"textinsetx"	"35"
		"use_proportional_insets" "1"
		"dulltext"		"0"
		"brighttext"	"0"
		"default"		"1"
		"Command"		"exitreplayeditor"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		
		"image_drawcolor"	"bh_white"
		"SubImage"
		{
			"ControlName"	"ImagePanel"
			"fieldName"		"SubImage"
			"xpos"			"16"
			"ypos"			"6"
			"zpos"			"1"
			"wide"			"14"
			"tall"			"14"
			"visible"		"1"
			"enabled"		"1"
			"scaleImage"	"1"
			"image"			"glyph_quit"
		}				
	}			
	
	"TutorialHighlight"
	{
		"ControlName"	"CExplanationPopup"
		"fieldName"		"TutorialHighlight"
		"xpos"			"c-285"
		"ypos"			"195"
		"zpos"			"100"
		"wide"			"250"
		"tall"			"120"
		"visible"		"0"
		"PaintBackgroundType"	"2"
		"paintbackground" "0"
		"border"		"MainMenuHighlightBorder"
		
		"start_x"		"c-85"
		"start_y"		"185"
		"start_wide"	"1"
		"start_tall"	"1"
		"end_x"			"c20"
		"end_y"			"120"
		"end_wide"		"250"
		"end_tall"		"120"
		"callout_inparents_x"	"c-40"
		"callout_inparents_y"	"195"
		
		"TitleLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"TitleLabel"
			"font"			"HudFontSmallBold"
			"labelText"		"%highlighttext%"
			"textAlignment"	"center"
			"xpos"			"20"
			"ypos"			"10"
			"wide"			"210"
			"tall"			"60"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"wrap"			"1"
			"fgcolor_override" "46 43 42 255"
		}
		
		"TextLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"TextLabel"
			"font"			"HudFontSmall"
			"labelText"		"#MMenu_TutorialHighlight_Text"
			"textAlignment"	"south-west"
			"xpos"			"20"
			"ypos"			"60"
			"wide"			"210"
			"tall"			"20"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"fgcolor_override" "46 43 42 255"
		}
		
		"TutorialHighlightButton"
		{
			"ControlName"	"EditablePanel"
			"fieldname"		"TutorialHighlightButton"
			"xpos"			"10"
			"ypos"			"85"
			"wide"			"230"
			"tall"			"26"
			"visible"		"1"
			
			"SubButton"
			{
				"ControlName"	"CExImageButton"
				"fieldName"		"SubButton"
				"xpos"			"0"
				"ypos"			"0"
				"wide"			"230"
				"tall"			"26"
				"autoResize"	"0"
				"pinCorner"		"3"
				"visible"		"1"
				"enabled"		"1"
				"tabPosition"	"0"
				"labeltext"		"#MMenu_TutorialHighlight_Button"
				"font"			"HudFontSmallBold"
				"textAlignment"	"center"
				"dulltext"		"0"
				"brighttext"	"0"
				"default"		"1"
				"sound_depressed"	"UI/buttonclick.wav"
				"sound_released"	"UI/buttonclickrelease.wav"
				"Command"		"tutorial"
				
				"border_default"	"MainMenuButtonDefault"
				"border_armed"		"MainMenuButtonArmed"
				"paintbackground"	"0"
				
				"defaultFgColor_override" "46 43 42 255"
				"armedFgColor_override" "bh_white"
				"depressedFgColor_override" "46 43 42 255"
				
				"image_drawcolor"	"117 107 94 255"
				"image_armedcolor"	"bh_white"
				"SubImage"
				{
					"ControlName"	"ImagePanel"
					"fieldName"		"SubImage"
					"xpos"			"6"
					"ypos"			"6"
					"zpos"			"1"
					"wide"			"14"
					"tall"			"14"
					"visible"		"1"
					"enabled"		"1"
					"scaleImage"	"1"
				}				
			}		
		}
		
		"CloseButton"
		{
			"ControlName"	"CExImageButton"
			"fieldName"		"CloseButton"
			"xpos"			"230"
			"ypos"			"5"
			"zpos"			"10"
			"wide"			"14"
			"tall"			"14"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labeltext"		""
			"font"			"HudFontSmallBold"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"default"		"1"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"Command"		"close"
			
			"paintbackground"	"0"
			
			"defaultFgColor_override" "46 43 42 255"
			"armedFgColor_override" "bh_white"
			"depressedFgColor_override" "46 43 42 255"
			
			"image_drawcolor"	"117 107 94 255"
			"image_armedcolor"	"200 80 60 255"
			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"1"
				"wide"			"14"
				"tall"			"14"
				"visible"		"1"
				"enabled"		"1"
				"image"			"close_button"
				"scaleImage"	"1"
			}				
		}		
	}	
	
	"PracticeHighlight"
	{
		"ControlName"	"CExplanationPopup"
		"fieldName"		"PracticeHighlight"
		"zpos"			"100"
		"wide"			"250"
		"tall"			"120"
		"visible"		"0"
		"PaintBackgroundType"	"2"
		"paintbackground" "0"
		"border"		"MainMenuHighlightBorder"
		
		"start_x"		"c-85"
		"start_y"		"185"
		"start_wide"	"1"
		"start_tall"	"1"
		"end_x"			"c20"
		"end_y"			"120"
		"end_wide"		"250"
		"end_tall"		"120"
		"callout_inparents_x"	"c-40"
		"callout_inparents_y"	"195"
		
		"TitleLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"TitleLabel"
			"font"			"HudFontSmallBold"
			"labelText"		"#MMenu_PracticeHighlight_Title"
			"textAlignment"	"center"
			"xpos"			"20"
			"ypos"			"10"
			"wide"			"210"
			"tall"			"50"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"wrap"			"1"
			"fgcolor_override" "46 43 42 255"
		}
		
		"TextLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"TextLabel"
			"font"			"HudFontSmall"
			"labelText"		"#MMenu_PracticeHighlight_Text"
			"textAlignment"	"south-west"
			"xpos"			"20"
			"ypos"			"50"
			"wide"			"210"
			"tall"			"30"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"fgcolor_override" "46 43 42 255"
		}
		
		"PracticeHighlightButton"
		{
			"ControlName"	"EditablePanel"
			"fieldname"		"PracticeHighlightButton"
			"xpos"			"10"
			"ypos"			"85"
			"wide"			"230"
			"tall"			"26"
			"visible"		"1"
			
			"SubButton"
			{
				"ControlName"	"CExImageButton"
				"fieldName"		"SubButton"
				"xpos"			"0"
				"ypos"			"0"
				"wide"			"230"
				"tall"			"26"
				"autoResize"	"0"
				"pinCorner"		"3"
				"visible"		"1"
				"enabled"		"1"
				"tabPosition"	"0"
				"labeltext"		"#MMenu_PracticeHighlight_Button"
				"font"			"HudFontSmallBold"
				"textAlignment"	"center"
				"dulltext"		"0"
				"brighttext"	"0"
				"default"		"1"
				"sound_depressed"	"UI/buttonclick.wav"
				"sound_released"	"UI/buttonclickrelease.wav"
				"Command"		"offlinepractice"
				
				"border_default"	"MainMenuButtonDefault"
				"border_armed"		"MainMenuButtonArmed"
				"paintbackground"	"0"
				
				"defaultFgColor_override" "46 43 42 255"
				"armedFgColor_override" "bh_white"
				"depressedFgColor_override" "46 43 42 255"
				
				"image_drawcolor"	"117 107 94 255"
				"image_armedcolor"	"bh_white"
				"SubImage"
				{
					"ControlName"	"ImagePanel"
					"fieldName"		"SubImage"
					"xpos"			"6"
					"ypos"			"6"
					"zpos"			"1"
					"wide"			"14"
					"tall"			"14"
					"visible"		"1"
					"enabled"		"1"
					"scaleImage"	"1"
				}				
			}		
		}
		
		"CloseButton"
		{
			"ControlName"	"CExImageButton"
			"fieldName"		"CloseButton"
			"xpos"			"230"
			"ypos"			"5"
			"zpos"			"10"
			"wide"			"14"
			"tall"			"14"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labeltext"		""
			"font"			"HudFontSmallBold"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"default"		"1"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"Command"		"close"
			
			"paintbackground"	"0"
			
			"defaultFgColor_override" "46 43 42 255"
			"armedFgColor_override" "bh_white"
			"depressedFgColor_override" "46 43 42 255"
			
			"image_drawcolor"	"117 107 94 255"
			"image_armedcolor"	"200 80 60 255"
			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"1"
				"wide"			"14"
				"tall"			"14"
				"visible"		"1"
				"enabled"		"1"
				"image"			"close_button"
				"scaleImage"	"1"
			}				
		}		
	}	
	
	"NewUserForumHighlight"
	{
		"ControlName"	"CExplanationPopup"
		"fieldName"		"NewUserForumHighlight"
		"xpos"			"c-55"
		"ypos"			"280"
		"zpos"			"100"
		"wide"			"250"
		"tall"			"120"
		"visible"		"0"
		"PaintBackgroundType"	"2"
		"paintbackground" "0"
		"border"		"MainMenuHighlightBorder"
		
		"start_x"		"c-112"
		"start_y"		"437"
		"start_wide"	"1"
		"start_tall"	"1"
		"end_x"			"c-205"
		"end_y"			"280"
		"end_wide"		"250"
		"end_tall"		"120"
		"callout_inparents_x"	"c-116"
		"callout_inparents_y"	"437"
		
		"TitleLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"TitleLabel"
			"font"			"HudFontSmallBold"
			"labelText"		"#MMenu_NewUserForumHighlight_Title"
			"textAlignment"	"north-west"
			"xpos"			"10"
			"ypos"			"10"
			"wide"			"210"
			"tall"			"20"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"wrap"			"1"
			"fgcolor_override" "46 43 42 255"
		}
		
		"TextLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"TextLabel"
			"font"			"HudFontSmall"
			"labelText"		"#MMenu_NewUserForumHighlight_Text"
			"textAlignment"	"north-west"
			"xpos"			"20"
			"ypos"			"30"
			"wide"			"210"
			"tall"			"90"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"wrap"			"1"
			"fgcolor_override" "46 43 42 255"
		}
		
		"CloseButton"
		{
			"ControlName"	"CExImageButton"
			"fieldName"		"CloseButton"
			"xpos"			"230"
			"ypos"			"5"
			"zpos"			"10"
			"wide"			"14"
			"tall"			"14"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labeltext"		""
			"font"			"HudFontSmallBold"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"default"		"1"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"Command"		"close"
			
			"paintbackground"	"0"
			
			"defaultFgColor_override" "46 43 42 255"
			"armedFgColor_override" "bh_white"
			"depressedFgColor_override" "46 43 42 255"
			
			"image_drawcolor"	"117 107 94 255"
			"image_armedcolor"	"200 80 60 255"
			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"1"
				"wide"			"14"
				"tall"			"14"
				"visible"		"1"
				"enabled"		"1"
				"image"			"close_button"
				"scaleImage"	"1"
			}				
		}		
	}	
	
	"OptionsHighlightPanel"
	{
		"ControlName"	"CExplanationPopup"
		"fieldName"		"OptionsHighlightPanel"
		"xpos"			"c-55"
		"ypos"			"280"
		"zpos"			"100"
		"wide"			"250"
		"tall"			"120"
		"visible"		"0"
		"PaintBackgroundType"	"2"
		"paintbackground" "0"
		"border"		"MainMenuHighlightBorder"
		
		"start_x"		"c238"
		"start_y"		"437"
		"start_wide"	"1"
		"start_tall"	"1"
		"end_x"			"c55"
		"end_y"			"280"
		"end_wide"		"250"
		"end_tall"		"120"
		"callout_inparents_x"	"c240"
		"callout_inparents_y"	"437"
		
		"TitleLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"TitleLabel"
			"font"			"HudFontSmallBold"
			"labelText"		"#MMenu_OptionsHighlightPanel_Title"
			"textAlignment"	"north-west"
			"xpos"			"10"
			"ypos"			"10"
			"wide"			"210"
			"tall"			"20"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"wrap"			"1"
			"fgcolor_override" "46 43 42 255"
		}
		
		"TextLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"TextLabel"
			"font"			"HudFontSmall"
			"labelText"		"#MMenu_OptionsHighlightPanel_Text"
			"textAlignment"	"north-west"
			"xpos"			"20"
			"ypos"			"30"
			"wide"			"210"
			"tall"			"90"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"wrap"			"1"
			"fgcolor_override" "46 43 42 255"
		}
		
		"CloseButton"
		{
			"ControlName"	"CExImageButton"
			"fieldName"		"CloseButton"
			"xpos"			"230"
			"ypos"			"5"
			"zpos"			"10"
			"wide"			"14"
			"tall"			"14"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labeltext"		""
			"font"			"HudFontSmallBold"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"default"		"1"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"Command"		"close"
			
			"paintbackground"	"0"
			
			"defaultFgColor_override" "46 43 42 255"
			"armedFgColor_override" "bh_white"
			"depressedFgColor_override" "46 43 42 255"
			
			"image_drawcolor"	"117 107 94 255"
			"image_armedcolor"	"200 80 60 255"
			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"1"
				"wide"			"14"
				"tall"			"14"
				"visible"		"1"
				"enabled"		"1"
				"image"			"close_button"
				"scaleImage"	"1"
			}				
		}		
	}
	
	"LoadoutHighlightPanel"
	{
		"ControlName"	"CExplanationPopup"
		"fieldName"		"LoadoutHighlightPanel"
		"xpos"			"c-55"
		"ypos"			"280"
		"zpos"			"100"
		"wide"			"250"
		"tall"			"120"
		"visible"		"0"
		"PaintBackgroundType"	"2"
		"paintbackground" "0"
		"border"		"MainMenuHighlightBorder"
		
		"start_x"		"c-190"
		"start_y"		"267"
		"start_wide"	"1"
		"start_tall"	"1"
		"end_x"			"c-125"
		"end_y"			"180"
		"end_wide"		"250"
		"end_tall"		"220"
		"callout_inparents_x"	"c-163"
		"callout_inparents_y"	"267"
		
		"TitleLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"TitleLabel"
			"font"			"HudFontSmallBold"
			"labelText"		"#MMenu_LoadoutHighlightPanel_Title"
			"textAlignment"	"north-west"
			"xpos"			"10"
			"ypos"			"10"
			"wide"			"210"
			"tall"			"20"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"wrap"			"1"
			"fgcolor_override" "46 43 42 255"
		}
		
		"TextLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"TextLabel"
			"font"			"HudFontSmall"
			"labelText"		"#MMenu_LoadoutHighlightPanel_Text"
			"textAlignment"	"north-west"
			"xpos"			"20"
			"ypos"			"30"
			"wide"			"210"
			"tall"			"190"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"wrap"			"1"
			"fgcolor_override" "46 43 42 255"
		}
		
		"CloseButton"
		{
			"ControlName"	"CExImageButton"
			"fieldName"		"CloseButton"
			"xpos"			"230"
			"ypos"			"5"
			"zpos"			"10"
			"wide"			"14"
			"tall"			"14"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labeltext"		""
			"font"			"HudFontSmallBold"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"default"		"1"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"Command"		"close"
			
			"paintbackground"	"0"
			
			"defaultFgColor_override" "46 43 42 255"
			"armedFgColor_override" "bh_white"
			"depressedFgColor_override" "46 43 42 255"
			
			"image_drawcolor"	"117 107 94 255"
			"image_armedcolor"	"200 80 60 255"
			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"1"
				"wide"			"14"
				"tall"			"14"
				"visible"		"1"
				"enabled"		"1"
				"image"			"close_button"
				"scaleImage"	"1"
			}				
		}		
	}

	"StoreHighlightPanel"
	{
		"ControlName"	"CExplanationPopup"
		"fieldName"		"StoreHighlightPanel"
		"xpos"			"c0"
		"ypos"			"300"
		"zpos"			"100"
		"wide"			"250"
		"tall"			"60"
		"visible"		"0"
		"PaintBackgroundType"	"2"
		"paintbackground" "0"
		"border"		"MainMenuHighlightBorder"
		
		"start_x"		"c20"
		"start_y"		"285"
		"start_wide"	"250"
		"start_tall"	"125"
		"end_x"			"c20"
		"end_y"			"285"
		"end_wide"		"250"
		"end_tall"		"125"
		"callout_inparents_x"	"c-40"
		"callout_inparents_y"	"267"
		
		"TitleLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"TitleLabel"
			"font"			"HudFontSmallBold"
			"labelText"		"#MMenu_StoreHighlightPanel_Title"
			"textAlignment"	"north-west"
			"xpos"			"10"
			"ypos"			"10"
			"wide"			"210"
			"tall"			"20"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"wrap"			"1"
			"fgcolor_override" "46 43 42 255"
		}
		
		"TextLabel"
		{
			"ControlName"	"CExLabel"
			"fieldName"		"TextLabel"
			"font"			"HudFontSmall"
			"labelText"		"%highlighttext%"
			"textAlignment"	"north-west"
			"xpos"			"20"
			"ypos"			"30"
			"wide"			"210"
			"tall"			"190"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"wrap"			"1"
			"fgcolor_override" "46 43 42 255"
		}
		
		"CloseButton"
		{
			"ControlName"	"CExImageButton"
			"fieldName"		"CloseButton"
			"xpos"			"230"
			"ypos"			"5"
			"zpos"			"10"
			"wide"			"14"
			"tall"			"14"
			"autoResize"	"0"
			"pinCorner"		"0"
			"visible"		"1"
			"enabled"		"1"
			"tabPosition"	"0"
			"labeltext"		""
			"font"			"HudFontSmallBold"
			"textAlignment"	"center"
			"dulltext"		"0"
			"brighttext"	"0"
			"default"		"1"
			"sound_depressed"	"UI/buttonclick.wav"
			"sound_released"	"UI/buttonclickrelease.wav"
			"Command"		"close"
			
			"paintbackground"	"0"
			
			"defaultFgColor_override" "46 43 42 255"
			"armedFgColor_override" "bh_white"
			"depressedFgColor_override" "46 43 42 255"
			
			"image_drawcolor"	"117 107 94 255"
			"image_armedcolor"	"200 80 60 255"
			"SubImage"
			{
				"ControlName"	"ImagePanel"
				"fieldName"		"SubImage"
				"xpos"			"0"
				"ypos"			"0"
				"zpos"			"1"
				"wide"			"14"
				"tall"			"14"
				"visible"		"1"
				"enabled"		"1"
				"image"			"close_button"
				"scaleImage"	"1"
			}				
		}		
	}
}
