//	#base	"..\..\#customization\_enabled\bh_menu_leftalign.res"
//	#base	"..\..\#customization\_enabled\bh_Menugif.res"
//	#base	"..\..\_stream\resource\ui\mainmenuoverride.res"
//	#base	"..\..\_budhud\resource\ui\mainmenuoverride.res"
	#base	"..\..\_tf2hud\resource\ui\mainmenuoverride.res"