	#base	"..\..\#customization\_enabled\bh_mainmenu_hidefriends.res"
//	#base	"..\..\#customization\_enabled\bh_mainmenu_leftalign.res"
//	#base	"..\..\#customization\_enabled\bh_mainmenu_gif.res"
//	#base	"..\..\_stream\resource\ui\mainmenuoverride.res"
//	#base	"..\..\_budhud\resource\ui\mainmenuoverride.res"
	#base	"..\..\_tf2hud\resource\ui\mainmenuoverride.res"