"Resource/UI/Spectator.res"
{
	"Spectator"
	{
		"ControlName"		"Frame"
		"fieldName"			"Spectator"
		"tall"						"480"
		"autoResize"			"0"
		"pinCorner"			"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
	}
	"topbar"
	{
		"ControlName"		"Panel"
		"fieldName"			"TopBar"
		"xpos"					"0"
		"ypos"					"0"
		"tall"						"0"	
		"wide"					"f0"
		"autoResize"			"0"
		"pinCorner"			"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
	}
	"BottomBar"
	{
		"ControlName"		"Frame"
		"fieldName"			"BottomBar"
		"xpos"					"6969"
		"ypos"					"6969"		
		"tall"						"0"	
		"autoResize"			"0"
		"pinCorner"			"0"
		"visible"				"1"
		"enabled"				"0"
		"tabPosition"			"0"
	}
	"bottombarblank"
	{
		"ControlName"		"Panel"
		"fieldName"			"bottombarblank"
		"xpos"					"6969"
		"ypos"					"6969"	
		"tall"						"0"	
		"wide"					"f0"
		"autoResize"			"0"
		"pinCorner"			"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
	}
	"ReinforcementsLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"			"ReinforcementsLabel"
		"xpos"					"c-300"	
		"ypos"					"50"	
		"wide"					"600"	
		"tall"						"24"
		"autoResize"			"0"
		"pinCorner"			"0"
		"visible"				"1"
		"enabled"				"1"
		"labelText"			"#game_respawntime_in_secs"
		"textAlignment"		"center"
		"font"					"RobotoCondensed24"
	}
	"BuyBackLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"			"BuyBackLabel"
		"xpos"					"0"
		"ypos"					"0"
		"wide"					"320"
		"tall"						"30"
		"autoResize"			"0"
		"pinCorner"			"0"
		"visible"				"0"
		"enabled"				"1"
		"labelText"			""
		"textAlignment"		"center"
		"font"					"RobotoCondensed24"
		"wrap"					"1"
		"centerwrap"			"1"
	}
	"MapLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"			"MapLabel"
		"font"					"HudFontSmall"
		"font_hidef"			"HudFontMedium"
		"xpos"					"6969"	
		"ypos"					"6969"	
		"tall"						"20"
		"tall_hidef"			"30"
		"autoResize"			"0"
		"pinCorner"			"0"
		"visible"				"1"
		"enabled"				"1"
		"labelText"			"map: cp_bridge"
		"textAlignment"		"east"
	}
	"ClassOrTeamLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"			"ClassOrTeamLabel"
		"xpos"					"6969"
		"ypos"					"6969"
		"wide"					"170"
		"tall"						"15"
		"zpos"					"2"
		"autoResize"			"0"
		"pinCorner"			"0"
		"visible"				"1"	
		"enabled"				"1"
		"labelText"			"#TF_Spectator_ChangeTeam"
		"textAlignment"		"center"
		"font"					"SpectatorKeyHints"
	}
	"SwitchCamModeKeyLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"			"SwitchCamModeKeyLabel"
		"xpos"					"6969"		
		"ypos"					"6969"	
		"wide"					"60"	
		"tall"						"20"
		"autoResize"			"0"
		"pinCorner"			"0"
		"visible"				"1"	
		"enabled"				"1"
		"labelText"			"#TF_Spectator_ChangeTeam"
		"textAlignment"		"east"
		"font"					"SpectatorKeyHints"
		
	}
	"SwitchCamModeLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"			"SwitchCamModeLabel"
		"xpos"					"6969"	
		"ypos"					"6969"	
		"wide"					"125"	
		"tall"						"20"
		"autoResize"			"0"
		"pinCorner"			"0"
		"visible"				"1"	
		"enabled"				"1"
		"labelText"			"#TF_Spectator_SwitchCamMode"
		"textAlignment"		"west"
		"font"					"SpectatorKeyHints"
	}
	"CycleTargetFwdKeyLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"			"CycleTargetFwdKeyLabel"
		"xpos"					"6969"	
		"ypos"					"6969"	
		"wide"					"60"	
		"tall"						"20"
		"autoResize"			"0"
		"pinCorner"			"0"
		"enabled"				"1"
		"labelText"			"#TF_Spectator_ClassOrTeamKey"
		"textAlignment"		"east"
		"font"					"SpectatorKeyHints"
	}
	"CycleTargetFwdLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"			"CycleTargetFwdLabel"
		"xpos"					"6969"	
		"ypos"					"6969"	
		"wide"					"125"	
		"tall"						"20"
		"autoResize"			"0"
		"pinCorner"			"0"
		"visible"				"1"	
		"enabled"				"1"
		"labelText"			"#TF_Spectator_CycleTargetFwd"
		"textAlignment"		"west"
		"font"					"SpectatorKeyHints"
	}
	"CycleTargetRevKeyLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"			"CycleTargetRevKeyLabel"
		"xpos"					"6969"	
		"ypos"					"6969"	
		"wide"					"60"	
		"tall"						"20"
		"autoResize"			"0"
		"pinCorner"			"0"
		"visible"				"1"	
		"enabled"				"1"
		"labelText"			"#TF_Spectator_ClassOrTeamKey"
		"textAlignment"		"east"
		"font"					"SpectatorKeyHints"
	}
	"CycleTargetRevLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"			"CycleTargetRevLabel"
		"xpos"					"6969"	
		"ypos"					"6969"	
		"wide"					"125"	
		"tall"						"20"
		"autoResize"			"0"
		"pinCorner"			"0"
		"visible"				"1"	
		"enabled"				"1"
		"labelText"			"#TF_Spectator_CycleTargetRev"
		"textAlignment"		"west"
		"font"					"SpectatorKeyHints"
	}
	"TipLabel"
	{
		"ControlName"		"CExLabel"
		"fieldName"			"TipLabel"
		"xpos"					"6969"
		"ypos"					"6969"
		"wide"					"130"
		"tall"						"54"
		"autoResize"			"0"
		"pinCorner"			"0"
		"visible"				"1"
		"enabled"				"1"
		"labelText"			"%tip%"
		"textAlignment"		"center"	
		"font"					"SpectatorKeyHints"
		"wrap"					"1"
	}
		"itempanel"
	{
		"ControlName"				"CItemModelPanel"
		"fieldName"					"itempanel"
		"xpos"							"r249"
		"ypos"							"c0"
		"zpos"							"1"
		"wide"							"240"
		"tall"								"900"
		"visible"						"0"
		"bgcolor_override"			"255 255 255 0"
		"PaintBackgroundType"	"0"
		"paintborder"					"0"
		
		"model_xpos"				"10"
		"model_center_y"			"1"
		"model_wide"				"64"
		"model_tall"					"48"
		
		"text_xpos"					"90"
		"text_ypos"					"25"
		"text_wide"					"150"
		"text_center"					"1"
		
		"max_text_height"			"90"
		"padding_height"			"10"
		"resize_to_text"				"1"
		"text_forcesize"				"2"
		
			"ItemBackground"
			{
			"ControlName" 			"ImagePanel"
			"fieldName" 				"ItemBackground"
			"xpos" 						"0"
			"ypos" 						"0"
			"zpos" 						"-1"
			"wide" 						"240"
			"tall" 						"900"
			"autoResize" 				"0"
			"pinCorner" 				"0"
			"visible" 					"1"
			"enabled" 					"1"
			"fillcolor" 					"0 0 0 100"
			}
			"TitleBackground"
			{
			"ControlName" 			"ImagePanel"
			"fieldName" 				"TitleBackground"
			"xpos" 						"4"
			"ypos" 						"4"
			"zpos" 						"-1"
			"wide" 						"232"
			"tall" 						"14"
			"autoResize" 				"0"
			"pinCorner" 				"0"
			"visible" 					"1"
			"enabled" 					"1"
			"fillcolor" 					"0 0 0 100"
			}
		
		"itemmodelpanel"
		{
			"fieldName"						"itemmodelpanel"
			"use_item_rendertarget" 	"1"
			"useparentbg"					"1"
		}
		
		"ItemLabel"
		{	
			"ControlName"					"CExLabel"
			"fieldName"						"ItemLabel"
			"font"								"RobotoCondensed12"
			"xpos"								"10"
			"ypos"								"5"
			"zpos"								"1"
			"wide"								"270"
			"tall"									"12"
			"autoResize"						"0"
			"pinCorner"						"0"
			"visible"							"1"
			"enabled"							"1"
			"labelText"						"#FreezePanel_Item"
			"textAlignment"					"south-west"
			"dulltext"							"0"
			"brighttext"						"0"
		}
	}		
}
