    #base    "../../../#users/custom/resource/ui/econ/backpackpanel.res"
    #base    "../../../#users/custom/#customization/_enabled/bh_backpackpanel_dev.res"
    #base    "../../../#customization/_enabled/bh_backpackpanel_dev.res"
    #base    "../../../_stream/resource/ui/econ/backpackpanel.res"
    #base    "../../../_budhud/resource/ui/econ/backpackpanel.res"
    #base    "../../../_tf2hud/resource/ui/econ/backpackpanel.res"