"resource/tug_of_war/tug_of_war_hud.res"
{
	"ObjectiveStatusRobotDestruction"
	{
		"ControlName"		"EditablePanel"
		"fieldName"			"ObjectiveStatusRobotDestruction"
		"xpos"				"0"
		"ypos"				"0"
		"zpos"				"1"
		"wide"				"f0"
		"tall"				"480"
		"visible"			"1"
		"enabled"			"1"
	}

	"ScoreContainer"
	{
		"fieldName"				"ScoreContainer"
		"ControlName"			"EditablePanel"
		"xpos"					"0"
		"ypos"					"0"
		"zpos"					"0"
		"wide"					"f0"
		"tall"					"f0"
		"scaleimage"			"0"
		"visible"				"1"
		"enabled"				"1"

		"ProgressBarContainer"
		{
			"fieldName"				"ProgressBarContainer"
			"ControlName"			"EditablePanel"
			"xpos"					"c-148"
			"ypos"					"r165"
			"zpos"					"1"
			"wide"					"300"
			"tall"					"150"
			"visible"				"1"
			"enabled"				"1"
			"proportionalToParent"	"1"


			"BlueProgressBarFill"
			{
				"ControlName"	"EditablePanel"
				"fieldName"		"BlueProgressBarFill"
				"xpos"			"-23"
				"ypos"			"100"
				"zpos"			"5"
				"wide"			"300"
				"tall"			"18"
				"autoResize"	"1"
				"pinCorner"		"0"
				"visible"		"1"
				"enabled"		"1"
				"tabPosition"	"0"
				"scaleImage"	"0"
			}

			"CartBase"
			{
				"ControlName"    "ImagePanel"
				"fieldName"       "CartBase"
				"xpos"            "0"
				"ypos"            "0"
				"zpos"            "0"
				"wide"            "41"
				"tall"            "41"
				"visible"        "1"
				"enabled"        "1"
				"image"            "../tug_of_war/cart_grid"
				"scaleImage"    "1"
				"pin_to_sibling"               "BlueProgressBarFill"
				"pin_corner_to_sibling"        "0"
				"pin_to_sibling_corner"        "1"
			}

			"CartBaseRed"
			{
				"ControlName"    "ImagePanel"
				"fieldName"       "CartBaseRed"
				"xpos"            "-41"
				"ypos"            "0"
				"zpos"            "0"
				"wide"            "41"
				"tall"            "41"
				"visible"        "0"
				"scaleImage"    "1"
				"pin_to_sibling"               "BlueProgressBarFill"
				"pin_corner_to_sibling"        "0"
				"pin_to_sibling_corner"        "1"
			}

			"RedProgressBarFill"
			{
				"fieldName"				"RedProgressBarFill"
				"ControlName"			"ProgressPanel"
				"xpos"					"0"
				"ypos"					"0"
				"zpos"					"2"
				"wide"					"41"
				"tall"					"41"
				"scaleimage"			"0"
				"visible"				"1"
				"proportionalToParent"	"1"
				"positionImage"			"0"
				"drawcolor"				"141 160 171 255"
				"image"            "../tug_of_war/cart_grid_red"

				"left_offset"			"0"
				"right_offset"			"0"
				"standard_color"		"127 143 152 255"
				"bright_color"			"177 193 202 255"
				"left_to_right"			"0"
				"blink_threshold"		"1"
				"blink_rate"			"20"
				"pin_to_sibling"               "CartBaseRed"
				"pin_corner_to_sibling"        "0"
				"pin_to_sibling_corner"        "1"
			}

			"BlueProgressBarEscrow"
			{
				"fieldName"				"BlueProgressBarEscrow"
				"ControlName"			"ProgressPanel"
				"xpos"					"0"
				"ypos"					"0"
				"zpos"					"2"
				"wide"					"41"
				"tall"					"41"
				"scaleimage"			"0"
				"visible"				"1"
				"proportionalToParent"	"1"
				"positionImage"			"0"
				"drawcolor"				"141 160 171 255"
				"image"            "../tug_of_war/cart_grid_blue"

				"left_offset"			"0"
				"right_offset"			"0"
				"standard_color"		"127 143 152 255"
				"bright_color"			"177 193 202 255"
				"left_to_right"			"1"
				"blink_threshold"		"1"
				"blink_rate"			"20"
				"pin_to_sibling"               "CartBase"
				"pin_corner_to_sibling"        "0"
				"pin_to_sibling_corner"        "0"
			}

			"CartCapOverlay"
			{
				"ControlName"    "ImagePanel"
				"fieldName"       "CartCapOverlay"
				"xpos"            "-13"
				"ypos"            "-4"
				"zpos"            "5"
				"wide"            "23"
				"tall"            "11"
				"visible"        "1"
				"enabled"        "1"
				"image"            "../tug_of_war/capture_grid"
				"scaleImage"    "1"
				"pin_to_sibling"               "CartBase"
				"pin_corner_to_sibling"        "0"
				"pin_to_sibling_corner"        "0"
			}

			"CartCapOutline"
			{
				"ControlName"    "ImagePanel"
				"fieldName"       "CartCapOutline"
				"xpos"            "0"
				"ypos"            "0"
				"zpos"            "5"
				"wide"            "41"
				"tall"            "41"
				"visible"        "1"
				"enabled"        "1"
				"image"            "../tug_of_war/cart_cap_outline"
				"scaleImage"    "1"
				"pin_to_sibling"               "CartBase"
				"pin_corner_to_sibling"        "0"
				"pin_to_sibling_corner"        "0"
			}

			"CartCapHightlight"
			{
				"ControlName"    "ImagePanel"
				"fieldName"       "CartCapHightlight"
				"xpos"            "0"
				"ypos"            "100"
				"zpos"            "5"
				"wide"            "34"
				"tall"            "102"
				"visible"        "1"
				"enabled"        "1"
				"image"            "../tug_of_war/capture_highlight"
				"scaleImage"    "1"
				"pin_to_sibling"               "CartBase"
				"pin_corner_to_sibling"        "4"
				"pin_to_sibling_corner"        "4"
			}
		}
	}

	"CountdownContainer"
	{
		"ControlName"			"EditablePanel"
		"fieldName"				"CountdownContainer"
		"xpos"					"0"
		"ypos"					"0"
		"zpos"					"-1"
		"wide"					"f0"
		"tall"					"f0"
		"scaleimage"			"0"
		"visible"				"1"
		"enabled"				"1"

		"CountdownImage"
		{
			"ControlName"		"ImagePanel"
			"fieldName"			"CountdownImage"
			"xpos"				"c-140"
			"ypos"				"r42"
			"zpos"				"0"
			"wide"				"280"
			"tall"				"35"
			"autoResize"		"0"
			"pinCorner"			"0"
			"visible"			"1"
			"enabled"			"1"
			"tabPosition"		"0"
			"Image"				"../tug_of_war/cart_track_32"
			"scaleImage"		"1"
		}
	}
}