#base "../../../#users/custom/resource/ui/classloadoutpanel.res"
#base "../../../_stream/resource/ui/classloadoutpanel.res"

"resource/ui/FullLoadoutPanel.res"
{

    "caratlabel"
    {
        "ypos"                                                      "r-6969"
        "visible"                                                   "0"
        "enabled"                                                   "0"
        "ControlName"                                               "CExLabel"
        "fieldName"                                                 "CaratLabel"
        "font"                                                      "HudFontSmallestBold"
        "labelText"                                                 ">>"
        "textAlignment"                                             "west"
        "xpos"                                                      "c-300"
        "zpos"                                                      "1"
        "wide"                                                      "20"
        "tall"                                                      "15"
        "autoResize"                                                "1"
        "pinCorner"                                                 "0"
        "fgcolor_override"                                          "200 80 60 255"
    }

    "classlabel"
    {
        "ypos"                                                      "r-6969"
        "visible"                                                   "0"
        "enabled"                                                   "0"
        "ControlName"                                               "CExLabel"
        "fieldName"                                                 "ClassLabel"
        "font"                                                      "HudFontMediumBold"
        "labelText"                                                 "#ClassBeingEquipped"
        "textAlignment"                                             "west"
        "xpos"                                                      "c-280"
        "zpos"                                                      "1"
        "wide"                                                      "240"
        "tall"                                                      "25"
        "autoResize"                                                "0"
        "pinCorner"                                                 "0"
    }

    "currentlyequippedlabel"
    {
        "ypos"                                                      "r-6969"
        "visible"                                                   "0"
        "enabled"                                                   "0"
    }

    "topline"
    {
        "ypos"                                                      "r-6969"
        "visible"                                                   "0"
        "enabled"                                                   "0"
        "ControlName"                                               "ImagePanel"
        "fieldName"                                                 "TopLine"
        "xpos"                                                      "c-305"
        "zpos"                                                      "2"
        "wide"                                                      "610"
        "tall"                                                      "10"
        "image"                                                     "loadout_dotted_line"
        "tileImage"                                                 "1"
        "tileVertically"                                            "0"
    }

    "taunthintlabel"
    {
        "ypos"                                                      "r-6969"
        "visible"                                                   "0"
        "enabled"                                                   "0"
        "ControlName"                                               "CExLabel"
        "fieldName"                                                 "TauntHintLabel"
        "font"                                                      "ItemFontAttribLarge"
        "xpos"                                                      "c90"
        "zpos"                                                      "1"
        "wide"                                                      "250"
        "tall"                                                      "25"
        "autoResize"                                                "0"
        "pinCorner"                                                 "0"
        "labelText"                                                 "#TF_ClassLoadoutTauntInputHint"
        "textAlignment"                                             "east"
        "centerwrap"                                                "1"
    }

    "tauntlabel"
    {
        "ypos"                                                      "r-6969"
        "visible"                                                   "0"
        "enabled"                                                   "0"
        "ControlName"                                               "CExLabel"
        "fieldName"                                                 "TauntLabel"
        "font"                                                      "HudFontMediumBold"
        "labelText"                                                 "#TF_Taunt"
        "textAlignment"                                             "west"
        "xpos"                                                      "c-130"
        "zpos"                                                      "1"
        "wide"                                                      "240"
        "tall"                                                      "25"
        "autoResize"                                                "0"
        "pinCorner"                                                 "0"
    }

    "tauntcaratlabel"
    {
        "ypos"                                                      "r-6969"
        "visible"                                                   "0"
        "enabled"                                                   "0"
        "ControlName"                                               "CExLabel"
        "fieldName"                                                 "TauntCaratLabel"
        "font"                                                      "HudFontSmallestBold"
        "labelText"                                                 ">>"
        "textAlignment"                                             "west"
        "xpos"                                                      "c-150"
        "zpos"                                                      "1"
        "wide"                                                      "20"
        "tall"                                                      "15"
        "autoResize"                                                "1"
        "pinCorner"                                                 "0"
        "fgcolor_override"                                          "200 80 60 255"
    }

    "class_loadout_panel"
    {
        "bgcolor_override"                                          "bh_Theme_BG20"
        "infocus_bgcolor_override"                                  "bh_Theme_BG20"
        "outoffocus_bgcolor_override"                               "bh_Theme_BG20"
        "item_xpos_offcenter_a"                                     "-310"
        "item_xpos_offcenter_b"                                     "165"
        "item_ypos"                                                 "60"
        "item_ydelta"                                               "75"
        "item_mod_wide"                                             "40"
        "item_backpack_offcenter_x"                                 "-288"
        "item_backpack_xdelta"                                      "4"
        "item_backpack_ydelta"                                      "3"
        "button_xpos_offcenter"                                     "175"
        "button_ypos"                                               "85"
        "button_ydelta"                                             "80"
        "button_override_delete_xpos"                               "0"

        "modelpanels_kv"
        {

            "itemmodelpanel"
            {
                "allow_rot"                                         "0"
                "inventory_image_type"                              "1"
                "use_item_rendertarget"                             "0"
            }
            "ControlName"                                           "CItemModelPanel"
            "xpos"                                                  "c-70"
            "ypos"                                                  "270"
            "wide"                                                  "140"
            "tall"                                                  "70"
            "visible"                                               "0"
            "bgcolor_override"                                      "0 0 0 0"
            "noitem_textcolor"                                      "117 107 94 255"
            "PaintBackgroundType"                                   "2"
            "paintborder"                                           "1"
            "model_center_x"                                        "1"
            "model_ypos"                                            "5"
            "model_tall"                                            "55"
            "model_wide"                                            "82"
            "text_ypos"                                             "54"
            "text_center"                                           "1"
            "name_only"                                             "1"

            "attriblabel"
            {
                "font"                                              "ItemFontAttribLarge"
                "visible"                                           "0"
            }
        }

        "itemoptionpanels_kv"
        {
            "wide"                                                  "15"
            "tall"                                                  "15"
            "labelText"                                             "+"
            "font"                                                  "bh_Font16"
            "PaintBackground"                                       "0"
            "defaultFgColor_override"                               "bh_white"
            "armedFgColor_override"                                 "bh_Theme_TextAccent"
            "border_default"                                        "NoBorder"
            "border_armed"                                          "NoBorder"
            "border_depressed"                                      "NoBorder"
            "ControlName"                                           "CExButton"
            "xpos"                                                  "0"
            "ypos"                                                  "0"
            "zpos"                                                  "1"
            "autoResize"                                            "0"
            "visible"                                               "0"
            "enabled"                                               "1"
            "tabPosition"                                           "0"
            "textAlignment"                                         "center"
            "dulltext"                                              "0"
            "brighttext"                                            "0"
            "default"                                               "1"
            "sound_depressed"                                       "UI/buttonclick.wav"
            "sound_released"                                        "UI/buttonclickrelease.wav"
        }
        "ControlName"                                               "Frame"
        "fieldName"                                                 "class_loadout_panel"
        "xpos"                                                      "0"
        "ypos"                                                      "0"
        "wide"                                                      "f0"
        "autoResize"                                                "0"
        "pinCorner"                                                 "0"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "tabPosition"                                               "0"
        "settitlebarvisible"                                        "0"
        "PaintBackgroundType"                                       "0"
    }

    "classmodelpanel"
    {
        "xpos"                                                      "0"
        "ypos"                                                      "0"
        "wide"                                                      "f0"
        "tall"                                                      "f0"
        "autoResize"                                                "0"
        "pinCorner"                                                 "0"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "render_texture"                                            "0"
        "fov"                                                       "35"
        "allow_manip"                                               "1"

        "model"
        {
            "force_pos"                                             "1"
            "angles_x"                                              "0"
            "angles_y"                                              "170"
            "origin_x"                                              "440"
            "origin_y"                                              "0"
            "origin_z"                                              "-35"
            "angles_z"                                              "0"
            "frame_origin_x"                                        "0"
            "frame_origin_y"                                        "0"
            "frame_origin_z"                                        "0"
            "spotlight"                                             "1"
            "modelname"                                             ""
        }
        "ControlName"                                               "CTFPlayerModelPanel"
        "fieldName"                                                 "classmodelpanel"
        "zpos"                                                      "-1"
        "allow_rot"                                                 "1"
    }

    "characterloadoutbutton"
    {
        "xpos"                                                      "c-166"
        "ypos"                                                      "c-180"
        "paintbackground"                                           "0"
        "image_drawcolor"                                           "255 255 255 255"
        "image_armedcolor"                                          "240 134 049 255"

        "subimage"
        {
            "wide"                                                  "17"
            "tall"                                                  "17"
            "image"                                                 "replay\thumbnails\menu_icons\loadout"
            "ControlName"                                           "ImagePanel"
            "fieldName"                                             "SubImage"
            "xpos"                                                  "4"
            "ypos"                                                  "4"
            "zpos"                                                  "1"
            "visible"                                               "1"
            "enabled"                                               "1"
            "scaleImage"                                            "1"
        }
        "ControlName"                                               "CExImageButton"
        "fieldName"                                                 "CharacterLoadoutButton"
        "labelText"                                                 ""
        "zpos"                                                      "2"
        "wide"                                                      "25"
        "tall"                                                      "25"
        "autoResize"                                                "0"
        "pinCorner"                                                 "3"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "tabPosition"                                               "0"
        "dulltext"                                                  "0"
        "brighttext"                                                "0"
        "default"                                                   "0"
        "Command"                                                   "characterloadout"
        "sound_depressed"                                           "UI/buttonclick.wav"
        "sound_released"                                            "UI/buttonclickrelease.wav"
    }

    "tauntloadoutbutton"
    {
        "xpos"                                                      "c-166"
        "ypos"                                                      "c-153"
        "paintbackground"                                           "0"
        "image_drawcolor"                                           "255 255 255 255"
        "image_armedcolor"                                          "240 134 049 255"

        "subimage"
        {
            "wide"                                                  "17"
            "tall"                                                  "17"
            "image"                                                 "replay\thumbnails\menu_icons\taunts"
            "ControlName"                                           "ImagePanel"
            "fieldName"                                             "SubImage"
            "xpos"                                                  "4"
            "ypos"                                                  "4"
            "zpos"                                                  "1"
            "visible"                                               "1"
            "enabled"                                               "1"
            "scaleImage"                                            "1"
        }
        "ControlName"                                               "CExImageButton"
        "fieldName"                                                 "TauntLoadoutButton"
        "labelText"                                                 ""
        "zpos"                                                      "2"
        "wide"                                                      "25"
        "tall"                                                      "25"
        "autoResize"                                                "0"
        "pinCorner"                                                 "3"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "tabPosition"                                               "0"
        "dulltext"                                                  "0"
        "brighttext"                                                "0"
        "default"                                                   "0"
        "Command"                                                   "tauntloadout"
        "sound_depressed"                                           "UI/buttonclick.wav"
        "sound_released"                                            "UI/buttonclickrelease.wav"
    }

    "bh_red"
    {
        "ControlName"                                               "CExImageButton"
        "fieldName"                                                 "bh_RED"
        "xpos"                                                      "c-166"
        "ypos"                                                      "c-126"
        "zpos"                                                      "12"
        "wide"                                                      "25"
        "tall"                                                      "25"
        "autoResize"                                                "1"
        "pinCorner"                                                 "2"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "tabPosition"                                               "0"
        "labelText"                                                 "&R"
        "textAlignment"                                             "center"
        "font"                                                      "bh_Font20"
        "scaleImage"                                                "1"
        "command"                                                   "sv_cheats 1;r_skin 0;r_eyes 1"
        "defaultFgColor_override"                                   "bh_white"
        "armedFgColor_override"                                     "bh_red"
        "sound_depressed"                                           "UI/buttonclick.wav"
        "sound_released"                                            "UI/buttonclickrelease.wav"
        "keyboardinputenabled"                                      "0"
        "paintbackground"                                           "0"
    }

    "bh_blu"
    {
        "ControlName"                                               "CExImageButton"
        "fieldName"                                                 "bh_BLU"
        "xpos"                                                      "c-166"
        "ypos"                                                      "c-99"
        "zpos"                                                      "12"
        "wide"                                                      "25"
        "tall"                                                      "25"
        "autoResize"                                                "1"
        "pinCorner"                                                 "2"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "tabPosition"                                               "0"
        "labelText"                                                 "&B"
        "textAlignment"                                             "center"
        "font"                                                      "bh_Font20"
        "scaleImage"                                                "1"
        "command"                                                   "sv_cheats 1;r_skin 1;r_eyes 1"
        "defaultFgColor_override"                                   "bh_white"
        "armedFgColor_override"                                     "bh_blue"
        "sound_depressed"                                           "UI/buttonclick.wav"
        "sound_released"                                            "UI/buttonclickrelease.wav"
        "keyboardinputenabled"                                      "0"
        "paintbackground"                                           "0"
    }

    "mouseoveritempanel"
    {
        "ControlName"                                               "CItemModelPanel"
        "fieldName"                                                 "mouseoveritempanel"
        "xpos"                                                      "c-70"
        "ypos"                                                      "270"
        "zpos"                                                      "100"
        "wide"                                                      "300"
        "tall"                                                      "300"
        "visible"                                                   "0"
        "bgcolor_override"                                          "0 0 0 0"
        "noitem_textcolor"                                          "117 107 94 255"
        "PaintBackgroundType"                                       "2"
        "paintborder"                                               "1"
        "text_ypos"                                                 "15"
        "text_center"                                               "1"
        "model_hide"                                                "1"
        "resize_to_text"                                            "1"
        "padding_height"                                            "15"

        "attriblabel"
        {
            "font"                                                  "ItemFontAttribLarge"
            "xpos"                                                  "0"
            "ypos"                                                  "0"
            "zpos"                                                  "2"
            "wide"                                                  "140"
            "tall"                                                  "60"
            "autoResize"                                            "0"
            "pinCorner"                                             "0"
            "visible"                                               "1"
            "enabled"                                               "1"
            "labelText"                                             "%attriblist%"
            "textAlignment"                                         "center"
            "fgcolor"                                               "117 107 94 255"
            "centerwrap"                                            "1"
        }
    }

    "passiveattribslabel"
    {
        "ControlName"                                               "CExLabel"
        "fieldName"                                                 "PassiveAttribsLabel"
        "font"                                                      "ItemFontAttribLarge"
        "xpos"                                                      "c-135"
        "ypos"                                                      "120"
        "zpos"                                                      "0"
        "wide"                                                      "270"
        "tall"                                                      "240"
        "autoResize"                                                "0"
        "pinCorner"                                                 "0"
        "visible"                                                   "0"
        "enabled"                                                   "1"
        "labelText"                                                 ""
        "textAlignment"                                             "south"
        "fgcolor"                                                   "255 215 0 255"
        "centerwrap"                                                "1"
    }

    "loadout_preset_panel"
    {
        "ControlName"                                               "CLoadoutPresetPanel"
        "FieldName"                                                 "loadout_preset_panel"
        "zpos"                                                      "20"
        "wide"                                                      "150"
        "tall"                                                      "25"
        "autoResize"                                                "0"
        "pinCorner"                                                 "0"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "tabPosition"                                               "0"
        "paintbackground"                                           "0"
    }

    "presetsexplanation"
    {
        "ControlName"                                               "CExplanationPopup"
        "fieldName"                                                 "PresetsExplanation"
        "xpos"                                                      "0"
        "ypos"                                                      "0"
        "zpos"                                                      "10000"
        "wide"                                                      "250"
        "tall"                                                      "160"
        "visible"                                                   "0"
        "PaintBackgroundType"                                       "2"
        "paintbackground"                                           "0"
        "border"                                                    "MainMenuHighlightBorder"
        "force_close"                                               "1"
        "end_x"                                                     "c-200"
        "end_y"                                                     "120"
        "end_wide"                                                  "250"
        "end_tall"                                                  "160"
        "callout_inparents_x"                                       "c0"
        "callout_inparents_y"                                       "75"
        "next_explanation"                                          ""

        "titlelabel"
        {
            "ControlName"                                           "CExLabel"
            "fieldName"                                             "TitleLabel"
            "font"                                                  "HudFontSmallBold"
            "labelText"                                             "#ItemPresetsExplanation_Title"
            "textAlignment"                                         "north"
            "xpos"                                                  "20"
            "ypos"                                                  "10"
            "wide"                                                  "210"
            "tall"                                                  "30"
            "autoResize"                                            "0"
            "pinCorner"                                             "0"
            "visible"                                               "1"
            "enabled"                                               "1"
            "wrap"                                                  "1"
            "fgcolor_override"                                      "46 43 42 255"
        }

        "textlabel"
        {
            "ControlName"                                           "CExLabel"
            "fieldName"                                             "TextLabel"
            "font"                                                  "HudFontSmall"
            "labelText"                                             "#ClassLoadoutItemPresetsExplanation_Text"
            "textAlignment"                                         "north-west"
            "xpos"                                                  "20"
            "ypos"                                                  "35"
            "wide"                                                  "210"
            "tall"                                                  "200"
            "autoResize"                                            "0"
            "pinCorner"                                             "0"
            "visible"                                               "1"
            "enabled"                                               "1"
            "wrap"                                                  "1"
            "fgcolor_override"                                      "46 43 42 255"
        }

        "closebutton"
        {
            "ControlName"                                           "CExImageButton"
            "fieldName"                                             "CloseButton"
            "xpos"                                                  "230"
            "ypos"                                                  "5"
            "zpos"                                                  "10"
            "wide"                                                  "14"
            "tall"                                                  "14"
            "autoResize"                                            "0"
            "pinCorner"                                             "0"
            "visible"                                               "1"
            "enabled"                                               "1"
            "tabPosition"                                           "0"
            "labeltext"                                             ""
            "font"                                                  "HudFontSmallBold"
            "textAlignment"                                         "center"
            "dulltext"                                              "0"
            "brighttext"                                            "0"
            "default"                                               "0"
            "sound_depressed"                                       "UI/buttonclick.wav"
            "sound_released"                                        "UI/buttonclickrelease.wav"
            "Command"                                               "close"
            "paintbackground"                                       "0"
            "defaultFgColor_override"                               "46 43 42 255"
            "armedFgColor_override"                                 "235 226 202 255"
            "depressedFgColor_override"                             "46 43 42 255"
            "image_drawcolor"                                       "117 107 94 255"
            "image_armedcolor"                                      "200 80 60 255"

            "subimage"
            {
                "ControlName"                                       "ImagePanel"
                "fieldName"                                         "SubImage"
                "xpos"                                              "0"
                "ypos"                                              "0"
                "zpos"                                              "1"
                "wide"                                              "14"
                "tall"                                              "14"
                "visible"                                           "1"
                "enabled"                                           "1"
                "image"                                             "close_button"
                "scaleImage"                                        "1"
            }
        }
    }

    "itemoptionspanel"
    {
        "ControlName"                                               "CLoadoutParticleSlider"
        "fieldname"                                                 "ItemOptionsPanel"
        "xpos"                                                      "0"
        "ypos"                                                      "0"
        "zpos"                                                      "100"
        "wide"                                                      "140"
        "tall"                                                      "75"
        "autoResize"                                                "1"
        "visible"                                                   "0"
        "bgcolor_override"                                          "69 64 63 255"
        "PaintBackgroundType"                                       "2"
    }

    "tauntsexplanation"
    {
        "ControlName"                                               "CExplanationPopup"
        "fieldName"                                                 "TauntsExplanation"
        "xpos"                                                      "0"
        "ypos"                                                      "0"
        "zpos"                                                      "10000"
        "wide"                                                      "250"
        "tall"                                                      "160"
        "visible"                                                   "0"
        "PaintBackgroundType"                                       "2"
        "paintbackground"                                           "0"
        "border"                                                    "MainMenuHighlightBorder"
        "force_close"                                               "1"
        "end_x"                                                     "c-180"
        "end_y"                                                     "150"
        "end_wide"                                                  "250"
        "end_tall"                                                  "140"
        "callout_inparents_x"                                       "c15"
        "callout_inparents_y"                                       "330"
        "next_explanation"                                          ""

        "titlelabel"
        {
            "ControlName"                                           "CExLabel"
            "fieldName"                                             "TitleLabel"
            "font"                                                  "HudFontSmallBold"
            "labelText"                                             "#TauntsExplanation_Title"
            "textAlignment"                                         "north"
            "xpos"                                                  "20"
            "ypos"                                                  "10"
            "wide"                                                  "210"
            "tall"                                                  "30"
            "autoResize"                                            "0"
            "pinCorner"                                             "0"
            "visible"                                               "1"
            "enabled"                                               "1"
            "wrap"                                                  "1"
            "fgcolor_override"                                      "46 43 42 255"
        }

        "textlabel"
        {
            "ControlName"                                           "CExLabel"
            "fieldName"                                             "TextLabel"
            "font"                                                  "HudFontSmall"
            "labelText"                                             "#ClassLoadoutTauntsExplanation_Text"
            "textAlignment"                                         "north-west"
            "xpos"                                                  "20"
            "ypos"                                                  "35"
            "wide"                                                  "210"
            "tall"                                                  "200"
            "autoResize"                                            "0"
            "pinCorner"                                             "0"
            "visible"                                               "1"
            "enabled"                                               "1"
            "wrap"                                                  "1"
            "fgcolor_override"                                      "46 43 42 255"
        }

        "closebutton"
        {
            "ControlName"                                           "CExImageButton"
            "fieldName"                                             "CloseButton"
            "xpos"                                                  "230"
            "ypos"                                                  "5"
            "zpos"                                                  "10"
            "wide"                                                  "14"
            "tall"                                                  "14"
            "autoResize"                                            "0"
            "pinCorner"                                             "0"
            "visible"                                               "1"
            "enabled"                                               "1"
            "tabPosition"                                           "0"
            "labeltext"                                             ""
            "font"                                                  "HudFontSmallBold"
            "textAlignment"                                         "center"
            "dulltext"                                              "0"
            "brighttext"                                            "0"
            "default"                                               "0"
            "sound_depressed"                                       "UI/buttonclick.wav"
            "sound_released"                                        "UI/buttonclickrelease.wav"
            "Command"                                               "close"
            "paintbackground"                                       "0"
            "defaultFgColor_override"                               "46 43 42 255"
            "armedFgColor_override"                                 "235 226 202 255"
            "depressedFgColor_override"                             "46 43 42 255"
            "image_drawcolor"                                       "117 107 94 255"
            "image_armedcolor"                                      "200 80 60 255"

            "subimage"
            {
                "ControlName"                                       "ImagePanel"
                "fieldName"                                         "SubImage"
                "xpos"                                              "0"
                "ypos"                                              "0"
                "zpos"                                              "1"
                "wide"                                              "14"
                "tall"                                              "14"
                "visible"                                           "1"
                "enabled"                                           "1"
                "image"                                             "close_button"
                "scaleImage"                                        "1"
            }
        }
    }
}
