    #base    "../../#users/custom/#customization/_enabled/bh_player_showcontrolpointprogressbar.res"
    #base    "../../#users/custom/resource/ui/controlpointprogressbar.res"
    #base    "../../#customization/_enabled/bh_player_showcontrolpointprogressbar.res"
    #base    "../../_stream/resource/ui/controlpointprogressbar.res"
    #base    "../../_budhud/resource/ui/controlpointprogressbar.res"
    #base    "../../_tf2hud/resource/ui/controlpointprogressbar.res"