"Resource/UI/HudAlert.res"
{
	"HudAlertBG"
	{
		"ControlName"		"CTFImagePanel"
		"fieldName"			"HudAlertBG"
		"xpos"				"6969"
		"ypos"				"6969"
		"zpos"				"-1"
		"wide"				"320"
		"tall"				"150"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"0"
		"enabled"			"0"
		"image"				"../hud/death_panel_blue_bg"
		"scaleImage"		"1"
		"teambg_2"			"../hud/death_panel_red_bg"
		"teambg_3"			"../hud/death_panel_blue_bg"
	}
	"AlertLabel"
	{	
		"ControlName"		"Label"
		"fieldName"			"AlertLabel"
		"font"				"DesignosaurRegular22"
		"xpos"				"80"
		"ypos"				"70"
		"zpos"				"1"
		"wide"				"230"
		"tall"				"55"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"wrap"				"1"
		"labelText"			""
		"textAlignment"		"North"
	}
	"AlertImage"
	{
		"ControlName"		"CTFImagePanel"
		"fieldName"			"AlertImage"
		"xpos"				"25"
		"ypos"				"53"
		"zpos"				"1"
		"wide"				"50"
		"tall"				"50"
		"autoResize"		"0"
		"pinCorner"			"0"
		"visible"			"1"
		"enabled"			"1"
		"image"				"../hud/ico_teambalance"
		"scaleImage"		"1"
	}
}
