"Resource/UI/HudAmmoWeapons.res"
{
        "HudWeaponAmmoBG"
        {
                "ControlName"   		"CTFImagePanel"
                "fieldName"             "HudWeaponAmmoBG"
                "xpos"                  "6969"
                "ypos"                  "6969"
                "zpos"                  "1"
                "wide"                  "90"
                "tall"                  "45"
                "visible"               "0"
                "enabled"               "1"
                "image"                 "../hud/ammo_blue_bg"
                "scaleImage"    "1"    
                "teambg_2"              "../hud/ammo_red_bg"
                "teambg_2_lodef"        "../hud/ammo_red_bg_lodef"
                "teambg_3"              "../hud/ammo_blue_bg"
                "teambg_3_lodef"        "../hud/ammo_blue_bg_lodef"                    
        }
        "HudWeaponLowAmmoImage"
        {
                "ControlName"   		"ImagePanel"
                "fieldName"             "HudWeaponLowAmmoImage"
                "xpos"                  "6969"
                "ypos"                  "6969"
                "zpos"                  "0"
                "wide"                  "90"
                "tall"                  "45"
                "visible"               "0"
                "enabled"               "0"
                "image"                 "../hud/ammo_red_bg"
                "scaleImage"    "1"    
                "teambg_2"              "../hud/ammo_red_bg"
                "teambg_2_lodef"        "../hud/ammo_red_bg_lodef"
                "teambg_3"              "../hud/ammo_blue_bg"
                "teambg_3_lodef"        "../hud/ammo_blue_bg_lodef"                    
        }
        "AmmoInClip"
        {
                "ControlName"   		"CExLabel"
                "fieldName"             "AmmoInClip"
                "font"                  "DesignosaurRegular48"
                "fgcolor"               "bh_white"
                "xpos"                  "0"
                "ypos"                  "0"
                "zpos"                  "5"
                "wide"                  "200"
                "tall"                  "100"
                "visible"               "0"
                "enabled"               "1"
                "textAlignment" 		"center" 
                "labelText"             "%Ammo%"
               
        }              
        "AmmoInClipShadow"
        {
                "ControlName"   		"CExLabel"
                "fieldName"             "AmmoInClipShadow"
                "font"                  "DesignosaurRegular48"
                "fgcolor"               "bh_black"
                "xpos"                  "2"
                "ypos"                  "2"
                "zpos"                  "5"
                "wide"                  "200"
                "tall"                  "100"
                "visible"               "0"
                "enabled"               "1"
                "textAlignment" 		"center" 
                "labelText"             "%Ammo%"
               
        }                                              
        "AmmoInReserve"
        {
                "ControlName"   		"CExLabel"
                "fieldName"             "AmmoInReserve"
                "font"                  "DesignosaurRegular24"
                "fgcolor"               "bh_white"
                "xpos"                  "125"
                "ypos"                  "-8"
                "zpos"                  "7"
                "wide"                  "200"
                "tall"                  "100"
                "visible"               "0"
                "enabled"               "1"
                "textAlignment" "west"         
                "labelText"             "%AmmoInReserve%"
        }              
        "AmmoInReserveShadow"
        {
                "ControlName"   		"CExLabel"
                "fieldName"             "AmmoInReserveShadow"
                "font"                  "DesignosaurRegular24"
                "fgcolor"               "bh_black"
                "xpos"                  "126"
                "ypos"                  "-7"
                "zpos"                  "7"
                "wide"                  "200"
                "tall"                  "100"
                "visible"               "0"
                "enabled"               "1"
                "textAlignment" "west"         
                "labelText"             "%AmmoInReserve%"
        }                                                                      
        "AmmoNoClip"
        {
                "ControlName"   		"CExLabel"
                "fieldName"             "AmmoNoClip"
                "font"                  "DesignosaurRegular48"
                "fgcolor"               "bh_white"
                "xpos"                  "0"
                "ypos"                  "0"
                "zpos"                  "5"
                "wide"                  "200"
                "tall"                  "100"
                "visible"               "0"
                "enabled"               "1"
                "textAlignment" "center"               
                "labelText"             "%Ammo%"
               
        }      
        "AmmoNoClipShadow"
        {
                "ControlName"   		"CExLabel"
                "fieldName"             "AmmoNoClipShadow"
                "font"                  "DesignosaurRegular48"
                "fgcolor"               "bh_black"
                "xpos"                  "2"
                "ypos"                  "2"
                "zpos"                  "5"
                "wide"                  "200"
                "tall"                  "100"
                "visible"               "0"
                "enabled"               "1"
                "textAlignment" "center"               
                "labelText"             "%Ammo%"
               
        }

}