	#base	"..\..\#users\custom\resource\ui\huddamageaccount.res"
	#base	"..\..\#users\jayhyunpae\resource\ui\huddamageaccount.res"
	#base	"..\..\_stream\resource\ui\huddamageaccount.res"
	#base	"..\..\_budhud\resource\ui\huddamageaccount.res"
	#base	"..\..\_tf2hud\resource\ui\huddamageaccount.res"