	#base	"../../#users/custom/resource/ui/huddemomancharge.res"
	#base	"../../#users/ly_dee/resource/ui/huddemomancharge.res"
	#base	"../../#users/jayhyunpae/resource/ui/huddemomancharge.res"
	#base	"../../_stream/resource/ui/huddemomancharge.res"
	#base	"../../_budhud/resource/ui/huddemomancharge.res"
	#base	"../../_tf2hud/resource/ui/huddemomancharge.res"