	#base	"..\..\#users\custom\resource\ui\huditemeffectmeter_particlecannon.res"
	#base	"..\..\#users\ly_dee\resource\ui\huditemeffectmeter_particlecannon.res"
	#base	"..\..\#users\jayhyunpae\resource\ui\huditemeffectmeter_particlecannon.res"
	#base	"..\..\_stream\resource\ui\huditemeffectmeter_particlecannon.res"
	#base	"..\..\_budhud\resource\ui\huditemeffectmeter_particlecannon.res"
	#base	"..\..\_tf2hud\resource\ui\huditemeffectmeter_particlecannon.res"