    #base    "../../#users/custom/resource/ui/huditemeffectmeter_killstreak.res"
    #base    "../../#users/jayhyunpae/resource/ui/huditemeffectmeter_killstreak.res"
    #base    "../../#users/zenith/resource/ui/huditemeffectmeter_killstreak.res"
    #base    "../../_stream/resource/ui/huditemeffectmeter_killstreak.res"
    #base    "../../_budhud/resource/ui/huditemeffectmeter_killstreak.res"
    #base    "../../_tf2hud/resource/ui/huditemeffectmeter_killstreak.res"