    #base    "../../#users/custom/resource/ui/huditemeffectmeter_sapper.res"
    #base    "../../#users/jayhyunpae/resource/ui/huditemeffectmeter_sapper.res"
    #base    "../../#customization/_enabled/bh_player_uicentered/huditemeffectmeter_sapper.res"
    #base    "../../#customization/_enabled/bh_player_uilowered/huditemeffectmeter_sapper.res"
    #base    "../../#customization/_enabled/bh_player_uireduced/huditemeffectmeter_sapper.res"
    #base    "../../_stream/resource/ui/huditemeffectmeter_sapper.res"
    #base    "../../_budhud/resource/ui/huditemeffectmeter_sapper.res"
    #base    "../../_tf2hud/resource/ui/huditemeffectmeter_sapper.res"