    #base    "../../#users/custom/resource/ui/huditemeffectmeter_spy.res"
    #base    "../../#users/jayhyunpae/resource/ui/huditemeffectmeter_spy.res"
    #base    "../../_stream/resource/ui/huditemeffectmeter_spy.res"
    #base    "../../_budhud/resource/ui/huditemeffectmeter_spy.res"
    #base    "../../_tf2hud/resource/ui/huditemeffectmeter_spy.res"