	#base	"..\..\#users\ly_dee\resource\ui\hudmediccharge.res"
	#base	"..\..\#customization\_enabled\bh_uber_longchargemeter.res"
	#base	"..\..\#customization\_enabled\bh_uber_percentagenearcrosshair.res"
	#base	"..\..\#customization\_enabled\bh_uber_largeuberpercentage.res"
	#base	"..\..\#users\custom\resource\ui\hudmediccharge.res"
	#base	"..\..\_stream\resource\ui\hudmediccharge.res"
	#base	"..\..\_budhud\resource\ui\hudmediccharge.res"
	#base	"..\..\_tf2hud\resource\ui\hudmediccharge.res"