    #base    "../../#users/custom/resource/ui/hudmatchstatus.res"
    #base    "../../#users/custom/#customization/_enabled/bh_matchstatus_6v6.res"
    #base    "../../#customization/_enabled/bh_matchstatus_6v6.res"
    #base    "../../_stream/resource/ui/hudmatchstatus.res"
    #base    "../../_budhud/resource/ui/hudmatchstatus.res"
    #base    "../../_tf2hud/resource/ui/hudmatchstatus.res"