	#base	"..\..\#users\toth\resource\ui\hudplayerclass.res"
	#base	"..\..\#users\dane\resource\ui\hudplayerclass.res"
	#base	"..\..\#customization\_enabled\bh_hudplayerclass_hideclass.res"
	#base	"..\..\#customization\_enabled\bh_crosshairs.res"
	#base	"..\..\_stream\resource\ui\hudplayerclass.res"
	#base	"..\..\_budhud\resource\ui\hudplayerclass.res"
	#base	"..\..\_tf2hud\resource\ui\hudplayerclass.res"