#base "../../../#users/custom/resource/ui/hudplayerhealth.res"
#base "../../../#users/truktruk/resource/ui/hudplayerhealth.res"
#base "../../../#users/ly_dee/resource/ui/hudplayerhealth.res"
#base "../../../#users/jayhyunpae/resource/ui/hudplayerhealth.res"
#base "../../../#customization/_enabled/bh_player_largehealth.res"
#base "../../../#customization/_enabled/bh_player_healthcross_inset.res"
#base "../../../#customization/_enabled/bh_player_healthcross.res"
#base "../../../#customization/_enabled/bh_player_m0re_healthcross_inset.res"
#base "../../../#customization/_enabled/bh_player_m0re_healthcross.res"
#base "../../../#customization/_enabled/bh_player_healthbox.res"
#base "../../../_stream/resource/ui/hudplayerhealth.res"

"Resource/UI/HudPlayerHealth.res"
{

    "playerstatushealthimagebg"
    {
        "ypos"                                                      "r-6969"
        "visible"                                                   "0"
        "enabled"                                                   "0"
        "ControlName"                                               "ImagePanel"
        "fieldName"                                                 "PlayerStatusHealthImageBG"
        "xpos"                                                      "73"
        "xpos$_disabled_"                                           "58"
        "zpos"                                                      "3"
        "wide"                                                      "55"
        "tall"                                                      "55"
        "image"                                                     "../hud/health_bg"
        "scaleImage"                                                "1"
    }

    "playerstatushealthimage"
    {
        "ypos"                                                      "r-6969"
        "visible"                                                   "0"
        "enabled"                                                   "0"
        "ControlName"                                               "ImagePanel"
        "fieldName"                                                 "PlayerStatusHealthImage"
        "xpos"                                                      "75"
        "xpos$_disabled_"                                           "60"
        "zpos"                                                      "4"
        "wide"                                                      "51"
        "tall"                                                      "51"
        "scaleImage"                                                "1"
    }

    "playerstatusmaxhealthvalue"
    {
        "ypos"                                                      "r-6969"
        "visible"                                                   "0"
        "enabled"                                                   "0"
        "ControlName"                                               "CExLabel"
        "fieldName"                                                 "PlayerStatusMaxHealthValue"
        "xpos"                                                      "76"
        "xpos$_disabled_"                                           "61"
        "zpos"                                                      "6"
        "wide"                                                      "50"
        "tall"                                                      "18"
        "labelText"                                                 "%MaxHealth%"
        "textAlignment"                                             "center"
        "font"                                                      "DefaultSmall"
        "fgcolor"                                                   "TanDark"
    }

    "hudplayerhealth"
    {
        "xpos"                                                      "c-300"
        "ypos"                                                      "c41"
        "wide"                                                      "250"
        "tall"                                                      "150"
        "ControlName"                                               "EditablePanel"
        "fieldName"                                                 "HudPlayerHealth"
        "xpos$_disabled_"                                           "-5"
        "ypos$_disabled_"                                           "r88"
        "zpos"                                                      "2"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "HealthBonusPosAdj"                                         "35"
        "HealthDeathWarning"                                        "0.49"
        "HealthDeathWarningColor"                                   "HUDDeathWarning"
    }

    "bh_playerstatuspin"
    {
        "ControlName"                                               "Label"
        "fieldName"                                                 "bh_PlayerStatusPin"
        "xpos"                                                      "196"
        "ypos"                                                      "23"
        "zpos"                                                      "0"
        "wide"                                                      "10"
        "tall"                                                      "0"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "bgcolor_override"                                          "0 0 0 0"
    }

    "bh_healthbg"
    {
        "ControlName"                                               "CExLabel"
        "fieldName"                                                 "bh_HealthBG"
        "xpos"                                                      "85"
        "ypos"                                                      "55"
        "zpos"                                                      "-6969"
        "wide"                                                      "81"
        "tall"                                                      "42"
        "autoResize"                                                "0"
        "pinCorner"                                                 "0"
        "labeltext"                                                 ""
        "visible"                                                   "0"
        "enabled"                                                   "0"
        "bgcolor_override"                                          "bh_HealthBox_Base"
    }

    "playerstatushealthvalue"
    {
        "xpos"                                                      "0"
        "ypos"                                                      "0"
        "zpos"                                                      "6"
        "wide"                                                      "250"
        "tall"                                                      "150"
        "font"                                                      "bh_Font_HealthAmmoMain"
        "fgcolor"                                                   "bh_Health_Main"
        "textAlignment"                                             "center"
        "ControlName"                                               "CExLabel"
        "fieldName"                                                 "PlayerStatusHealthValue"
        "xpos$_disabled_"                                           "61"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "labelText"                                                 "%Health%"
    }

    "playerstatushealthvalueshadow"
    {
        "pin_to_sibling"                                            "PlayerStatusHealthValue"
        "pin_corner_to_sibling"                                     "PIN_TOPLEFT"
        "pin_to_sibling_corner"                                     "0"
        "ControlName"                                               "CExLabel"
        "fieldName"                                                 "PlayerStatusHealthValueShadow"
        "xpos"                                                      "-1"
        "ypos"                                                      "-1"
        "zpos"                                                      "6"
        "wide"                                                      "250"
        "tall"                                                      "150"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "labelText"                                                 "%Health%"
        "textAlignment"                                             "center"
        "font"                                                      "bh_Font_HealthAmmoMain"
        "fgcolor"                                                   "bh_Shadow"
    }

    "playerstatushealthbonusimage"
    {
        "xpos"                                                      "108"
        "ypos"                                                      "59"
        "zpos"                                                      "-10"
        "wide"                                                      "34"
        "tall"                                                      "34"
        "ControlName"                                               "ImagePanel"
        "fieldName"                                                 "PlayerStatusHealthBonusImage"
        "xpos$_disabled_"                                           "65"
        "ypos$_disabled_"                                           "40"
        "wide$_disabled_"                                           "40"
        "tall$_disabled_"                                           "40"
        "visible"                                                   "0"
        "enabled"                                                   "1"
        "image"                                                     "../hud/health_over_bg"
        "scaleImage"                                                "1"
    }

    "playerstatusbleedimage"
    {
        "pin_to_sibling"                                            "bh_PlayerStatusPin"
        "pin_corner_to_sibling"                                     "PIN_TOPLEFT"
        "pin_to_sibling_corner"                                     "0"
        "ControlName"                                               "ImagePanel"
        "fieldName"                                                 "PlayerStatusBleedImage"
        "xpos"                                                      "85"
        "xpos$_disabled_"                                           "70"
        "ypos"                                                      "0"
        "zpos"                                                      "7"
        "wide"                                                      "32"
        "tall"                                                      "32"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "scaleImage"                                                "1"
        "image"                                                     "../vgui/bleed_drop"
        "fgcolor"                                                   "TanDark"
    }

    "playerstatushookbleedimage"
    {
        "pin_to_sibling"                                            "bh_PlayerStatusPin"
        "pin_corner_to_sibling"                                     "PIN_TOPLEFT"
        "pin_to_sibling_corner"                                     "0"
        "ControlName"                                               "ImagePanel"
        "fieldName"                                                 "PlayerStatusHookBleedImage"
        "xpos"                                                      "85"
        "xpos$_disabled_"                                           "70"
        "ypos"                                                      "0"
        "zpos"                                                      "8"
        "wide"                                                      "32"
        "tall"                                                      "32"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "scaleImage"                                                "1"
        "image"                                                     "../vgui/bleed_drop_grapple"
        "fgcolor"                                                   "TanDark"
    }

    "playerstatusmilkimage"
    {
        "pin_to_sibling"                                            "bh_PlayerStatusPin"
        "pin_corner_to_sibling"                                     "PIN_TOPLEFT"
        "pin_to_sibling_corner"                                     "0"
        "ControlName"                                               "ImagePanel"
        "fieldName"                                                 "PlayerStatusMilkImage"
        "xpos"                                                      "117"
        "xpos$_disabled_"                                           "102"
        "ypos"                                                      "0"
        "zpos"                                                      "7"
        "wide"                                                      "32"
        "tall"                                                      "32"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "scaleImage"                                                "1"
        "image"                                                     "../vgui/bleed_drop"
        "fgcolor"                                                   "TanDark"
    }

    "playerstatusgasimage"
    {
        "pin_to_sibling"                                            "bh_PlayerStatusPin"
        "pin_corner_to_sibling"                                     "PIN_TOPLEFT"
        "pin_to_sibling_corner"                                     "0"
        "ControlName"                                               "ImagePanel"
        "fieldName"                                                 "PlayerStatusGasImage"
        "xpos"                                                      "117"
        "xpos$_disabled_"                                           "102"
        "ypos"                                                      "0"
        "zpos"                                                      "7"
        "wide"                                                      "32"
        "tall"                                                      "32"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "scaleImage"                                                "1"
        "image"                                                     "../vgui/covered_in_gas"
        "fgcolor"                                                   "TanDark"
    }

    "playerstatusmarkedfordeathimage"
    {
        "pin_to_sibling"                                            "bh_PlayerStatusPin"
        "pin_corner_to_sibling"                                     "PIN_TOPLEFT"
        "pin_to_sibling_corner"                                     "0"
        "ControlName"                                               "ImagePanel"
        "fieldName"                                                 "PlayerStatusMarkedForDeathImage"
        "xpos"                                                      "85"
        "xpos$_disabled_"                                           "70"
        "ypos"                                                      "0"
        "zpos"                                                      "7"
        "wide"                                                      "32"
        "tall"                                                      "32"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "scaleImage"                                                "1"
        "image"                                                     "../vgui/marked_for_death"
        "fgcolor"                                                   "TanDark"
    }

    "playerstatusmarkedfordeathsilentimage"
    {
        "pin_to_sibling"                                            "bh_PlayerStatusPin"
        "pin_corner_to_sibling"                                     "PIN_TOPLEFT"
        "pin_to_sibling_corner"                                     "0"
        "ControlName"                                               "ImagePanel"
        "fieldName"                                                 "PlayerStatusMarkedForDeathSilentImage"
        "xpos"                                                      "85"
        "xpos$_disabled_"                                           "70"
        "ypos"                                                      "0"
        "zpos"                                                      "7"
        "wide"                                                      "31"
        "tall"                                                      "31"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "scaleImage"                                                "1"
        "image"                                                     "../vgui/marked_for_death"
        "fgcolor"                                                   "TanDark"
    }

    "playerstatus_medicuberbulletresistimage"
    {
        "pin_to_sibling"                                            "bh_PlayerStatusPin"
        "pin_corner_to_sibling"                                     "PIN_TOPLEFT"
        "pin_to_sibling_corner"                                     "0"
        "ControlName"                                               "ImagePanel"
        "fieldName"                                                 "PlayerStatus_MedicUberBulletResistImage"
        "xpos"                                                      "85"
        "xpos$_disabled_"                                           "70"
        "ypos"                                                      "0"
        "zpos"                                                      "7"
        "wide"                                                      "31"
        "tall"                                                      "31"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "scaleImage"                                                "1"
        "image"                                                     "../HUD/defense_buff_bullet_blue"
        "fgcolor"                                                   "TanDark"
    }

    "playerstatus_medicuberblastresistimage"
    {
        "pin_to_sibling"                                            "bh_PlayerStatusPin"
        "pin_corner_to_sibling"                                     "PIN_TOPLEFT"
        "pin_to_sibling_corner"                                     "0"
        "ControlName"                                               "ImagePanel"
        "fieldName"                                                 "PlayerStatus_MedicUberBlastResistImage"
        "xpos"                                                      "85"
        "xpos$_disabled_"                                           "70"
        "ypos"                                                      "0"
        "zpos"                                                      "7"
        "wide"                                                      "31"
        "tall"                                                      "31"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "scaleImage"                                                "1"
        "image"                                                     "../HUD/defense_buff_explosion_blue"
        "fgcolor"                                                   "TanDark"
    }

    "playerstatus_medicuberfireresistimage"
    {
        "pin_to_sibling"                                            "bh_PlayerStatusPin"
        "pin_corner_to_sibling"                                     "PIN_TOPLEFT"
        "pin_to_sibling_corner"                                     "0"
        "ControlName"                                               "ImagePanel"
        "fieldName"                                                 "PlayerStatus_MedicUberFireResistImage"
        "xpos"                                                      "85"
        "xpos$_disabled_"                                           "70"
        "ypos"                                                      "0"
        "zpos"                                                      "7"
        "wide"                                                      "31"
        "tall"                                                      "31"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "scaleImage"                                                "1"
        "image"                                                     "../HUD/defense_buff_fire_blue"
        "fgcolor"                                                   "TanDark"
    }

    "playerstatus_medicsmallbulletresistimage"
    {
        "pin_to_sibling"                                            "bh_PlayerStatusPin"
        "pin_corner_to_sibling"                                     "PIN_TOPLEFT"
        "pin_to_sibling_corner"                                     "0"
        "ControlName"                                               "ImagePanel"
        "fieldName"                                                 "PlayerStatus_MedicSmallBulletResistImage"
        "xpos"                                                      "85"
        "xpos$_disabled_"                                           "70"
        "ypos"                                                      "0"
        "zpos"                                                      "7"
        "wide"                                                      "31"
        "tall"                                                      "31"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "scaleImage"                                                "1"
        "image"                                                     "../HUD/defense_buff_bullet_blue"
        "fgcolor"                                                   "TanDark"
    }

    "playerstatus_medicsmallblastresistimage"
    {
        "pin_to_sibling"                                            "bh_PlayerStatusPin"
        "pin_corner_to_sibling"                                     "PIN_TOPLEFT"
        "pin_to_sibling_corner"                                     "0"
        "ControlName"                                               "ImagePanel"
        "fieldName"                                                 "PlayerStatus_MedicSmallBlastResistImage"
        "xpos"                                                      "85"
        "xpos$_disabled_"                                           "70"
        "ypos"                                                      "0"
        "zpos"                                                      "7"
        "wide"                                                      "31"
        "tall"                                                      "31"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "scaleImage"                                                "1"
        "image"                                                     "../HUD/defense_buff_explosion_blue"
        "fgcolor"                                                   "TanDark"
    }

    "playerstatus_medicsmallfireresistimage"
    {
        "pin_to_sibling"                                            "bh_PlayerStatusPin"
        "pin_corner_to_sibling"                                     "PIN_TOPLEFT"
        "pin_to_sibling_corner"                                     "0"
        "ControlName"                                               "ImagePanel"
        "fieldName"                                                 "PlayerStatus_MedicSmallFireResistImage"
        "xpos"                                                      "85"
        "xpos$_disabled_"                                           "70"
        "ypos"                                                      "0"
        "zpos"                                                      "7"
        "wide"                                                      "31"
        "tall"                                                      "31"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "scaleImage"                                                "1"
        "image"                                                     "../HUD/defense_buff_fire_blue"
        "fgcolor"                                                   "TanDark"
    }

    "playerstatus_wheelofdoom"
    {
        "xpos"                                                      "40"
        "ypos"                                                      "60"
        "ControlName"                                               "ImagePanel"
        "fieldName"                                                 "PlayerStatus_WheelOfDoom"
        "xpos$_disabled_"                                           "145"
        "ypos$_disabled_"                                           "55"
        "zpos"                                                      "7"
        "wide"                                                      "32"
        "tall"                                                      "32"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "scaleImage"                                                "1"
        "image"                                                     "../signs/death_wheel_whammy"
        "fgcolor"                                                   "TanDark"
    }

    "playerstatus_soldieroffensebuff"
    {
        "pin_to_sibling"                                            "bh_PlayerStatusPin"
        "pin_corner_to_sibling"                                     "PIN_TOPLEFT"
        "pin_to_sibling_corner"                                     "0"
        "ControlName"                                               "ImagePanel"
        "fieldName"                                                 "PlayerStatus_SoldierOffenseBuff"
        "xpos"                                                      "85"
        "xpos$_disabled_"                                           "70"
        "ypos"                                                      "0"
        "zpos"                                                      "7"
        "wide"                                                      "31"
        "tall"                                                      "31"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "scaleImage"                                                "1"
        "image"                                                     "../HUD/defense_buff_bullet_blue"
        "fgcolor"                                                   "TanDark"
    }

    "playerstatus_soldierdefensebuff"
    {
        "pin_to_sibling"                                            "bh_PlayerStatusPin"
        "pin_corner_to_sibling"                                     "PIN_TOPLEFT"
        "pin_to_sibling_corner"                                     "0"
        "ControlName"                                               "ImagePanel"
        "fieldName"                                                 "PlayerStatus_SoldierDefenseBuff"
        "xpos"                                                      "85"
        "xpos$_disabled_"                                           "70"
        "ypos"                                                      "0"
        "zpos"                                                      "7"
        "wide"                                                      "31"
        "tall"                                                      "31"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "scaleImage"                                                "1"
        "image"                                                     "../HUD/defense_buff_bullet_blue"
        "fgcolor"                                                   "TanDark"
    }

    "playerstatus_soldierhealonhitbuff"
    {
        "pin_to_sibling"                                            "bh_PlayerStatusPin"
        "pin_corner_to_sibling"                                     "PIN_TOPLEFT"
        "pin_to_sibling_corner"                                     "0"
        "ControlName"                                               "ImagePanel"
        "fieldName"                                                 "PlayerStatus_SoldierHealOnHitBuff"
        "xpos"                                                      "85"
        "xpos$_disabled_"                                           "70"
        "ypos"                                                      "0"
        "zpos"                                                      "7"
        "wide"                                                      "31"
        "tall"                                                      "31"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "scaleImage"                                                "1"
        "image"                                                     "../HUD/defense_buff_bullet_blue"
        "fgcolor"                                                   "TanDark"
    }

    "playerstatus_spymarked"
    {
        "pin_to_sibling"                                            "bh_PlayerStatusPin"
        "pin_corner_to_sibling"                                     "PIN_TOPLEFT"
        "pin_to_sibling_corner"                                     "0"
        "ControlName"                                               "ImagePanel"
        "fieldName"                                                 "PlayerStatus_SpyMarked"
        "xpos"                                                      "115"
        "xpos$_disabled_"                                           "70"
        "ypos"                                                      "0"
        "zpos"                                                      "7"
        "wide"                                                      "31"
        "tall"                                                      "31"
        "visible"                                                   "0"
        "enabled"                                                   "1"
        "scaleImage"                                                "1"
        "image"                                                     ""
        "fgcolor"                                                   "TanDark"
    }

    "playerstatus_parachute"
    {
        "pin_to_sibling"                                            "bh_PlayerStatusPin"
        "pin_corner_to_sibling"                                     "PIN_TOPLEFT"
        "pin_to_sibling_corner"                                     "0"
        "ControlName"                                               "ImagePanel"
        "fieldName"                                                 "PlayerStatus_Parachute"
        "xpos"                                                      "85"
        "xpos$_disabled_"                                           "70"
        "ypos"                                                      "0"
        "zpos"                                                      "7"
        "wide"                                                      "31"
        "tall"                                                      "31"
        "visible"                                                   "0"
        "enabled"                                                   "1"
        "scaleImage"                                                "1"
        "image"                                                     ""
        "fgcolor"                                                   "TanDark"
    }

    "playerstatus_runestrength"
    {
        "pin_to_sibling"                                            "bh_PlayerStatusPin"
        "pin_corner_to_sibling"                                     "PIN_TOPLEFT"
        "pin_to_sibling_corner"                                     "0"
        "ControlName"                                               "ImagePanel"
        "fieldName"                                                 "PlayerStatus_RuneStrength"
        "xpos"                                                      "85"
        "xpos$_disabled_"                                           "70"
        "ypos"                                                      "0"
        "zpos"                                                      "7"
        "wide"                                                      "31"
        "tall"                                                      "31"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "scaleImage"                                                "1"
        "image"                                                     "../Effects/powerup_strength_hud"
        "fgcolor"                                                   "TanDark"
    }

    "playerstatus_runehaste"
    {
        "pin_to_sibling"                                            "bh_PlayerStatusPin"
        "pin_corner_to_sibling"                                     "PIN_TOPLEFT"
        "pin_to_sibling_corner"                                     "0"
        "ControlName"                                               "ImagePanel"
        "fieldName"                                                 "PlayerStatus_RuneHaste"
        "xpos"                                                      "85"
        "xpos$_disabled_"                                           "70"
        "ypos"                                                      "0"
        "zpos"                                                      "7"
        "wide"                                                      "31"
        "tall"                                                      "31"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "scaleImage"                                                "1"
        "image"                                                     "../Effects/powerup_haste_hud"
        "fgcolor"                                                   "TanDark"
    }

    "playerstatus_runeregen"
    {
        "pin_to_sibling"                                            "bh_PlayerStatusPin"
        "pin_corner_to_sibling"                                     "PIN_TOPLEFT"
        "pin_to_sibling_corner"                                     "0"
        "ControlName"                                               "ImagePanel"
        "fieldName"                                                 "PlayerStatus_RuneRegen"
        "xpos"                                                      "85"
        "xpos$_disabled_"                                           "70"
        "ypos"                                                      "0"
        "zpos"                                                      "7"
        "wide"                                                      "31"
        "tall"                                                      "31"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "scaleImage"                                                "1"
        "image"                                                     "../Effects/powerup_regen_hud"
        "fgcolor"                                                   "TanDark"
    }

    "playerstatus_runeresist"
    {
        "pin_to_sibling"                                            "bh_PlayerStatusPin"
        "pin_corner_to_sibling"                                     "PIN_TOPLEFT"
        "pin_to_sibling_corner"                                     "0"
        "ControlName"                                               "ImagePanel"
        "fieldName"                                                 "PlayerStatus_RuneResist"
        "xpos"                                                      "85"
        "xpos$_disabled_"                                           "70"
        "ypos"                                                      "0"
        "zpos"                                                      "7"
        "wide"                                                      "31"
        "tall"                                                      "31"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "scaleImage"                                                "1"
        "image"                                                     "../Effects/powerup_resist_hud"
        "fgcolor"                                                   "TanDark"
    }

    "playerstatus_runevampire"
    {
        "pin_to_sibling"                                            "bh_PlayerStatusPin"
        "pin_corner_to_sibling"                                     "PIN_TOPLEFT"
        "pin_to_sibling_corner"                                     "0"
        "ControlName"                                               "ImagePanel"
        "fieldName"                                                 "PlayerStatus_RuneVampire"
        "xpos"                                                      "85"
        "xpos$_disabled_"                                           "70"
        "ypos"                                                      "0"
        "zpos"                                                      "7"
        "wide"                                                      "31"
        "tall"                                                      "31"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "scaleImage"                                                "1"
        "image"                                                     "../Effects/powerup_vampire_hud"
        "fgcolor"                                                   "TanDark"
    }

    "playerstatus_runereflect"
    {
        "pin_to_sibling"                                            "bh_PlayerStatusPin"
        "pin_corner_to_sibling"                                     "PIN_TOPLEFT"
        "pin_to_sibling_corner"                                     "0"
        "ControlName"                                               "ImagePanel"
        "fieldName"                                                 "PlayerStatus_RuneReflect"
        "xpos"                                                      "85"
        "xpos$_disabled_"                                           "70"
        "ypos"                                                      "0"
        "zpos"                                                      "7"
        "wide"                                                      "31"
        "tall"                                                      "31"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "scaleImage"                                                "1"
        "image"                                                     "../Effects/powerup_reflect_hud"
        "fgcolor"                                                   "TanDark"
    }

    "playerstatus_runeprecision"
    {
        "pin_to_sibling"                                            "bh_PlayerStatusPin"
        "pin_corner_to_sibling"                                     "PIN_TOPLEFT"
        "pin_to_sibling_corner"                                     "0"
        "ControlName"                                               "ImagePanel"
        "fieldName"                                                 "PlayerStatus_RunePrecision"
        "xpos"                                                      "85"
        "xpos$_disabled_"                                           "70"
        "ypos"                                                      "0"
        "zpos"                                                      "7"
        "wide"                                                      "31"
        "tall"                                                      "31"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "scaleImage"                                                "1"
        "image"                                                     "../Effects/powerup_precision_hud"
        "fgcolor"                                                   "TanDark"
    }

    "playerstatus_runeagility"
    {
        "pin_to_sibling"                                            "bh_PlayerStatusPin"
        "pin_corner_to_sibling"                                     "PIN_TOPLEFT"
        "pin_to_sibling_corner"                                     "0"
        "ControlName"                                               "ImagePanel"
        "fieldName"                                                 "PlayerStatus_RuneAgility"
        "xpos"                                                      "85"
        "xpos$_disabled_"                                           "70"
        "ypos"                                                      "0"
        "zpos"                                                      "7"
        "wide"                                                      "31"
        "tall"                                                      "31"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "scaleImage"                                                "1"
        "image"                                                     "../Effects/powerup_agility_hud"
        "fgcolor"                                                   "TanDark"
    }

    "playerstatus_runeknockout"
    {
        "pin_to_sibling"                                            "bh_PlayerStatusPin"
        "pin_corner_to_sibling"                                     "PIN_TOPLEFT"
        "pin_to_sibling_corner"                                     "0"
        "ControlName"                                               "ImagePanel"
        "fieldName"                                                 "PlayerStatus_RuneKnockout"
        "xpos"                                                      "85"
        "xpos$_disabled_"                                           "70"
        "ypos"                                                      "0"
        "zpos"                                                      "7"
        "wide"                                                      "31"
        "tall"                                                      "31"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "scaleImage"                                                "1"
        "image"                                                     "../Effects/powerup_knockout_hud"
        "fgcolor"                                                   "TanDark"
    }

    "playerstatus_runeking"
    {
        "pin_to_sibling"                                            "bh_PlayerStatusPin"
        "pin_corner_to_sibling"                                     "PIN_TOPLEFT"
        "pin_to_sibling_corner"                                     "0"
        "ControlName"                                               "ImagePanel"
        "fieldName"                                                 "PlayerStatus_RuneKing"
        "xpos"                                                      "85"
        "xpos$_disabled_"                                           "70"
        "ypos"                                                      "0"
        "zpos"                                                      "7"
        "wide"                                                      "31"
        "tall"                                                      "31"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "scaleImage"                                                "1"
        "image"                                                     "../Effects/powerup_king_hud"
        "fgcolor"                                                   "TanDark"
    }

    "playerstatus_runeplague"
    {
        "pin_to_sibling"                                            "bh_PlayerStatusPin"
        "pin_corner_to_sibling"                                     "PIN_TOPLEFT"
        "pin_to_sibling_corner"                                     "0"
        "ControlName"                                               "ImagePanel"
        "fieldName"                                                 "PlayerStatus_RunePlague"
        "xpos"                                                      "85"
        "xpos$_disabled_"                                           "70"
        "ypos"                                                      "0"
        "zpos"                                                      "7"
        "wide"                                                      "31"
        "tall"                                                      "31"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "scaleImage"                                                "1"
        "image"                                                     "../Effects/powerup_plague_hud"
        "fgcolor"                                                   "TanDark"
    }

    "playerstatus_runesupernova"
    {
        "pin_to_sibling"                                            "bh_PlayerStatusPin"
        "pin_corner_to_sibling"                                     "PIN_TOPLEFT"
        "pin_to_sibling_corner"                                     "0"
        "ControlName"                                               "ImagePanel"
        "fieldName"                                                 "PlayerStatus_RuneSupernova"
        "xpos"                                                      "85"
        "xpos$_disabled_"                                           "70"
        "ypos"                                                      "0"
        "zpos"                                                      "7"
        "wide"                                                      "31"
        "tall"                                                      "31"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "scaleImage"                                                "1"
        "image"                                                     "../Effects/powerup_supernova_hud"
        "fgcolor"                                                   "TanDark"
    }

    "playerstatusslowed"
    {
        "pin_to_sibling"                                            "bh_PlayerStatusPin"
        "pin_corner_to_sibling"                                     "PIN_TOPLEFT"
        "pin_to_sibling_corner"                                     "0"
        "ControlName"                                               "ImagePanel"
        "fieldName"                                                 "PlayerStatusSlowed"
        "xpos"                                                      "85"
        "xpos$_disabled_"                                           "70"
        "ypos"                                                      "0"
        "zpos"                                                      "7"
        "wide"                                                      "32"
        "tall"                                                      "32"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "scaleImage"                                                "1"
        "image"                                                     "../vgui/slowed"
        "fgcolor"                                                   "TanDark"
    }
}
