    #base    "../../#users/custom/resource/ui/hudrocketpack.res"
    #base    "../../#users/ly_dee/resource/ui/hudrocketpack.res"
    #base    "../../#users/jayhyunpae/resource/ui/hudrocketpack.res"
    #base    "../../_stream/resource/ui/hudrocketpack.res"
    #base    "../../_budhud/resource/ui/hudrocketpack.res"
    #base    "../../_tf2hud/resource/ui/hudrocketpack.res"