#base "../../../#users/custom/resource/ui/lobbycontainerframe_mvm.res"
#base "../../../_stream/resource/ui/lobbycontainerframe_mvm.res"

"Resource/UI/LobbyContainerFrame_MvM.res"
{

    "learnmorebutton"
    {
        "ypos"                                                      "r-6969"
        "labeltext"                                                 "#bh_MvMGuide"
        "defaultBgColor_override"                                   "bh_Theme_BG20"
        "armedBgColor_override"                                     "bh_Theme_BG30"
        "depressedBgColor_override"                                 "bh_Theme_BG30"
        "defaultFgColor_override"                                   "bh_Theme_TextSecondary"
        "armedFgColor_override"                                     "bh_Theme_TextAccent"
        "depressedFgColor_override"                                 "bh_ButtonDepressed"
        "border_default"                                            "bh_b_NESW"
        "border_armed"                                              "bh_b_NESW"
        "paintbackground"                                           "1"
        "ControlName"                                               "CExImageButton"
        "fieldName"                                                 "LearnMoreButton"
        "xpos"                                                      "c106"
        "zpos"                                                      "2"
        "wide"                                                      "195"
        "tall"                                                      "25"
        "autoResize"                                                "0"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "tabPosition"                                               "0"
        "labelText"                                                 "#TF_MvM_LearnMore"
        "font"                                                      "HudFontSmallBold"
        "textAlignment"                                             "center"
        "dulltext"                                                  "0"
        "brighttext"                                                "0"
        "Command"                                                   "learn_more"
        "NavUp"                                                     "PracticeButton"
        "NavLeft"                                                   "BackButton"
        "NavRight"                                                  "NextButton"
        "sound_depressed"                                           "UI/buttonclick.wav"
        "sound_released"                                            "UI/buttonclickrelease.wav"
    }

    "playnowbutton"
    {
        "ypos"                                                      "304"
        "labeltext"                                                 "#bh_MannUp"
        "defaultBgColor_override"                                   "bh_Theme_BG20"
        "armedBgColor_override"                                     "bh_Theme_BG30"
        "depressedBgColor_override"                                 "bh_Theme_BG30"
        "defaultFgColor_override"                                   "bh_Theme_TextSecondary"
        "armedFgColor_override"                                     "bh_Theme_TextAccent"
        "depressedFgColor_override"                                 "bh_ButtonDepressed"
        "border_default"                                            "bh_b_NESW"
        "border_armed"                                              "bh_b_NESW"
        "paintbackground"                                           "1"
        "ControlName"                                               "CExButton"
        "fieldName"                                                 "PlayNowButton"
        "xpos"                                                      "c-295"
        "zpos"                                                      "20"
        "wide"                                                      "180"
        "tall"                                                      "40"
        "autoResize"                                                "0"
        "pinCorner"                                                 "0"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "tabPosition"                                               "0"
        "labelText"                                                 "#TF_MvM_MannUp"
        "font"                                                      "HudFontMediumBold"
        "textAlignment"                                             "center"
        "textinsetx"                                                "50"
        "dulltext"                                                  "0"
        "brighttext"                                                "0"
        "Command"                                                   "mannup"
        "NavUp"                                                     "Sheet"
        "NavDown"                                                   "BackButton"
        "NavLeft"                                                   "Sheet"
        "NavRight"                                                  "PracticeButton"
        "sound_depressed"                                           "UI/buttonclick.wav"
        "sound_released"                                            "UI/buttonclickrelease.wav"
    }

    "practicebutton"
    {
        "ypos"                                                      "304"
        "labeltext"                                                 "#bh_Training"
        "defaultBgColor_override"                                   "bh_Theme_BG20"
        "armedBgColor_override"                                     "bh_Theme_BG30"
        "depressedBgColor_override"                                 "bh_Theme_BG30"
        "defaultFgColor_override"                                   "bh_Theme_TextSecondary"
        "armedFgColor_override"                                     "bh_Theme_TextAccent"
        "depressedFgColor_override"                                 "bh_ButtonDepressed"
        "border_default"                                            "bh_b_NESW"
        "border_armed"                                              "bh_b_NESW"
        "paintbackground"                                           "1"
        "ControlName"                                               "CExButton"
        "fieldName"                                                 "PracticeButton"
        "xpos"                                                      "c-95"
        "zpos"                                                      "20"
        "wide"                                                      "180"
        "tall"                                                      "40"
        "autoResize"                                                "0"
        "pinCorner"                                                 "0"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "tabPosition"                                               "0"
        "labelText"                                                 "#TF_MvM_BootCamp"
        "font"                                                      "HudFontMediumBold"
        "textAlignment"                                             "center"
        "textinsetx"                                                "50"
        "dulltext"                                                  "0"
        "brighttext"                                                "0"
        "Command"                                                   "practice"
        "NavUp"                                                     "Sheet"
        "NavDown"                                                   "LearnMoreButton"
        "NavLeft"                                                   "PlayNowButton"
        "NavRight"                                                  "StartPartyButton"
        "sound_depressed"                                           "UI/buttonclick.wav"
        "sound_released"                                            "UI/buttonclickrelease.wav"
    }

    "optionsbutton"
    {
        "xpos"                                                      "c270"
        "ypos"                                                      "72"
        "zpos"                                                      "80085"
        "wide"                                                      "12"
        "tall"                                                      "12"
        "image_drawcolor"                                           "255 255 255 255"
        "image_armedcolor"                                          "240 134 049 255"
        "paintbackground"                                           "0"

        "subimage"
        {
            "xpos"                                                  "0"
            "ypos"                                                  "0"
            "wide"                                                  "12"
            "tall"                                                  "12"
            "ControlName"                                           "ImagePanel"
            "fieldName"                                             "SubImage"
            "zpos"                                                  "1"
            "visible"                                               "1"
            "enabled"                                               "1"
            "image"                                                 "glyph_options"
            "scaleImage"                                            "1"
        }
        "ControlName"                                               "CExImageButton"
        "fieldName"                                                 "OptionsButton"
        "visible"                                                   "0"
        "autoResize"                                                "0"
        "pinCorner"                                                 "0"
        "enabled"                                                   "1"
        "tabPosition"                                               "0"
        "labelText"                                                 ""
        "font"                                                      "HudFontSmallBold"
        "textAlignment"                                             "center"
        "dulltext"                                                  "0"
        "brighttext"                                                "0"
        "default"                                                   "0"
        "Command"                                                   "options"
        "sound_depressed"                                           "UI/buttonclick.wav"
        "sound_released"                                            "UI/buttonclickrelease.wav"
    }

    "lobbycontainerframe"
    {
        "bgcolor_override"                                          "bh_Theme_BG20"
        "infocus_bgcolor_override"                                  "bh_Theme_BG20"
        "outoffocus_bgcolor_override"                               "bh_Theme_BG20"
        "ControlName"                                               "EditablePanel"
        "fieldName"                                                 "LobbyContainerFrame"
        "xpos"                                                      "0"
        "ypos"                                                      "0"
        "wide"                                                      "f0"
        "tall"                                                      "480"
        "autoResize"                                                "0"
        "pinCorner"                                                 "0"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "tabPosition"                                               "0"
        "settitlebarvisible"                                        "1"
        "PaintBackgroundType"                                       "0"
        "title"                                                     "#CharInfoAndSetup"
        "title_font"                                                "HudFontMediumBold"
        "titletextinsetX"                                           "40"
        "titletextinsetY"                                           "0"
        "titlebarfgcolor_override"                                  "200 187 161 255"
        "titlebardisabledfgcolor_override"                          "200 187 161 255"
        "titlebarbgcolor_override"                                  "46 43 42 255"
        "clientinsetx_override"                                     "0"
        "sheetinset_bottom"                                         "40"
        "NavToRelay"                                                "BackButton"
    }

    "footerline"
    {
        "ControlName"                                               "EditablePanel"
        "image"                                                     ""
        "tall"                                                      "2"
        "bgcolor_override"                                          "bh_border"
        "fieldName"                                                 "FooterLine"
        "xpos"                                                      "0"
        "ypos"                                                      "420"
        "zpos"                                                      "2"
        "wide"                                                      "f0"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "scaleImage"                                                "1"
    }

    "sheet"
    {

        "headerline"
        {
            "ControlName"                                           "EditablePanel"
            "tall"                                                  "2"
            "bgcolor_override"                                      "bh_border"
            "fieldName"                                             "HeaderLine"
            "xpos"                                                  "0"
            "ypos"                                                  "32"
            "zpos"                                                  "5"
            "wide"                                                  "f0"
            "visible"                                               "1"
            "enabled"                                               "1"
            "image"                                                 "loadout_solid_line"
            "scaleImage"                                            "1"
        }

        "tabskv"
        {
            "textAlignment"                                         "center"
            "selectedcolor"                                         "bh_white"
            "unselectedcolor"                                       "bh_gray"
            "defaultBgColor_override"                               "bh_Theme_BG20"
            "paintbackground"                                       "1"
            "activeborder_override"                                 "bh_b_NEW"
            "normalborder_override"                                 "bh_b_NEW"
            "textinsetx"                                            "40"
            "font"                                                  "HudFontMediumBold"
            "mouseinputenabled"                                     "0"
        }
        "ControlName"                                               "EditablePanel"
        "fieldName"                                                 "Sheet"
        "tabxindent"                                                "80"
        "tabxdelta"                                                 "10"
        "tabwidth"                                                  "240"
        "tabheight"                                                 "34"
        "transition_time"                                           "0"
    }

    "backbutton"
    {
        "xpos"                                                      "c-300"
        "ypos"                                                      "437"
        "zpos"                                                      "4"
        "wide"                                                      "100"
        "tall"                                                      "25"
        "defaultBgColor_override"                                   "bh_Theme_BG20"
        "armedBgColor_override"                                     "bh_Theme_BG30"
        "depressedBgColor_override"                                 "bh_Theme_BG30"
        "defaultFgColor_override"                                   "bh_Theme_TextSecondary"
        "armedFgColor_override"                                     "bh_Theme_TextAccent"
        "depressedFgColor_override"                                 "bh_ButtonDepressed"
        "border_default"                                            "bh_b_NESW"
        "border_armed"                                              "bh_b_NESW"
        "ControlName"                                               "CExButton"
        "fieldName"                                                 "BackButton"
        "autoResize"                                                "0"
        "pinCorner"                                                 "3"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "tabPosition"                                               "0"
        "font"                                                      "HudFontSmallBold"
        "textAlignment"                                             "center"
        "dulltext"                                                  "0"
        "brighttext"                                                "0"
        "Command"                                                   "back"
        "NavUp"                                                     "PlayNowButton"
        "NavRight"                                                  "LearnMoreButton"
        "sound_depressed"                                           "UI/buttonclick.wav"
        "sound_released"                                            "UI/buttonclickrelease.wav"
    }

    "nextbutton"
    {
        "xpos"                                                      "c200"
        "ypos"                                                      "437"
        "zpos"                                                      "2"
        "wide"                                                      "100"
        "tall"                                                      "25"
        "defaultBgColor_override"                                   "bh_Theme_BG20"
        "armedBgColor_override"                                     "bh_Theme_BG30"
        "depressedBgColor_override"                                 "bh_Theme_BG30"
        "defaultFgColor_override"                                   "bh_Theme_TextSecondary"
        "armedFgColor_override"                                     "bh_Theme_TextAccent"
        "depressedFgColor_override"                                 "bh_ButtonDepressed"
        "border_default"                                            "bh_b_NESW"
        "border_armed"                                              "bh_b_NESW"
        "ControlName"                                               "CExImageButton"
        "fieldName"                                                 "NextButton"
        "autoResize"                                                "0"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "tabPosition"                                               "0"
        "font"                                                      "HudFontSmallBold"
        "textAlignment"                                             "center"
        "dulltext"                                                  "0"
        "brighttext"                                                "0"
        "Command"                                                   "next"
        "NavUp"                                                     "StartPartyButton"
        "NavDown"                                                   "LearnMoreButton"
        "NavLeft"                                                   "LearnMoreButton"
        "sound_depressed"                                           "UI/buttonclick.wav"
        "sound_released"                                            "UI/buttonclickrelease.wav"
    }

    "startpartybutton"
    {
        "labeltext"                                                 "#bh_CreateParty"
        "defaultBgColor_override"                                   "bh_Theme_BG20"
        "armedBgColor_override"                                     "bh_Theme_BG30"
        "depressedBgColor_override"                                 "bh_Theme_BG30"
        "defaultFgColor_override"                                   "bh_Theme_TextSecondary"
        "armedFgColor_override"                                     "bh_Theme_TextAccent"
        "depressedFgColor_override"                                 "bh_ButtonDepressed"
        "border_default"                                            "bh_b_NESW"
        "border_armed"                                              "bh_b_NESW"
        "ControlName"                                               "CExButton"
        "fieldName"                                                 "StartPartyButton"
        "xpos"                                                      "c+110"
        "ypos"                                                      "310"
        "zpos"                                                      "10"
        "wide"                                                      "180"
        "tall"                                                      "25"
        "autoResize"                                                "0"
        "pinCorner"                                                 "0"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "tabPosition"                                               "0"
        "labelText"                                                 "#TF_Matchmaking_StartParty"
        "font"                                                      "HudFontSmallBold"
        "textAlignment"                                             "center"
        "textinsetx"                                                "50"
        "dulltext"                                                  "0"
        "brighttext"                                                "0"
        "Command"                                                   "start_party"
        "NavUp"                                                     "Sheet"
        "NavDown"                                                   "NextButton"
        "NavLeft"                                                   "PracticeButton"
        "sound_depressed"                                           "UI/buttonclick.wav"
        "sound_released"                                            "UI/buttonclickrelease.wav"
    }

    "playwithfriendsexplanation"
    {
        "ControlName"                                               "EditablePanel"
        "fieldName"                                                 "PlayWithFriendsExplanation"
        "xpos"                                                      "c+100"
        "ypos"                                                      "62"
        "zpos"                                                      "8"
        "wide"                                                      "200"
        "tall"                                                      "285"
        "PaintBackgroundType"                                       "0"
        "paintbackground"                                           "1"
        "bgcolor_override"                                          "0 0 0 200"
        "border"                                                    "QuickplayBorder"

        "playwithfriendsexplanationtitle"
        {
            "ControlName"                                           "CExLabel"
            "fieldName"                                             "PlayWithFriendsExplanationTitle"
            "font"                                                  "HudFontSmallBold"
            "labelText"                                             "#TF_Matchmaking_PlayWithFriends"
            "textAlignment"                                         "center"
            "xpos"                                                  "0"
            "ypos"                                                  "0"
            "zpos"                                                  "10"
            "wide"                                                  "200"
            "tall"                                                  "32"
        }

        "friendsimage"
        {
            "ControlName"                                           "ImagePanel"
            "fieldName"                                             "FriendsImage"
            "xpos"                                                  "10"
            "ypos"                                                  "32"
            "zpos"                                                  "0"
            "wide"                                                  "180"
            "tall"                                                  "90"
            "visible"                                               "1"
            "enabled"                                               "1"
            "image"                                                 "pve/mvm_friends_image"
            "scaleImage"                                            "1"
        }

        "playwithfriendsexplanationlabel"
        {
            "ControlName"                                           "CExLabel"
            "fieldName"                                             "PlayWithFriendsExplanationLabel"
            "font"                                                  "HudFontSmall"
            "labelText"                                             "#TF_MvM_PlayWithFriendsExplanation"
            "textAlignment"                                         "north-west"
            "xpos"                                                  "10"
            "ypos"                                                  "130"
            "zpos"                                                  "10"
            "wide"                                                  "180"
            "tall"                                                  "150"
            "wrap"                                                  "1"
        }
    }

    "backgroundheader"
    {
        "ControlName"                                               "ImagePanel"
        "fieldName"                                                 "BackgroundHeader"
        "xpos"                                                      "0"
        "ypos"                                                      "0"
        "zpos"                                                      "-2"
        "wide"                                                      "f0"
        "tall"                                                      "120"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "image"                                                     "loadout_header"
        "tileImage"                                                 "1"
    }

    "backgroundfooter"
    {
        "ControlName"                                               "ImagePanel"
        "fieldName"                                                 "BackgroundFooter"
        "xpos"                                                      "0"
        "ypos"                                                      "420"
        "zpos"                                                      "1"
        "wide"                                                      "f0"
        "tall"                                                      "60"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "image"                                                     "loadout_bottom_gradient"
        "tileImage"                                                 "1"
    }

    "notificationspresentpanel"
    {
        "ControlName"                                               "CNotificationsPresentPanel"
        "fieldName"                                                 "NotificationsPresentPanel"
        "xpos"                                                      "r200"
        "ypos"                                                      "10"
        "zpos"                                                      "10000"
        "wide"                                                      "190"
        "tall"                                                      "50"
        "visible"                                                   "0"
        "enabled"                                                   "1"
    }

    "matchmakingbanpanel"
    {
        "ControlName"                                               "EditablePanel"
        "fieldName"                                                 "MatchmakingBanPanel"
        "xpos"                                                      "c-113"
        "ypos"                                                      "428"
        "zpos"                                                      "2"
        "wide"                                                      "220"
        "tall"                                                      "40"
        "visible"                                                   "0"
        "enabled"                                                   "1"
        "mouseinputenabled"                                         "0"
        "bgcolor_override"                                          "Black"

        "matchmakingbandurationlabel"
        {
            "ControlName"                                           "CExLabel"
            "fieldName"                                             "MatchmakingBanDurationLabel"
            "font"                                                  "HudFontSmallest"
            "fgcolor_override"                                      "RedSolid"
            "labelText"                                             "#TF_Matchmaking_Ban_Duration_Remaining"
            "textalignment"                                         "center"
            "xpos"                                                  "5"
            "ypos"                                                  "0"
            "zpos"                                                  "2"
            "wide"                                                  "200"
            "tall"                                                  "40"
            "visible"                                               "1"
            "enabled"                                               "1"
            "autoResize"                                            "1"
            "pinCorner"                                             "0"
        }
    }
}
