#base "../../../#users/custom/resource/ui/matchmakingdashboardpopup_newmatch.res"
#base "../../../_stream/resource/ui/matchmakingdashboardpopup_newmatch.res"

"Resource/UI/MatchMakingDashboardPopup_NewMatch.res"
{

    "newmatchfound"
    {

        "bgpanel"
        {
            "bgcolor_override"                                      "bh_Theme_BG20"
            "border"                                                "bh_blank"

            "abandonbutton"
            {
                "defaultFgColor_override"                           "bh_Theme_TextSecondary"
                "armedFgColor_override"                             "bh_Theme_TextAccent"
                "depressedFgColor_override"                         "bh_ButtonDepressed"
                "defaultBgColor_override"                           "bh_Theme_BG20"
                "armedBgColor_override"                             "bh_Theme_BG30"
                "depressedBgColor_override"                         "bh_Theme_BG30"
                "border_default"                                    "bh_b_NESW"
                "border_armed"                                      "bh_b_NESW"
                "ControlName"                                       "CExButton"
                "fieldName"                                         "AbandonButton"
                "xpos"                                              "rs1-10"
                "ypos"                                              "rs1-5"
                "zpos"                                              "100"
                "wide"                                              "75"
                "tall"                                              "15"
                "autoResize"                                        "0"
                "pinCorner"                                         "3"
                "visible"                                           "1"
                "enabled"                                           "1"
                "tabPosition"                                       "0"
                "font"                                              "HudFontSmallestBold"
                "textAlignment"                                     "center"
                "dulltext"                                          "0"
                "brighttext"                                        "0"
                "Command"                                           "abandon_match"
                "proportionaltoparent"                              "1"
                "labeltext"                                         "#TF_MM_Rejoin_Abandon"
                "mouseinputenabled"                                 "1"
                "keyboardinputenabled"                              "0"
                "actionsignallevel"                                 "2"
                "paintbackground"                                   "1"
                "sound_depressed"                                   "UI/buttonclick.wav"
                "sound_released"                                    "UI/buttonclickrelease.wav"
            }

            "smalljoinbutton"
            {
                "defaultFgColor_override"                           "bh_Theme_TextSecondary"
                "armedFgColor_override"                             "bh_Theme_TextAccent"
                "depressedFgColor_override"                         "bh_ButtonDepressed"
                "defaultBgColor_override"                           "bh_Theme_BG20"
                "armedBgColor_override"                             "bh_Theme_BG30"
                "depressedBgColor_override"                         "bh_Theme_BG30"
                "border_default"                                    "bh_b_NESW"
                "border_armed"                                      "bh_b_NESW"
                "ControlName"                                       "CExButton"
                "fieldName"                                         "SmallJoinButton"
                "xpos"                                              "10"
                "ypos"                                              "rs1-5"
                "wide"                                              "90"
                "zpos"                                              "100"
                "tall"                                              "15"

                "$_disabled_expected"
                {
                    "xpos"                                          "cs-0.5"
                    "wide"                                          "150"
                }
                "autoResize"                                        "0"
                "pinCorner"                                         "3"
                "visible"                                           "1"
                "enabled"                                           "1"
                "tabPosition"                                       "0"
                "font"                                              "HudFontSmallestBold"
                "textAlignment"                                     "center"
                "dulltext"                                          "0"
                "brighttext"                                        "0"
                "Command"                                           "join_match"
                "proportionaltoparent"                              "1"
                "labeltext"                                         "#TF_Matchmaking_RollingQueue_JoinNow"
                "mouseinputenabled"                                 "1"
                "keyboardinputenabled"                              "0"
                "actionsignallevel"                                 "2"
                "sound_depressed"                                   "UI/buttonclick.wav"
                "sound_released"                                    "UI/buttonclickrelease.wav"
            }

            "widejoinbutton"
            {
                "defaultFgColor_override"                           "bh_Theme_TextSecondary"
                "armedFgColor_override"                             "bh_Theme_TextAccent"
                "depressedFgColor_override"                         "bh_ButtonDepressed"
                "defaultBgColor_override"                           "bh_Theme_BG20"
                "armedBgColor_override"                             "bh_Theme_BG30"
                "depressedBgColor_override"                         "bh_Theme_BG30"
                "border_default"                                    "bh_b_NESW"
                "border_armed"                                      "bh_b_NESW"
                "ControlName"                                       "CExButton"
                "fieldName"                                         "WideJoinButton"
                "xpos"                                              "cs-0.5"
                "ypos"                                              "rs1-5"
                "wide"                                              "150"
                "zpos"                                              "100"
                "tall"                                              "15"
                "autoResize"                                        "0"
                "pinCorner"                                         "3"
                "visible"                                           "1"
                "enabled"                                           "1"
                "tabPosition"                                       "0"
                "font"                                              "HudFontSmallestBold"
                "textAlignment"                                     "center"
                "dulltext"                                          "0"
                "brighttext"                                        "0"
                "Command"                                           "join_match"
                "proportionaltoparent"                              "1"
                "labeltext"                                         "#TF_Matchmaking_RollingQueue_JoinNow"
                "mouseinputenabled"                                 "1"
                "keyboardinputenabled"                              "0"
                "actionsignallevel"                                 "2"
                "sound_depressed"                                   "UI/buttonclick.wav"
                "sound_released"                                    "UI/buttonclickrelease.wav"
            }

            "spinner"
            {
                "xpos"                                              "c+10"
                "ypos"                                              "rs1-13"
                "ControlName"                                       "CTFLogoPanel"
                "fieldName"                                         "Spinner"
                "zpos"                                              "104"
                "wide"                                              "o1"
                "tall"                                              "25"
                "visible"                                           "1"
                "proportionaltoparent"                              "1"
                "mouseinputenabled"                                 "0"
                "alpha"                                             "200"
                "radius"                                            "10"
                "velocity"                                          "250"
                "fgcolor_override"                                  "Orange"
            }
            "ControlName"                                           "EditablePanel"
            "fieldName"                                             "BGPanel"
            "xpos"                                                  "cs-0.5"
            "ypos"                                                  "cs-0.5"
            "zpos"                                                  "-1"
            "wide"                                                  "f5"
            "tall"                                                  "f5"
            "visible"                                               "1"
            "PaintBackgroundType"                                   "2"
            "proportionaltoparent"                                  "1"
            "pinCorner"                                             "3"

            "desclabel"
            {
                "ControlName"                                       "CAutoFittingLabel"
                "fieldName"                                         "DescLabel"
                "xpos"                                              "0"
                "ypos"                                              "7"
                "wide"                                              "f0"
                "zpos"                                              "100"
                "tall"                                              "20"
                "visible"                                           "1"
                "enabled"                                           "1"
                "font"                                              "HudFontSmallBold"
                "fgcolor_override"                                  "TanLight"
                "textAlignment"                                     "center"
                "labelText"                                         "%match_type%"
                "proportionaltoparent"                              "1"
                "pinCorner"                                         "3"

                "fonts"
                {
                    "0"                                             "HudFontSmallestBold"
                    "1"                                             "StorePromotionsTitle"
                    "2"                                             "FontStorePrice"
                }
            }

            "autojoinlabel"
            {
                "ControlName"                                       "Label"
                "fieldName"                                         "AutoJoinLabel"
                "xpos"                                              "0"
                "ypos"                                              "rs1-17"
                "wide"                                              "f0"
                "zpos"                                              "100"
                "tall"                                              "20"
                "visible"                                           "1"
                "enabled"                                           "1"
                "font"                                              "HudFontSmallest"
                "fgcolor_override"                                  "TanLight"
                "textAlignment"                                     "center"
                "labelText"                                         "%auto_join%"
                "proportionaltoparent"                              "1"
                "pinCorner"                                         "3"
            }

            "joininglabel"
            {
                "ControlName"                                       "Label"
                "fieldName"                                         "JoiningLabel"
                "xpos"                                              "cs-1"
                "ypos"                                              "rs1-17"
                "wide"                                              "f0"
                "zpos"                                              "100"
                "tall"                                              "20"
                "visible"                                           "1"
                "enabled"                                           "1"
                "font"                                              "HudFontSmallest"
                "fgcolor_override"                                  "TanLight"
                "textAlignment"                                     "east"
                "labelText"                                         "#TF_Matchmaking_RollingQueue_MatchReadyJoining"
                "proportionaltoparent"                              "1"
                "pinCorner"                                         "3"
            }
        }
        "ControlName"                                               "CExpandablePanel"
        "fieldName"                                                 "NewMatchFound"
        "xpos"                                                      "cs-0.5"
        "ypos"                                                      "0"
        "zpos"                                                      "9999"
        "wide"                                                      "200"
        "tall"                                                      "60"
        "visible"                                                   "1"
        "proportionaltoparent"                                      "0"
        "keyboardinputenabled"                                      "0"
        "mouseinputenabled"                                         "1"
        "collapsed_height"                                          "0"
        "expanded_height"                                           "60"
        "pinCorner"                                                 "2"
        "autoResize"                                                "1"

        "outershadow"
        {
            "ControlName"                                           "EditablePanel"
            "fieldName"                                             "OuterShadow"
            "xpos"                                                  "0"
            "ypos"                                                  "rs1"
            "zpos"                                                  "-2"
            "wide"                                                  "f0"
            "tall"                                                  "f0"
            "visible"                                               "1"
            "PaintBackgroundType"                                   "0"
            "border"                                                "OuterShadowBorder"
            "proportionaltoparent"                                  "1"
            "pinCorner"                                             "0"
            "autoResize"                                            "2"
        }
    }
}
