#base "../../../#users/custom/resource/ui/matchmakingcasualcriteria.res"
#base "../../../_stream/resource/ui/matchmakingcasualcriteria.res"

"Resource/UI/MatchmakingCasualCriteria.res"
{

    "playlistbgpanel"
    {

        "rankimage"
        {
            "ypos"                                                  "r-6969"
            "visible"                                               "0"
            "enabled"                                               "0"
            "ControlName"                                           "CTFLocalPlayerBadgePanel"
            "fieldName"                                             "RankImage"
            "xpos"                                                  "4"
            "zpos"                                                  "110"
            "wide"                                                  "o1"
            "tall"                                                  "60"
            "proportionaltoparent"                                  "1"
            "mouseinputenabled"                                     "0"
            "matchgroup"                                            "MatchGroup_Casual_12v12"
        }

        "rankpanel"
        {
            "ypos"                                                  "r-6969"
            "visible"                                               "0"
            "enabled"                                               "0"
            "ControlName"                                           "CPvPRankPanel"
            "fieldName"                                             "RankPanel"
            "xpos"                                                  "-70"
            "zpos"                                                  "100"
            "wide"                                                  "330"
            "tall"                                                  "92"
            "proportionaltoparent"                                  "1"
            "mouseinputenabled"                                     "0"
            "matchgroup"                                            "MatchGroup_Casual_12v12"
            "show_model"                                            "0"
            "show_name"                                             "0"
        }

        "title"
        {
            "xpos"                                                  "cs-0.5"
            "wide"                                                  "f0"
            "textalignment"                                         "center"
            "ypos"                                                  "2"
            "fgcolor"                                               "bh_Theme_TextSecondary"
            "ControlName"                                           "Label"
            "fieldName"                                             "Title"
            "zpos"                                                  "0"
            "tall"                                                  "20"
            "proportionaltoparent"                                  "1"
            "labeltext"                                             "#TF_Casual_MapSelection"
            "textAlignment"                                         "north-west"
            "font"                                                  "HudFontMediumSmallBold"
            "mouseinputenabled"                                     "0"
        }

        "selectedcount"
        {
            "xpos"                                                  "cs-0.5"
            "wide"                                                  "f0"
            "textalignment"                                         "center"
            "ypos"                                                  "15"
            "fgcolor_override"                                      "bh_Theme_TextSecondary"
            "ControlName"                                           "Label"
            "fieldName"                                             "SelectedCount"
            "zpos"                                                  "0"
            "tall"                                                  "20"
            "proportionaltoparent"                                  "1"
            "labeltext"                                             "%selected_maps_count%"
            "textAlignment"                                         "west"
            "font"                                                  "HudFontSmallest"
            "mouseinputenabled"                                     "1"
        }

        "restorecasualsearchcriteria"
        {
            "paintbackground"                                       "0"
            "image_drawcolor"                                       "255 255 255 255"
            "image_armedcolor"                                      "240 134 49 255"
            "ControlName"                                           "CExImageButton"
            "fieldName"                                             "RestoreCasualSearchCriteria"
            "xpos"                                                  "rs1-49"
            "ypos"                                                  "49"
            "zpos"                                                  "100"
            "wide"                                                  "15"
            "tall"                                                  "o1"
            "autoResize"                                            "0"
            "pinCorner"                                             "0"
            "visible"                                               "1"
            "enabled"                                               "1"
            "tabPosition"                                           "0"
            "labelText"                                             ""
            "font"                                                  "HudFontSmallBold"
            "textAlignment"                                         "center"
            "dulltext"                                              "0"
            "brighttext"                                            "0"
            "default"                                               "0"
            "Command"                                               "restore_search_criteria"
            "sound_depressed"                                       "UI/buttonclick.wav"
            "sound_released"                                        "UI/buttonclickrelease.wav"
            "actionsignallevel"                                     "2"
            "proportionaltoparent"                                  "1"

            "subimage"
            {
                "ControlName"                                       "ImagePanel"
                "fieldName"                                         "SubImage"
                "xpos"                                              "2"
                "ypos"                                              "2"
                "zpos"                                              "1"
                "wide"                                              "11"
                "tall"                                              "11"
                "visible"                                           "1"
                "enabled"                                           "1"
                "image"                                             "button_load"
                "scaleImage"                                        "1"
            }
        }

        "savecasualsearchcriteria"
        {
            "paintbackground"                                       "0"
            "image_drawcolor"                                       "255 255 255 255"
            "image_armedcolor"                                      "240 134 49 255"
            "ControlName"                                           "CExImageButton"
            "fieldName"                                             "SaveCasualSearchCriteria"
            "xpos"                                                  "rs1-29"
            "ypos"                                                  "49"
            "zpos"                                                  "100"
            "wide"                                                  "15"
            "tall"                                                  "o1"
            "autoResize"                                            "0"
            "pinCorner"                                             "0"
            "visible"                                               "1"
            "enabled"                                               "1"
            "tabPosition"                                           "0"
            "labelText"                                             ""
            "font"                                                  "HudFontSmallBold"
            "textAlignment"                                         "center"
            "dulltext"                                              "0"
            "brighttext"                                            "0"
            "default"                                               "0"
            "Command"                                               "save_search_criteria"
            "sound_depressed"                                       "UI/buttonclick.wav"
            "sound_released"                                        "UI/buttonclickrelease.wav"
            "actionsignallevel"                                     "2"
            "proportionaltoparent"                                  "1"

            "subimage"
            {
                "ControlName"                                       "ImagePanel"
                "fieldName"                                         "SubImage"
                "xpos"                                              "2"
                "ypos"                                              "2"
                "zpos"                                              "1"
                "wide"                                              "11"
                "tall"                                              "11"
                "visible"                                           "1"
                "enabled"                                           "1"
                "image"                                             "button_save"
                "scaleImage"                                        "1"
            }
        }

        "showexplanationsbutton"
        {
            "paintbackground"                                       "0"
            "defaultFgColor_override"                               "bh_Theme_TextSecondary"
            "armedFgColor_override"                                 "bh_Theme_TextAccent"
            "depressedFgColor_override"                             "bh_ButtonDepressed"
            "ControlName"                                           "CExButton"
            "fieldName"                                             "ShowExplanationsButton"
            "xpos"                                                  "rs1-9"
            "ypos"                                                  "49"
            "zpos"                                                  "100"
            "wide"                                                  "15"
            "tall"                                                  "o1"
            "autoResize"                                            "0"
            "pinCorner"                                             "0"
            "visible"                                               "1"
            "enabled"                                               "1"
            "tabPosition"                                           "0"
            "labelText"                                             "?"
            "font"                                                  "HudFontSmallBold"
            "textAlignment"                                         "center"
            "dulltext"                                              "0"
            "brighttext"                                            "0"
            "default"                                               "0"
            "Command"                                               "show_explanations"
            "sound_depressed"                                       "UI/buttonclick.wav"
            "sound_released"                                        "UI/buttonclickrelease.wav"
            "actionsignallevel"                                     "2"
            "proportionaltoparent"                                  "1"
        }

        "playlistdropshadow"
        {
            "ypos"                                                  "r-6969"
            "visible"                                               "0"
            "enabled"                                               "0"
            "ControlName"                                           "EditablePanel"
            "fieldName"                                             "PlayListDropShadow"
            "xpos"                                                  "cs-0.5"
            "zpos"                                                  "101"
            "wide"                                                  "f15"
            "tall"                                                  "f65"
            "PaintBackgroundType"                                   "2"
            "border"                                                "InnerShadowBorder"
            "proportionaltoparent"                                  "1"
            "mouseinputenabled"                                     "0"
        }

        "gamemodeslist"
        {
            "border"                                                "NoBorder"

            "scrollbar"
            {
                "xpos"                                              "r5"
                "wide"                                              "6"
                "ControlName"                                       "ScrollBar"
                "FieldName"                                         "ScrollBar"
                "ypos"                                              "0"
                "tall"                                              "f0"
                "zpos"                                              "1000"
                "nobuttons"                                         "1"
                "proportionaltoparent"                              "1"

                "slider"
                {
                    "fgcolor_override"                              "TanDark"
                }

                "upbutton"
                {
                    "ControlName"                                   "Button"
                    "FieldName"                                     "UpButton"
                    "visible"                                       "0"
                }

                "downbutton"
                {
                    "ControlName"                                   "Button"
                    "FieldName"                                     "DownButton"
                    "visible"                                       "0"
                }
            }
            "ControlName"                                           "CScrollableList"
            "fieldName"                                             "GameModesList"
            "xpos"                                                  "cs-0.5"
            "ypos"                                                  "65"
            "wide"                                                  "f15"
            "tall"                                                  "f65"
            "visible"                                               "1"
            "proportionaltoparent"                                  "1"
            "restrict_width"                                        "0"
        }
        "ControlName"                                               "EditablePanel"
        "fieldName"                                                 "PlaylistBGPanel"
        "xpos"                                                      "cs-0.5"
        "ypos"                                                      "0"
        "zpos"                                                      "-1"
        "wide"                                                      "p0.98"
        "tall"                                                      "p1"
        "visible"                                                   "1"
        "PaintBackgroundType"                                       "2"
        "proportionaltoparent"                                      "1"
        "pinCorner"                                                 "2"
        "autoResize"                                                "1"

        "queueestimation"
        {
            "ControlName"                                           "Label"
            "fieldName"                                             "QueueEstimation"
            "xpos"                                                  "rs1-5"
            "ypos"                                                  "18"
            "zpos"                                                  "0"
            "wide"                                                  "f0"
            "tall"                                                  "20"
            "proportionaltoparent"                                  "1"
            "labeltext"                                             "#TF_Casual_QueueEstimation"
            "textAlignment"                                         "east"
            "font"                                                  "HudFontSmallest"
            "fgcolor_override"                                      "TanLight"
            "textinsetx"                                            "5"
            "visible"                                               "0"
            "mouseinputenabled"                                     "0"
        }
    }
}
