    #base    "../../#users/custom/resource/ui/pvpcomprankpanel.res"
    #base    "../../#users/custom/#customization/_enabled/bh_menu_hidestats.res"
    #base    "../../#customization/_enabled/bh_menu_hidestats.res"
    #base    "../../_stream/resource/ui/pvpcomprankpanel.res"
    #base    "../../_budhud/resource/ui/pvpcomprankpanel.res"
    #base    "../../_tf2hud/resource/ui/pvpcomprankpanel.res"