	#base	"..\..\#users\toth\#customization\_enabled\bh_mainmenu_hidestats.res"
	#base	"..\..\#customization\_enabled\bh_mainmenu_hidestats.res"
	#base	"..\..\_stream\resource\ui\pvprankpanel.res"
	#base	"..\..\_budhud\resource\ui\pvprankpanel.res"
	#base	"..\..\_tf2hud\resource\ui\pvprankpanel.res"