	#base	"..\..\#users\toth\#customization\bh_menu_hidestats.res"
	#base	"..\..\#customization\_enabled\bh_menu_hidestats.res"
	#base	"..\..\#users\custom\resource\ui\pvprankpanel.res"
	#base	"..\..\_stream\resource\ui\pvprankpanel.res"
	#base	"..\..\_budhud\resource\ui\pvprankpanel.res"
	#base	"..\..\_tf2hud\resource\ui\pvprankpanel.res"