    #base    "../../#users/custom/resource/ui/revivedialog.res"
    #base    "../../#customization/_enabled/bh_targetid_healthcross/revivedialog.res"
    #base    "../../_stream/resource/ui/revivedialog.res"
    #base    "../../_budhud/resource/ui/revivedialog.res"
    #base    "../../_tf2hud/resource/ui/revivedialog.res"