    #base    "../../#users/custom/resource/ui/spectatortournament.res"
    #base    "../../#users/custom/#customization/_enabled/bh_tournamentpanels_lowered.res"
    #base    "../../#customization/_enabled/bh_tournamentpanels_lowered.res"
    #base    "../../#customization/_enabled/bh_dev_referencelines.res"
    #base    "../../_stream/resource/ui/spectatortournament.res"
    #base    "../../_budhud/resource/ui/spectatortournament.res"
    #base    "../../_tf2hud/resource/ui/spectatortournament.res"