	#base	"..\..\#customization\_enabled\bh_spectatorguihealth_size.res"
	#base	"..\..\#customization\_enabled\bh_spectatorguihealth_cross.res"
	#base	"..\..\_stream\resource\ui\spectatorguihealth.res"
	#base	"..\..\_budhud\resource\ui\spectatorguihealth.res"
	#base	"..\..\_tf2hud\resource\ui\spectatorguihealth.res"