    #base    "../../#users/custom/resource/ui/statsummary.res"
    #base    "../../#users/ly_dee/#customization/_enabled/bh_stats_customimage.res"
    #base    "../../#users/jayhyunpae/#customization/_enabled/bh_stats_customimage.res"
    #base    "../../#customization/_enabled/bh_stats_customimage.res"
    #base    "../../#customization/_enabled/bh_stats_hidebackground.res"
    #base    "../../_stream/resource/ui/statsummary.res"
    #base    "../../_budhud/resource/ui/statsummary.res"
    #base    "../../_tf2hud/resource/ui/statsummary.res"