	#base	"..\..\#customization\_enabled\bh_statsummary_loadingimage.res"
	#base	"..\..\#customization\_enabled\bh_statsummary_hidebg.res"
	#base	"..\..\_stream\resource\ui\statsummary.res"
	#base	"..\..\_budhud\resource\ui\statsummary.res"
	#base	"..\..\_tf2hud\resource\ui\statsummary.res"