#base "../../../#users/custom/resource/ui/targetid.res"
#base "../../../#users/jayhyunpae/resource/ui/targetid.res"
#base "../../../#customization/_enabled/bh_targetid_healthcross2.res"
#base "../../../_stream/resource/ui/targetid.res"

"Resource/UI/TargetID.res"
{

    "avatarimage"
    {
        "ypos"                                                      "r-6969"
        "visible"                                                   "0"
        "enabled"                                                   "0"
        "ControlName"                                               "CAvatarImagePanel"
        "fieldName"                                                 "AvatarImage"
        "xpos"                                                      "6"
        "xpos$_disabled_"                                           "6"
        "zpos"                                                      "99"
        "wide"                                                      "11"
        "tall"                                                      "11"
        "image"                                                     ""
        "scaleImage"                                                "1"
        "color_outline"                                             "52 48 45 255"
    }

    "spectatorguihealth"
    {
        "xpos"                                                      "0"
        "ypos"                                                      "34"
        "wide"                                                      "40"
        "tall"                                                      "40"
        "ControlName"                                               "EditablePanel"
        "fieldName"                                                 "SpectatorGUIHealth"
        "xpos$_disabled_"                                           "0"
        "ypos$_disabled_"                                           "0"
        "visible"                                                   "0"
        "enabled"                                                   "0"
        "HealthBonusPosAdj"                                         "10"
        "HealthDeathWarning"                                        "0.49"
        "TFFont"                                                    "HudFontSmall"
        "HealthDeathWarningColor"                                   "HUDDeathWarning"
        "TextColor"                                                 "HudOffWhite"
    }

    "targetnamelabel"
    {
        "ypos"                                                      "37"
        "wide"                                                      "f0"
        "tall"                                                      "17"
        "font"                                                      "bh_Font14"
        "ControlName"                                               "Label"
        "fieldName"                                                 "TargetNameLabel"
        "font$_disabled_"                                           "TFFontLarge"
        "xpos"                                                      "8"
        "xpos$_disabled_"                                           "30"
        "ypos$_disabled_"                                           "5"
        "zpos"                                                      "1"
        "autoResize"                                                "0"
        "pinCorner"                                                 "0"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "labelText"                                                 "%targetname%"
        "textAlignment"                                             "North-West"
        "dulltext"                                                  "0"
        "brighttext"                                                "0"
    }

    "bh_targetnamebg"
    {
        "ControlName"                                               "ImagePanel"
        "fieldName"                                                 "bh_TargetNameBG"
        "xpos"                                                      "0"
        "ypos"                                                      "34"
        "zpos"                                                      "-2"
        "wide"                                                      "f0"
        "tall"                                                      "18"
        "autoResize"                                                "0"
        "pinCorner"                                                 "0"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "fillcolor"                                                 "bh_TargetID_NameBG"
        "src_corner_height"                                         "0"
        "src_corner_width"                                          "0"
        "draw_corner_width"                                         "0"
        "draw_corner_height"                                        "0"
    }

    "targetdatalabel"
    {
        "font"                                                      "bh_Font10DropShadow"
        "ypos"                                                      "51"
        "wide"                                                      "f0"
        "tall"                                                      "14"
        "textalignment"                                             "west"
        "ControlName"                                               "Label"
        "fieldName"                                                 "TargetDataLabel"
        "font$_disabled_"                                           "DefaultVerySmall"
        "xpos"                                                      "8"
        "xpos$_disabled_"                                           "30"
        "ypos$_disabled_"                                           "12"
        "zpos"                                                      "1"
        "autoResize"                                                "0"
        "pinCorner"                                                 "0"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "labelText"                                                 "%targetdata%"
        "textAlignment"                                             "Left"
        "dulltext"                                                  "0"
        "brighttext"                                                "0"
    }

    "bh_ammokspin"
    {
        "ControlName"                                               "Label"
        "fieldName"                                                 "bh_AmmoKSPin"
        "xpos"                                                      "45"
        "ypos"                                                      "54"
        "zpos"                                                      "0"
        "wide"                                                      "100"
        "tall"                                                      "0"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "bgcolor_override"                                          "0 0 0 0"
    }

    "ammoicon"
    {
        "pin_to_sibling"                                            "bh_AmmoKSPin"
        "pin_corner_to_sibling"                                     "PIN_TOPLEFT"
        "pin_to_sibling_corner"                                     "0"
        "xpos"                                                      "0"
        "ypos"                                                      "0"
        "wide"                                                      "9"
        "tall"                                                      "9"
        "ControlName"                                               "ImagePanel"
        "fieldName"                                                 "AmmoIcon"
        "xpos$_disabled_"                                           "38"
        "ypos$_disabled_"                                           "16"
        "zpos"                                                      "12"
        "visible"                                                   "0"
        "enabled"                                                   "1"
        "image"                                                     "../hud/leaderboard_class_heavy"
        "scaleImage"                                                "1"
    }

    "killstreakicon"
    {
        "pin_to_sibling"                                            "bh_AmmoKSPin"
        "pin_corner_to_sibling"                                     "PIN_TOPLEFT"
        "pin_to_sibling_corner"                                     "0"
        "xpos"                                                      "0"
        "ypos"                                                      "0"
        "wide"                                                      "9"
        "tall"                                                      "9"
        "ControlName"                                               "ImagePanel"
        "fieldName"                                                 "KillStreakIcon"
        "xpos$_disabled_"                                           "30"
        "ypos$_disabled_"                                           "16"
        "zpos"                                                      "12"
        "visible"                                                   "0"
        "enabled"                                                   "1"
        "image"                                                     "../hud/leaderboard_streak"
        "scaleImage"                                                "1"
    }

    "targetidbg"
    {
        "pin_to_sibling"                                            "SpectatorGUIHealth"
        "pin_corner_to_sibling"                                     "PIN_TOPLEFT"
        "pin_to_sibling_corner"                                     "0"
        "xpos"                                                      "0"
        "ypos"                                                      "0"
        "zpos"                                                      "-1"
        "src_corner_height"                                         "0"
        "src_corner_width"                                          "0"
        "draw_corner_width"                                         "0"
        "draw_corner_height"                                        "0"
        "teambg_1"                                                  "replay\thumbnails\team_colors\bh_targetid_gray"
        "teambg_2"                                                  "replay\thumbnails\team_colors\bh_targetid_red"
        "teambg_3"                                                  "replay\thumbnails\team_colors\bh_targetid_blue"
        "ControlName"                                               "CTFImagePanel"
        "fieldName"                                                 "TargetIDBG"
        "wide"                                                      "252"
        "tall"                                                      "50"
        "autoResize"                                                "0"
        "pinCorner"                                                 "0"
        "visible"                                                   "1"
        "enabled"                                                   "1"
        "image"                                                     "../hud/color_panel_brown"
        "scaleImage"                                                "1"
        "teambg_2$_disabled_"                                       "../hud/color_panel_red"
        "teambg_3$_disabled_"                                       "../hud/color_panel_blu"
    }

    "targetidbg_spec_blue"
    {
        "pin_to_sibling"                                            "SpectatorGUIHealth"
        "pin_corner_to_sibling"                                     "PIN_TOPLEFT"
        "pin_to_sibling_corner"                                     "0"
        "xpos"                                                      "0"
        "ypos"                                                      "0"
        "zpos"                                                      "-1"
        "src_corner_height"                                         "0"
        "src_corner_width"                                          "0"
        "draw_corner_width"                                         "0"
        "draw_corner_height"                                        "0"
        "image"                                                     "replay\thumbnails\team_colors\bh_targetid_blue"
        "ControlName"                                               "ScalableImagePanel"
        "fieldName"                                                 "TargetIDBG_Spec_Blue"
        "wide"                                                      "252"
        "tall"                                                      "30"
        "autoResize"                                                "0"
        "pinCorner"                                                 "0"
        "visible"                                                   "0"
        "enabled"                                                   "1"
        "image$_disabled_"                                          "../hud/color_panel_blu"
    }

    "targetidbg_spec_red"
    {
        "pin_to_sibling"                                            "SpectatorGUIHealth"
        "pin_corner_to_sibling"                                     "PIN_TOPLEFT"
        "pin_to_sibling_corner"                                     "0"
        "xpos"                                                      "0"
        "ypos"                                                      "0"
        "zpos"                                                      "-1"
        "src_corner_height"                                         "0"
        "src_corner_width"                                          "0"
        "draw_corner_width"                                         "0"
        "draw_corner_height"                                        "0"
        "image"                                                     "replay\thumbnails\team_colors\bh_targetid_red"
        "ControlName"                                               "ScalableImagePanel"
        "fieldName"                                                 "TargetIDBG_Spec_Red"
        "wide"                                                      "252"
        "tall"                                                      "30"
        "autoResize"                                                "0"
        "pinCorner"                                                 "0"
        "visible"                                                   "0"
        "enabled"                                                   "1"
        "image$_disabled_"                                          "../hud/color_panel_red"
    }

    "moveablesubpanel"
    {
        "fieldName"                                                 "bh_MoveableSubPanel"

        "moveableiconbg"
        {
            "ypos"                                                  "r-6969"
            "visible"                                               "0"
            "enabled"                                               "0"
            "ControlName"                                           "CIconPanel"
            "fieldName"                                             "MoveableIconBG"
            "xpos"                                                  "0"
            "zpos"                                                  "0"
            "wide"                                                  "10"
            "tall"                                                  "36"
            "icon"                                                  "obj_status_alert_background_tall_nocolor"
            "iconColor"                                             "HudBlack"
            "scaleImage"                                            "1"
        }

        "moveableicon"
        {
            "ypos"                                                  "r-6969"
            "visible"                                               "0"
            "enabled"                                               "0"
            "ControlName"                                           "CIconPanel"
            "fieldName"                                             "MoveableIcon"
            "xpos"                                                  "5"
            "zpos"                                                  "11"
            "wide"                                                  "14"
            "tall"                                                  "14"
            "icon"                                                  "obj_status_sentrygun_1"
            "drawcolor"                                             "ProgressOffWhite"
            "scaleImage"                                            "1"
        }

        "moveablesymbolicon"
        {
            "ypos"                                                  "r-6969"
            "visible"                                               "0"
            "enabled"                                               "0"
            "ControlName"                                           "ImagePanel"
            "fieldName"                                             "MoveableSymbolIcon"
            "xpos"                                                  "16"
            "zpos"                                                  "12"
            "wide"                                                  "16"
            "tall"                                                  "8"
            "image"                                                 "../hud/eng_sel_item_movable"
            "drawcolor"                                             "ProgressOffWhite"
            "scaleImage"                                            "1"
        }

        "moveablekeylabel"
        {
            "ypos"                                                  "r-6969"
            "visible"                                               "0"
            "enabled"                                               "0"
            "ControlName"                                           "Label"
            "fieldName"                                             "MoveableKeyLabel"
            "font"                                                  "TFFontMedium"
            "font$_disabled_"                                       "DefaultVerySmall"
            "xpos"                                                  "0"
            "zpos"                                                  "1"
            "wide"                                                  "640"
            "tall"                                                  "24"
            "autoResize"                                            "0"
            "pinCorner"                                             "0"
            "labelText"                                             "%movekey%"
            "textAlignment"                                         "North"
            "dulltext"                                              "0"
            "brighttext"                                            "0"
        }
        "ControlName"                                               "EditablePanel"
        "xpos"                                                      "0"
        "ypos"                                                      "0"
        "zpos"                                                      "-5"
        "wide"                                                      "32"
        "tall"                                                      "36"
        "visible"                                                   "1"
        "enabled"                                                   "1"
    }
}
